-- =============================================================================
-- 037  CUSTOMER 360
--
-- What the customer record shows that the CRM did not yet keep:
--
--   crm_tag / crm_party_tag             labels staff put on a customer
--   crm_party_relationship_type         spouse, parent company, affiliate ...
--   crm_party_relationship              one customer's relation to another
--   crm_party_interaction               calls, emails, chats and messages, with
--                                       the agent and how it ended
--   crm_party_note / crm_party_file     staff notes and attached documents
--   crm_party_team_member               who looks after the customer
--   crm_party_agreement                 contracts with the customer
--   crm_organization (+5 columns)       local name, size, headquarters, about
--
-- New CRM tables and columns only; no Crystal table is touched.
-- =============================================================================

CREATE TABLE crm_tag (
    tag_id                             int            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_code                           varchar(50)    NOT NULL UNIQUE,
    tag_name                           varchar(100)   NOT NULL,
    color_scheme                       varchar(20)    NOT NULL DEFAULT 'gray'
                                       CHECK (color_scheme IN ('gray','green','blue','purple','pink','orange','red','teal','yellow','cyan')),
    description                        varchar(255)   NULL,
    is_active                          boolean        NOT NULL DEFAULT true,
    created_at                         timestamptz    NOT NULL DEFAULT now()
);
COMMENT ON TABLE crm_tag IS 'Labels staff put on customers (High value, Early adopter ...). Basic data.';

CREATE TABLE crm_party_tag (
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    tag_id                             int            NOT NULL REFERENCES crm_tag(tag_id) ON DELETE CASCADE,
    tagged_at                          timestamptz    NOT NULL DEFAULT now(),
    tagged_by_manager_id               integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    PRIMARY KEY (party_id, tag_id)
);
CREATE INDEX idx_crm_party_tag_tag ON crm_party_tag(tag_id);

CREATE TABLE crm_party_relationship_type (
    relationship_type_code             varchar(40)    PRIMARY KEY,
    relationship_name                  varchar(100)   NOT NULL,
    inverse_code                       varchar(40)    NOT NULL,
    applies_to                         varchar(20)    NOT NULL CHECK (applies_to IN ('PERSON','ORGANIZATION','ANY')),
    is_hierarchy                       boolean        NOT NULL DEFAULT false,
    sort_order                         smallint       NOT NULL DEFAULT 0,
    is_active                          boolean        NOT NULL DEFAULT true
);
COMMENT ON TABLE crm_party_relationship_type IS 'A row (A, B, T) reads "B is the T of A"; inverse_code is what A is to B. is_hierarchy marks the parent-company link the group tree follows.';

CREATE TABLE crm_party_relationship (
    party_relationship_id              bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    related_party_id                   bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    relationship_type_code             varchar(40)    NOT NULL REFERENCES crm_party_relationship_type(relationship_type_code),
    status                             varchar(20)    NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','ENDED')),
    valid_from                         date           NULL,
    valid_to                           date           NULL,
    note                               varchar(255)   NULL,
    created_by_manager_id              integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now(),
    updated_at                         timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT chk_crm_party_rel_self CHECK (party_id <> related_party_id),
    CONSTRAINT chk_crm_party_rel_period CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);
CREATE UNIQUE INDEX uq_crm_party_rel_active ON crm_party_relationship(party_id, related_party_id, relationship_type_code) WHERE status = 'ACTIVE';
CREATE INDEX idx_crm_party_rel_related ON crm_party_relationship(related_party_id, status);

CREATE TABLE crm_party_interaction (
    interaction_id                     bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    project_id                         int            NULL REFERENCES crm_project(project_id),
    direction                          varchar(10)    NOT NULL CHECK (direction IN ('INBOUND','OUTBOUND')),
    channel_code                       varchar(20)    NOT NULL CHECK (channel_code IN ('EMAIL','PHONE','SMS','CHAT','IN_PERSON','APP','WEB','LETTER','PUSH')),
    interaction_type                   varchar(30)    NOT NULL CHECK (interaction_type IN ('GENERAL_INQUIRY','PRODUCT_SUPPORT','ORDER_INQUIRY',
                                                     'COMPLAINT','FEEDBACK','SALES','SERVICE_NOTICE','MARKETING','FOLLOW_UP')),
    purpose_id                         int            NULL REFERENCES crm_communication_purpose(purpose_id),
    subject                            varchar(250)   NOT NULL,
    body                               text           NULL,
    case_id                            bigint         NULL REFERENCES crm_service_case(case_id) ON DELETE SET NULL,
    contact_point_id                   bigint         NULL REFERENCES crm_contact_point(contact_point_id) ON DELETE SET NULL,
    destination_snapshot               varchar(500)   NULL,
    manager_id                         integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    outcome_code                       varchar(20)    NOT NULL CHECK (outcome_code IN ('ANSWERED','FOLLOW_UP','RESOLVED','CLOSED','NO_ANSWER','QUEUED','SENT','FAILED')),
    occurred_at                        timestamptz    NOT NULL DEFAULT now(),
    duration_seconds                   integer        NULL CHECK (duration_seconds >= 0),
    created_at                         timestamptz    NOT NULL DEFAULT now()
);
COMMENT ON TABLE crm_party_interaction IS 'One contact with a customer outside a campaign: a call taken, an email answered, a message sent from the customer record.';
CREATE INDEX idx_crm_party_interaction_party ON crm_party_interaction(party_id, occurred_at DESC);
CREATE INDEX idx_crm_party_interaction_case ON crm_party_interaction(case_id) WHERE case_id IS NOT NULL;

CREATE TABLE crm_party_note (
    note_id                            bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    note_text                          text           NOT NULL,
    is_pinned                          boolean        NOT NULL DEFAULT false,
    created_by_manager_id              integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now(),
    updated_at                         timestamptz    NOT NULL DEFAULT now(),
    deleted_at                         timestamptz    NULL
);
CREATE INDEX idx_crm_note_party ON crm_party_note(party_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE crm_party_file (
    file_id                            bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    file_name                          varchar(255)   NOT NULL,
    storage_key                        varchar(255)   NOT NULL UNIQUE,
    content_type                       varchar(100)   NOT NULL,
    byte_size                          bigint         NOT NULL CHECK (byte_size >= 0),
    description                        varchar(255)   NULL,
    uploaded_by_manager_id             integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now(),
    deleted_at                         timestamptz    NULL
);
COMMENT ON TABLE crm_party_file IS 'A document kept with a customer. The bytes live in the private CRM file folder, never under the public uploads; storage_key is the name there.';
CREATE INDEX idx_crm_file_party ON crm_party_file(party_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE crm_party_team_member (
    team_member_id                     bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    manager_id                         integer        NOT NULL REFERENCES managers(id) ON DELETE CASCADE,
    team_role                          varchar(30)    NOT NULL CHECK (team_role IN ('ACCOUNT_MANAGER','SALES_REP','SUPPORT_MANAGER')),
    assigned_at                        timestamptz    NOT NULL DEFAULT now(),
    ended_at                           timestamptz    NULL,
    assigned_by_manager_id             integer        NULL REFERENCES managers(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX uq_crm_team_role_current ON crm_party_team_member(party_id, team_role) WHERE ended_at IS NULL;
CREATE INDEX idx_crm_team_manager ON crm_party_team_member(manager_id) WHERE ended_at IS NULL;

CREATE TABLE crm_party_agreement (
    agreement_id                       bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id                           bigint         NOT NULL REFERENCES crm_party(party_id) ON DELETE CASCADE,
    agreement_no                       varchar(60)    NULL,
    agreement_type                     varchar(30)    NOT NULL CHECK (agreement_type IN ('ENTERPRISE','RESELLER','DISTRIBUTION','SERVICE_LEVEL','PURCHASE','PARTNERSHIP')),
    title                              varchar(200)   NULL,
    start_date                         date           NOT NULL,
    end_date                           date           NULL,
    renewal_date                       date           NULL,
    status                             varchar(20)    NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','EXPIRED','TERMINATED')),
    annual_value                       numeric(20,4)  NULL CHECK (annual_value >= 0),
    currency_code                      varchar(3)     NULL REFERENCES crm_currency(currency_code),
    note                               text           NULL,
    created_by_manager_id              integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now(),
    updated_at                         timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT chk_crm_agreement_period CHECK (end_date IS NULL OR end_date >= start_date)
);
CREATE INDEX idx_crm_agreement_party ON crm_party_agreement(party_id, status);

ALTER TABLE crm_organization ADD COLUMN local_name varchar(250) NULL;
ALTER TABLE crm_organization ADD COLUMN employee_count_band varchar(20) NULL
    CHECK (employee_count_band IN ('1-10','11-50','51-200','201-1000','1001-5000','5001+'));
ALTER TABLE crm_organization ADD COLUMN description text NULL;
ALTER TABLE crm_organization ADD COLUMN headquarters_location_id bigint NULL REFERENCES crm_location(location_id);
ALTER TABLE crm_organization ADD COLUMN headquarters_address varchar(255) NULL;

INSERT INTO crm_tag (tag_code, tag_name, color_scheme) VALUES
 ('HIGH_VALUE', 'High value', 'green'), ('TECH_ENTHUSIAST', 'Tech enthusiast', 'blue'), ('EARLY_ADOPTER', 'Early adopter', 'pink'),
 ('VIP', 'VIP', 'purple'), ('PRICE_SENSITIVE', 'Price sensitive', 'orange'), ('NEEDS_ATTENTION', 'Needs attention', 'red'),
 ('KEY_ACCOUNT', 'Key account', 'purple'), ('STRATEGIC_ACCOUNT', 'Strategic account', 'teal');

INSERT INTO crm_party_relationship_type (relationship_type_code, relationship_name, inverse_code, applies_to, is_hierarchy, sort_order) VALUES
 ('SPOUSE', 'Spouse', 'SPOUSE', 'PERSON', false, 1),
 ('PARENT', 'Parent', 'CHILD', 'PERSON', false, 2),
 ('CHILD', 'Child', 'PARENT', 'PERSON', false, 3),
 ('SIBLING', 'Sibling', 'SIBLING', 'PERSON', false, 4),
 ('RELATIVE', 'Family member', 'RELATIVE', 'PERSON', false, 5),
 ('REFERRER', 'Referred by', 'REFERRAL', 'ANY', false, 6),
 ('REFERRAL', 'Referred', 'REFERRER', 'ANY', false, 7),
 ('PARENT_COMPANY', 'Parent company', 'SUBSIDIARY', 'ORGANIZATION', true, 10),
 ('SUBSIDIARY', 'Subsidiary', 'PARENT_COMPANY', 'ORGANIZATION', false, 11),
 ('AFFILIATE', 'Affiliate', 'AFFILIATE', 'ORGANIZATION', false, 12),
 ('PARTNER', 'Business partner', 'PARTNER', 'ORGANIZATION', false, 13);

INSERT INTO crm_org_contact_role (role_code, role_name) VALUES
 ('DECISION_MAKER', 'Decision maker'), ('INFLUENCER', 'Influencer'), ('PURCHASING', 'Purchasing'),
 ('OPERATIONAL', 'Operational'), ('REPRESENTATIVE', 'Legal representative')
ON CONFLICT (role_code) DO NOTHING;
