-- =====================================================================
-- Delta 038 - a person's job is a choice from a list, a person can be
-- marked as checked by staff, and an organization has a location.
--
--   crm_job_title                   NEW: the job list (seeded from the vendor's JOBS)
--   crm_person.job_title            varchar  -> job_title_id int -> crm_job_title
--   crm_person.nationality_code     dropped
--   crm_person.preferred_language   dropped
--   crm_person.id_card_hash         dropped
--   crm_person.id_card_masked       -> is_checked_manually boolean
--   crm_organization.headquarters_location_id -> location_id
--
-- A job title typed before this delta is not lost: every distinct value that
-- is not already on the list is added to it, and the person points at it.
-- =====================================================================

CREATE TABLE crm_job_title (
    job_title_id                       int            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_code                           varchar(30)    NOT NULL UNIQUE,
    job_name                           varchar(100)   NOT NULL UNIQUE,
    sort_order                         smallint       NOT NULL DEFAULT 0,
    is_active                          boolean        NOT NULL DEFAULT true
);
COMMENT ON TABLE crm_job_title IS 'The job titles a person can be given. Seeded from the vendor JOBS list; edited at /admin/crm/settings.';

INSERT INTO crm_job_title (job_code, job_name, sort_order) VALUES
 ('WORKER', 'Worker', 1), ('FARMER', 'Farmer', 2), ('TEACHER', 'Teacher', 3), ('SCIENTIST', 'Scientist', 4),
 ('ENGINEER', 'Engineer', 5), ('EMPLOYEE', 'Employee', 6), ('ARTISTE', 'Artiste', 7), ('ATHLETE', 'Athlete', 8),
 ('DOCTOR', 'Doctor', 9), ('STUDENT', 'Student', 10), ('PUBLIC_CATERING', 'Public catering', 11),
 ('PUPIL', 'Pupil', 12), ('OTHER', 'Other', 99);

/* the titles people already have, so none is lost */
INSERT INTO crm_job_title (job_code, job_name, sort_order)
SELECT left(upper(regexp_replace(trim(t.job_title), '[^A-Za-z0-9]+', '_', 'g')), 24) || '_' || row_number() OVER (ORDER BY t.job_title),
       left(trim(t.job_title), 100), 100
  FROM (SELECT DISTINCT trim(job_title) AS job_title FROM crm_person
         WHERE job_title IS NOT NULL AND trim(job_title) <> '') t
 WHERE NOT EXISTS (SELECT 1 FROM crm_job_title j WHERE lower(j.job_name) = lower(t.job_title));

ALTER TABLE crm_person ADD COLUMN job_title_id int NULL REFERENCES crm_job_title(job_title_id);
UPDATE crm_person p SET job_title_id = j.job_title_id
  FROM crm_job_title j
 WHERE p.job_title IS NOT NULL AND lower(j.job_name) = lower(trim(p.job_title));

ALTER TABLE crm_person ADD COLUMN is_checked_manually boolean NOT NULL DEFAULT false;

ALTER TABLE crm_person DROP COLUMN job_title;
ALTER TABLE crm_person DROP COLUMN nationality_code;
ALTER TABLE crm_person DROP COLUMN preferred_language;
ALTER TABLE crm_person DROP COLUMN id_card_hash;
ALTER TABLE crm_person DROP COLUMN id_card_masked;

CREATE INDEX idx_crm_person_job ON crm_person(job_title_id) WHERE job_title_id IS NOT NULL;
CREATE INDEX idx_crm_person_unchecked ON crm_person(party_id) WHERE NOT is_checked_manually;
COMMENT ON COLUMN crm_person.is_checked_manually IS 'true once a manager has reviewed this person by hand. Who and when is in audit_log.';

ALTER TABLE crm_organization RENAME COLUMN headquarters_location_id TO location_id;
