-- Phase 1: preserve relationships while replacing public-id FKs with numeric PKs.
CREATE TEMP TABLE phase1_columns ON COMMIT DROP AS
SELECT table_name::text, column_name::text FROM information_schema.columns
 WHERE table_schema=current_schema() AND table_name LIKE 'crm\_%'
 AND (column_name='party_id' OR column_name LIKE '%\_party_id')
 AND column_name <> 'transaction_party_id' AND NOT (table_name='crm_party' AND column_name='party_id');
CREATE TEMP TABLE phase1_constraints ON COMMIT DROP AS
SELECT c.conrelid::regclass::text AS table_name, c.conname, pg_get_constraintdef(c.oid) AS definition
FROM pg_constraint c WHERE c.connamespace=current_schema()::regnamespace AND c.contype IN ('f','c')
AND EXISTS (SELECT 1 FROM pg_attribute a JOIN phase1_columns p ON p.column_name=a.attname
WHERE a.attrelid=c.conrelid AND a.attnum=ANY(c.conkey) AND p.table_name=c.conrelid::regclass::text);
CREATE TEMP TABLE phase1_views ON COMMIT DROP AS
SELECT viewname, definition FROM pg_views WHERE schemaname=current_schema() AND viewname IN ('v_crm_current_holding','v_crm_point_account_drift');
DROP VIEW IF EXISTS v_crm_current_holding;
DROP VIEW IF EXISTS v_crm_point_account_drift;
DO $$ DECLARE r record; BEGIN
 FOR r IN SELECT * FROM phase1_constraints LOOP
 EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',r.table_name,r.conname); END LOOP;
 FOR r IN SELECT DISTINCT table_name FROM phase1_columns LOOP
 EXECUTE format('ALTER TABLE %I DISABLE TRIGGER USER',r.table_name); END LOOP;
 FOR r IN SELECT * FROM phase1_columns LOOP
 EXECUTE format('UPDATE %I t SET %I=''phase1:'' || p.party_pk::text FROM crm_party p WHERE t.%I=p.party_id',r.table_name,r.column_name,r.column_name);
 EXECUTE format('ALTER TABLE %I ALTER COLUMN %I TYPE bigint USING substring(%I from 8)::bigint',r.table_name,r.column_name,r.column_name);
 EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I',r.table_name,r.column_name,replace(r.column_name,'party_id','party_pk'));
 END LOOP;
 FOR r IN SELECT * FROM phase1_constraints LOOP
 EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s',r.table_name,r.conname,replace(r.definition,'party_id','party_pk')); END LOOP;
 FOR r IN SELECT DISTINCT table_name FROM phase1_columns LOOP
 EXECUTE format('ALTER TABLE %I ENABLE TRIGGER USER',r.table_name); END LOOP;
 FOR r IN SELECT * FROM phase1_views LOOP
 EXECUTE format('CREATE VIEW %I AS %s',r.viewname,replace(r.definition,'party_id','party_pk')); END LOOP;
END $$;
CREATE OR REPLACE FUNCTION crm_check_party_subtype() RETURNS trigger AS $$
DECLARE expected text := CASE TG_TABLE_NAME WHEN 'crm_person' THEN 'PERSON' ELSE 'ORGANIZATION' END; actual text;
BEGIN
 SELECT party_type INTO actual FROM crm_party WHERE party_pk=NEW.party_pk;
 IF actual IS DISTINCT FROM expected THEN RAISE EXCEPTION '% needs a % party',TG_TABLE_NAME,expected; END IF;
 RETURN NEW;
END $$ LANGUAGE plpgsql;
COMMENT ON COLUMN crm_party.party_pk IS 'Phase 1 customer key, referenced by CRM foreign keys and returned to departments.';
COMMENT ON COLUMN crm_party.party_id IS 'Reserved public identifier; not used as a foreign key in phase 1.';

ALTER TABLE crm_identity_match_candidate DROP CONSTRAINT crm_identity_match_candidate_match_score_check;
ALTER TABLE crm_identity_match_candidate ALTER COLUMN match_score TYPE numeric(5,0) USING round(match_score * 100);
ALTER TABLE crm_identity_match_candidate ADD CHECK (match_score BETWEEN 0 AND 110);

CREATE TABLE crm_registration_intake (
 intake_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_project_id bigint REFERENCES crm_project(project_id),
 source_record_id text,
 category text NOT NULL DEFAULT 'PERSON' CHECK (category IN ('PERSON','ESHOP')),
 status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','MERGED','CREATED','ASSIGNED','REJECTED')),
 payload jsonb NOT NULL,
 candidates jsonb NOT NULL DEFAULT '[]',
 party_pk bigint REFERENCES crm_party(party_pk),
 reviewed_by_manager_id integer REFERENCES managers(id),
 reviewed_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_project_id,source_record_id,category)
);
CREATE INDEX idx_crm_intake_pending ON crm_registration_intake(category,status,created_at);
CREATE TABLE crm_identity_resolution (
 resolution_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 intake_id bigint NOT NULL UNIQUE REFERENCES crm_registration_intake(intake_id),
 source_project_id bigint REFERENCES crm_project(project_id),
 source_record_id text,
 party_pk bigint NOT NULL REFERENCES crm_party(party_pk),
 outcome text NOT NULL,
 acknowledged_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now()
);
-- Existing e-shop assignments are retained as candidates pending explicit review.
INSERT INTO crm_registration_intake(source_project_id,source_record_id,category,payload,candidates)
SELECT a.project_id,a.external_account_id,'ESHOP',
 jsonb_build_object('account',to_jsonb(a),'party',jsonb_build_object('display_name',p.display_name)),
 jsonb_build_array(jsonb_build_object('party_pk',a.party_pk,'display_name',p.display_name,'reason','Existing e-shop assignment'))
FROM crm_project_account a JOIN crm_project project USING(project_id) JOIN crm_party p USING(party_pk)
WHERE project.project_code='ESHOP' AND a.unlinked_at IS NULL;
UPDATE crm_project_account a SET unlinked_at=now(),is_primary=false
FROM crm_project project WHERE a.project_id=project.project_id AND project.project_code='ESHOP' AND a.unlinked_at IS NULL;
