-- Delta 044. Safe to run on a database built from the current schema.sql.

-- 1. A project's type is a free label the console edits; it no longer has a fixed list.
ALTER TABLE crm_project DROP CONSTRAINT IF EXISTS crm_project_project_type_code_check;

-- 2. Department systems call the CRM with a key issued to their project.
CREATE TABLE IF NOT EXISTS crm_project_api_key (
    api_key_id                         bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                         int            NOT NULL REFERENCES crm_project(project_id),
    key_prefix                         varchar(16)    NOT NULL UNIQUE,
    key_hash                           char(64)       NOT NULL,
    label                              varchar(100)   NOT NULL,
    last_used_at                       timestamptz    NULL,
    revoked_at                         timestamptz    NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now()
);
COMMENT ON TABLE crm_project_api_key IS 'Keys a department system uses for /api/integration/crm. Only the SHA-256 of the secret is stored; the project comes from the key, never the request.';
CREATE INDEX IF NOT EXISTS idx_crm_project_api_key_project ON crm_project_api_key(project_id) WHERE revoked_at IS NULL;
