-- Delta 047. Safe to run on a database built from the current schema.sql.

-- Rows of a customer Excel import that failed the file check. Valid rows are
-- imported; these are kept with their reasons so an administrator can see and
-- fix what was not loaded.
CREATE TABLE IF NOT EXISTS crm_person_import_error (
    import_error_id                    bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_hash                         char(64)       NOT NULL,
    file_name                          varchar(255)   NULL,
    row_number                         int            NOT NULL,
    cells                              jsonb          NOT NULL,
    errors                             jsonb          NOT NULL,
    status                             varchar(20)    NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','DISMISSED')),
    imported_by_manager_id             integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    dismissed_by_manager_id            integer        NULL REFERENCES managers(id) ON DELETE SET NULL,
    dismissed_at                       timestamptz    NULL,
    created_at                         timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT uq_crm_person_import_error_row UNIQUE (batch_hash, row_number)
);
COMMENT ON TABLE crm_person_import_error IS 'Customer Excel import rows that failed the file check, with the cells as written and every reason. Valid rows of the same file are imported.';
CREATE INDEX IF NOT EXISTS idx_crm_person_import_error_open ON crm_person_import_error(status, created_at);
