const { ESHOP_ORDER_STATUS_NAME, JOB_NAME, LOCAL_DEFAULT_CITY, NEWS_SOURCE_NAME, LEVEL_PHONE_NAME, LEVEL_EPROD_NAME, AGENCY_MARS } = require('../lang/en');

const DOWNLOAD_PATH = "downloads";
const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_MAX_LIMIT = 1000;
const FLAG_NONE = 0;
const FLAG_SET = 1;
const FLAG_EXIST = 0;
const FLAG_DELETED = 1;
const FLAG_ACTIVE = 1;
const FLAG_INACTIVE = 0;
const FLAG_READ = 1;
const FLAG_TO_ALL = 1;
const FLAG_USER = 0;
const FLAG_AGENCY = 1;
const FLAG_LOTTERY = 0;
const FLAG_LOCKED = 1;
const FLAG_TESTER = 1;
const FLAG_FAVORITE = 1;

const REPORT_COUNT_FOR_BLOCK = 5;
const REPORT_MAX_COUNT_FOR_SAME = 3;

const ORACLE_VALUE_MAXLEN = 1500;

const ROOT_MANAGER_PK = 1;
const CID_LENGTH = 10;

const MANAGER_ROLES = {
  NONE: 0,
  READ: 1,
  WRITE: 2,
  SUPER: 3,
};

const NOTIFICATION_STATUS = {
  PENDING: 0,
  SHOW: 1,
};

const PHONE_TYPE = {
  USER: 0,
  REPORT: 1,
  FEEDBACK: 2,
  MANAGER: 3,
  EPROD: 4,
};
const PHONE_NUMBER_MAX_COUNT = 3;

const ACTION_TYPE = {
  USER: 0,
  MANAGER: 1,
};

const USER_PROPERTY_TYPE = {
  USER_NAME: 0,
  BIRTHDAY: 1,
  ID_CARD: 2,
  CID: 3,
  JOB: 4,
  LOCATION: 5,
  GENDER: 6,
};

const USER_PWD_APP_TYPE = {
  APPSTORE: 1,
  ESHOP: 2,
  MASS: 3, // OS_4
};

const USER_PWD_STATUS = {
  PENDING: 0,
  SUCCESS: 1,
  IGNORE: 2,
};

const USER_REG_APP_TYPE = {
  APPSTORE: 1,
  ESHOP: 2,
  MASS: 3, // OS_4
};

const USER_REG_STATUS = {
  PENDING: 0,
  SUCCESS: 1,
  IGNORE: 2,
};

const DUTY_TYPE = {
  DAILY: 0,
  PERIOD: 1,
};

const DUTY_ACTION = {
  EVERY_LOGIN: 100,
  PERIOD_SURVEY_ALL: 200,
  PERIOD_SURVEY_ONE: 201,
  PERIOD_USER_PROFILE: 207,
};

const ESHOP_ORDER_STATUS_LIST = [
  { id: -5, name: ESHOP_ORDER_STATUS_NAME.REFUNDED },
  { id: -4, name: ESHOP_ORDER_STATUS_NAME.REFUND_ACCEPT },
  { id: -3, name: ESHOP_ORDER_STATUS_NAME.REFUND_PENDING },
  { id: -2, name: ESHOP_ORDER_STATUS_NAME.CANCELED },
  { id: -1, name: ESHOP_ORDER_STATUS_NAME.CANCEL_PENDING },
  { id: 0, name: ESHOP_ORDER_STATUS_NAME.ORDER_PENDING },
  { id: 1, name: ESHOP_ORDER_STATUS_NAME.ORDER_PENDING },
  { id: 2, name: ESHOP_ORDER_STATUS_NAME.ORDER_PENDING },
  { id: 3, name: ESHOP_ORDER_STATUS_NAME.ORDER_ACCEPT },
  { id: 4, name: ESHOP_ORDER_STATUS_NAME.ORDER_ACCEPT },
  { id: 5, name: ESHOP_ORDER_STATUS_NAME.DELIVERING },
  { id: 6, name: ESHOP_ORDER_STATUS_NAME.DELIVERING },
  { id: 7, name: ESHOP_ORDER_STATUS_NAME.ORDER_FINISH },
  { id: 8, name: ESHOP_ORDER_STATUS_NAME.ORDER_FINISH },
  { id: 9, name: ESHOP_ORDER_STATUS_NAME.DELIVERED },
];

const ESHOP_LOG_TYPE = {
  TRANSACTION: 0,
  EXP: 1,
  COMMERCE_VALUE: 2,
};

const ESHOP_WALLET_LOG_TYPE = {
  TRANSACTION: 0,
  EXP: 1,
  COMMERCE_VALUE: 10,
};

const ESHOP_WALLET_SHOP_ID = 1;

const MERGE_ID_TYPE = {
  FIXED: 0,
  APPSTORE: 1,
  ESHOP: 2,
  MASS: 3, // OS_4
};

const MERGE_TYPE = {
  MERGE: 0,
  SPLIT: 1,
};

const FIXED_STATUS = {
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
  CANCELED: 3,
};

const USER_VERIFY_STATUS = {
  NONE: 0,
  DONE: 1,
}

const APP_UPDATE_TYPE = {
  PATCH: 1,
  APK: 2,
  TEST: 3,
};

const PRODUCT_IMAGE_TYPE = {
  MAIN: 0,
  INTRO: 1,
};

const API_TIMEOUT = 15 * 1000; // 15 seconds

const POINT_TYPE_PREFIXES = {
  FIXED: 10,
  MOBILE: 20,
  BLOG: 30,
  DUTY_DAILY: 40,
  DUTY_PERIOD: 50,
  MANAGER: 90,
  OTHER: 99,
};

const POINT_TYPE_VALUES = {
  FIXED_DAILY_LOGIN_PREFIX: 1000,
  FIXED_DAILY_LOGIN_FIRST: 100001,
  FIXED_DAILY_LOGIN_LAST: 100007,
  FIXED_HOLIDAY: 100101,
  FIXED_BIRTHDAY: 100201,
  FIXED_MERGE_ID: 101001,
  MOBILE_DAILY_LOGIN_PREFIX: 2000,
  MOBILE_DAILY_LOGIN_FIRST: 200001,
  MOBILE_DAILY_LOGIN_LAST: 200007,
  MOBILE_HOLIDAY: 200101,
  MOBILE_BIRTHDAY: 200201,
  MOBILE_REGISTER: 209001,
  BLOG_POST_ARTICLE_DISCUSS: 300001,
  BLOG_REPLY_ARTICLE: 300002,
  BLOG_CORRECT_ARTICLE: 300003,
  BLOG_POST_BBS_HUMOR: 300004,
  BLOG_POST_BBS_TECH: 300005,
  BLOG_POST_ARTICLE_PRHN: 300006,
  BLOG_POST_ARTICLE_INFO: 300007,
  BLOG_POST_ARTICLE_SCIENCE: 300008,
  BLOG_POST_ARTICLE_ECONOMY: 300009,
  BLOG_RECOM_GOLD: 300101,
  BLOG_RECOM_SILVER: 300102,
  BLOG_RECOM_BRONZE: 300103,
  BLOG_COPY_ARTICLE_PUBLISHED: 900001,
  BLOG_COPY_ARTICLE_PENDING: 900002,
  BLOG_COPY_BBS_PUBLISHED: 900004,
  BLOG_COPY_BBS_PENDING: 900004,
  MANAGER_MANUAL_PLUS: 900101,
  MANAGER_MANUAL_MINUS: 900102,
  MANAGER_MANUAL_REPORT: 900103,
  MANAGER_BOOK_MINUS: 900104,
};

const POINT_TYPE_HASHES = {
  MOBILE_DAILY_LOGIN: "MOBILE_DAILY_LOGIN",
  FIXED_DAILY_LOGIN: "FIXED_DAILY_LOGIN",
  FIXED_BIRTHDAY: "FIXED_BIRTHDAY",
  FIXED_HOLIDAY: "FIXED_HOLIDAY",
  BLOG_POST_ARTICLE_DISCUSS: "BLOG_POST_ARTICLE",
  BLOG_REPLY_ARTICLE: "BLOG_REPLY_ARTICLE",
  BLOG_CORRECT_ARTICLE: "BLOG_CORRECT_ARTICLE",
  BLOG_POST_BBS_HUMOR: "BLOG_POST_BBS",
  BLOG_POST_BBS_TECH: "BLOG_POST_BBS_TECH",
  BLOG_POST_ARTICLE_PRHN: "BLOG_POST_ARTICLE_PRHN",
  BLOG_POST_ARTICLE_INFO: "BLOG_POST_ARTICLE_INFO",
  BLOG_POST_ARTICLE_SCIENCE: "BLOG_POST_ARTICLE_SCIENCE",
  BLOG_POST_ARTICLE_ECOMONY: "BLOG_POST_ARTICLE_ECONOMY",
  BLOG_RECOM_GOLD: "BLOG_RECOM_GOLD",
  BLOG_RECOM_SILVER: "BLOG_RECOM_SILVER",
  BLOG_RECOM_BRONZE: "BLOG_RECOM_BRONZE",
  BLOG_COPY_ARTICLE_PUBLISHED: "BLOG_COPY_ARTICLE_PUBLISHED",
  BLOG_COPY_ARTICLE_PENDING: "BLOG_COPY_ARTICLE_PENDING",
  BLOG_COPY_BBS_PUBLISHED: "BLOG_COPY_BBS_PUBLISHED",
  BLOG_COPY_BBS_PENDING: "BLOG_COPY_BBS_PENDING",
}

const POINT_MANAGER_MANUAL = {
  ACTIVITY: 0,
  SOFT: 1,
  REGISTER: 2,
};

const RESERVE_TYPES = {
  NORMAL: 0,
  REWARD: 1,
};

const RESERVE_SOURCES = {
  ESHOP: 0,
  SOFTWARE: 1,
  EPROD_REG: 2,
  ACTIVITY: 3,
  CREDIT: 4,
  LOTTERY: 5,
  PHONE_REG: 6,
  AGENCY_SOFT_APPSTORE: 7,
  AGENCY_SOFT_EPROD: 8,
  AGENCY_SALE_EPROD: 9,
  AGENCY_AS_EPROD: 10,
  AGENCY_AS_PHONE: 11,
  AGENCY_STANDARD: 12,
};

const RESERVE_STATUS = {
  PENDING: 0,
  RESERVED: 1,
  PAID: 2,
  SALED: 3,
  UNKNOWN: 4,
};

const PHONE_BOOK_STATUS = {
  PENDING: 0,
  ACCEPT: 1,
  SALED: 2,
};

const RESERVE_SMS_STATUS = {
  SMS_ACCEPT: 0,
  RESERVE_PENDING: 1,
  RESERVED: 2,
  SALE_FINISH: 3,
};

const FEEDBACK_STATUS = {
  PENDING: 0,
  REPLIED: 1,
  IGNORED: 2,
};

const THREAD_STATUS = {
  DISCUSSING: 0,
  RESOLVED: 1,
  FINISHED: 2,
};

const FEEDBACK_THREAD_LAST_TYPE = {
  PENDING: 0,
  REPLIED: 1,
};

const FEEDBACK_THREAD_SOURCES = {
  PID: 0,
  FIXED: 1,
};

const FEEDBACK_CATEGORY = {
  PID: 0,
  PHONE_SALE: 1,
  EPROD_REG: 2,
  ESHOP: 3,
  APPSTORE: 4,
  CONTACT: 5,
  PHONE_AS: 6,
  PHONE_REG: 7,
  EPRODUCT: 8,
  BLOG: 9,
  FIXED: 10,
  MARS: 11,
};

const FEEDBACK_LEVEL = {
  NORMAL: 0,
};

const FEEDBACK_THREAD_MAX_COUNT_PER_DAY = 10;
const FEEDBACK_MESSAGE_MAX_COUNT_PER_DAY = 10;

const APP_POINT_PAGE = {
  ESHOP: 1,
  SOFT: 2,
  REGISTER: 3,
  ACTIVITY: 4,
};

const SURVEY_CATEGORY = {
  PID: 0,
  EPRODUCT: 1,
  PHONE_SALE: 2,
  PHONE_AS: 3,
  APPSTORE: 4,
  ESHOP: 5,
  MARS: 6,
};

const DEPARTMENTS = [
  { id: 0, name: "Integrate", feedback_indices: [ FEEDBACK_CATEGORY.PID, FEEDBACK_CATEGORY.CONTACT, FEEDBACK_CATEGORY.PHONE_REG, FEEDBACK_CATEGORY.FIXED, FEEDBACK_CATEGORY.BLOG], app_pages: [APP_POINT_PAGE.ACTIVITY, APP_POINT_PAGE.REGISTER], survey_indices: [SURVEY_CATEGORY.PID] },
  { id: 1, name: "Phone", feedback_indices: [ FEEDBACK_CATEGORY.PHONE_SALE, FEEDBACK_CATEGORY.PHONE_AS], app_pages: [APP_POINT_PAGE.REGISTER], survey_indices: [SURVEY_CATEGORY.PHONE_SALE, SURVEY_CATEGORY.PHONE_AS] },
  { id: 2, name: "Appstore", feedback_indices: [ FEEDBACK_CATEGORY.APPSTORE], app_pages: [APP_POINT_PAGE.SOFT], survey_indices: [SURVEY_CATEGORY.APPSTORE] },
  { id: 3, name: "Eproduct", feedback_indices: [ FEEDBACK_CATEGORY.EPROD_REG, FEEDBACK_CATEGORY.EPRODUCT], app_pages: [APP_POINT_PAGE.SOFT, APP_POINT_PAGE.REGISTER], survey_indices: [SURVEY_CATEGORY.EPRODUCT] },
  { id: 4, name: "Commerce", feedback_indices: [ FEEDBACK_CATEGORY.ESHOP, FEEDBACK_CATEGORY.MARS], app_pages: [APP_POINT_PAGE.ESHOP], survey_indices: [SURVEY_CATEGORY.ESHOP, SURVEY_CATEGORY.MARS] },
];

const JOBS = [
  { id: 1, name: JOB_NAME.WORKER },
  { id: 2, name: JOB_NAME.FARMER },
  { id: 3, name: JOB_NAME.TEACHER },
  { id: 4, name: JOB_NAME.SCIENTIST },
  { id: 5, name: JOB_NAME.ENGINEER },
  { id: 6, name: JOB_NAME.EMPLOYEE },
  { id: 7, name: JOB_NAME.ARTISTE },
  { id: 8, name: JOB_NAME.ATHLETE },
  { id: 9, name: JOB_NAME.DOCTOR },
  { id: 10, name: JOB_NAME.STUDENT },
  { id: 11, name: JOB_NAME.PUBLIC_CATERING },
  { id: 12, name: JOB_NAME.PUPIL },
  { id: 13, name: JOB_NAME.ETC },
];

const ACTIVITY_LIMIT_SOURCES = {
  ACTIVITY: 0,
  SOFTWARE: 1,
  REGISTER: 2,
  ESHOP: 3,
};

const ACTIVITY_POINT_PREDEFINED_RELATED_PKS = {
  FIXED: "-1",
};

const SOFT_POINT_TYPES = {
  APPSTORE: 0,
  KARAOKE: 1,
  BMEDIA: 2,
  MANAGER: 3,
};

const SOFT_POINT_STATUS = {
  PLUS: 0,
  MINUS: 1,
  REFUND: 2,
};

const SOFT_POINT_PREDEFINED_RELATED_PKS = {
  FIXED_APPSTORE: "-1",
  KARAOKE: "-2",
  BMEDIA: "-3",
  MOBILE_APPSTORE: "-4",
  SYNC_APPSTORE: "-5",
};

const REGISTER_POINT_STATUS = {
  PLUS: 0,
  MINUS: 1,
  REFUND: 2,
};

const SYNC_STATUS = {
  PENDING: 0,
  APPROVED: 1,
};

const ARTICLE_STATES = {
  PUB_REQUEST: 0,
  PUB_ADMIN_AGREE: 1,
  PUB_ADMIN_DENY: 2,
  PUB_ADMIN_PENDING: 3,
  PUB_APPROVED: 4,
  PUB_DENY: 5,
  PUB_CANCEL: 6,
  PUB_PENDING: 7,
  PUB_TEMP: -2,
};

const OLD_RESERVE_TYPES = {
  NORMAL: 0,
  REWARD: 1,
};

const OLD_PRIZE_FILL_TYPES = {
  MINUS_PRIZE: 5,
};

const OLD_BLOG_RATING_LIMIT = 5;

const OLD_BLOG_RATING_TYPES = {
  GOLD: 1,
  SILVER: 2,
  BRONZE: 3,
};

const PHONE_MODEL_SPLITTER = "?";

const REG_POINT_STATUS = {
  PLUS: 0,
  MINUS: 1,
  REFUND: 2,
};

const REG_POINT_TYPES = {
  PHONE: 0,
  EPROD: 1,
  MANAGER: 2,
};

const USER_FIXED_FUNC_TYPES = {
  APPSTORE: 1,
  EPROD_SOFT: 2,
  EPROD_REGISTER: 3,
};

const USER_FIXED_STATUS = {
  PENDING: 0,
  SUCCESS: 1,
  IGNORED: 2,
};

const OLD_BLOG_HELP_STATUS = {
  CORRECT_CHECK: 4,
};

const OLD_BLOG_MANAGER_ID = "jc225";
const OLD_BLOG_SUBJECT_IDS = {
  DISCUSS: 1,
};

const OLD_BLOG_SEARCH_TYPES = {
  ALL: 0,
  TITLE: 1,
  AUTHOR: 2,
};

const OLD_BLOG_ARTICLE_TYPES = {
  ALL: 0,
  BBS: 1,
  BLOG: 2,
};

const PRIZE_FILL_TYPES = {
  BLOG: 2,
};

const MANAGER_ROLE_PAGE_SUFFIX = {
  FEEDBACK_THREAD: "user/feedback_threads",
  SURVEY_GROUP: "survey/surveys",
  AGENCY_PHONE: "agency/phone_agencies",
  AGENCY_EPROD: "agency/eprod_agencies",
};

const REPORT_STATUS = {
  NONE: -1,
  PENDING: 0,
  ACCEPTED: 1,
  DENIED: 2,
  CANCELED: 3,
};

const WEATHER_STATION_ORDER_NONE = 999;
const WEATHER_STATION_DEFAULT = LOCAL_DEFAULT_CITY;

const LOTTERY_NUMBER_LEN = 5; // max count = 90000 because 10000 ~ 99999
const GOODS_TYPE_ACTIVITY_POINT = 7;

const PHONE_REG_MAX_POINTS = 18;
const EPROD_REG_MAX_POINTS = 20;
const INTEGRATED_VALUE_RATES = {
  REGISTER: 400,
  ESHOP: 1,
  SOFT: 0.25, // * 2000 / 0.2 / 40000
  ACTIVITY: 0.02, // /50
};

const ESHOP_COMBINE_TYPE_ID = 0;

const NEWS_SOURCES = {
  MORNING: 1,
  POLESTAR: 2,
};
const NEWS_SOURCE_NAMES = [
  { id: NEWS_SOURCES.MORNING, name: NEWS_SOURCE_NAME.MORNING },
  { id: NEWS_SOURCES.POLESTAR, name: NEWS_SOURCE_NAME.POLESTAR },
];

const NEWS_STATUS = {
  COPY: 0,
  ADMIN_ACCEPT: 2,
  ADMIN_DENY: 3,
  PUB_PENDING: 4,
  PUB_ACCEPT: 5,
  PUB_DENY: 6,
  PUB_CANCEL: 7,
  NOTICE: 8,
  NEWS_CANCEL: 9,
};

const NEWS_SUMMARY_MAX_LEN = 100;

const NEWS_CATEGORY = {
  SCIENCE_TECH: 1,
  ECONOMY_INFO: 81,
  HEALTH_INFO: 62,
};

const POLESTAR_CATEGORY = {
  SCIENCE_TECH: 4,
  ECONOMY_INFO: 2,
  HEALTH_INFO: 7,
};

const PREMIUM_SERVICE_TYPES = {
  YEAREND_2025: 0,
  LOTTERY_PERIOD: 1,
  WOMENSDAY_2026: 2,
  PUZZLE: 3,
};

const PREMIUM_SERVICE_WOMENSDAY_SERVICE_PK = 100050;
const PREMIUM_SERVICE_WOMENSDAY_RESULT_TIME = "2026-03-08 01:00:00";
const PREMIUM_SERVICE_WOMENSDAY_DISP_DATE = "2026-03-15";
const PREMIUM_SERVICE_WOMENSDAY_BLOG_START_DATE = "2026-02-28";
const PREMIUM_SERVICE_WOMENSDAY_BLOG_END_DATE = "2026-03-07";
const PREMIUM_SERVICE_WOMENSDAY_ARTICLE_PK = 973891;
const PREMIUM_SERVICE_WOMENSDAY_ARTICLE_MAX_THUMBS = 5;
const PREMIUM_SERVICE_26_03_SERVICE_PK = 100060;

const ESHOP_ID_FILTERS = {
  PID: 1,
  ESHOP: 2,
};

const CLASSIFY_PHONE_RULE = {
  RATIO_9: 6,
  RATIO_7: 4,
  RATIO_5: 3,
  RATIO_3: 2,
  USAGE: 6,
  PURCHASE: 2.5,
  FEEDBACK: 1,
  PROFILE: 0.5,
};

const CLASSIFY_PHONE_LEVELS = [
  { id: 0, name: LEVEL_PHONE_NAME.LV0, min: 0, max: 18 },
  { id: 1, name: LEVEL_PHONE_NAME.LV1, min: 18, max: 27.5 },
  { id: 2, name: LEVEL_PHONE_NAME.LV2, min: 27.5, max: 40 },
  { id: 3, name: LEVEL_PHONE_NAME.LV3, min: 40, max: 63 },
  { id: 4, name: LEVEL_PHONE_NAME.LV4, min: 63, max: 70 },
  { id: 5, name: LEVEL_PHONE_NAME.LV5, min: 70, max: 83 },
  { id: 6, name: LEVEL_PHONE_NAME.LV6, min: 83, max: 112 },
  { id: 7, name: LEVEL_PHONE_NAME.LV7, min: 112, max: 999 },
];

const CLASSIFY_EPROD_RULE = {
  TV_3: 6.8,
  TV_2: 4.5,
  TV_1: 2.5,
  STB: 1.25,
  NOTECOM: 2.5,
  PC: 2.5,
  CAMERA: 3,
  PHONE: 2.5,
  OTHER: 1.25,
  USAGE: 6,
  PURCHASE: 2.5,
  FEEDBACK: 1,
  PROFILE: 0.5,
};

const CLASSIFY_EPROD_LEVELS = [
  { id: 0, name: LEVEL_EPROD_NAME.LV0, min: 0, max: 7.5 },
  { id: 1, name: LEVEL_EPROD_NAME.LV1, min: 7.5, max: 23.5 },
  { id: 2, name: LEVEL_EPROD_NAME.LV2, min: 23.5, max: 51 },
  { id: 3, name: LEVEL_EPROD_NAME.LV3, min: 51, max: 73.5 },
  { id: 4, name: LEVEL_EPROD_NAME.LV4, min: 73.5, max: 103.3 },
  { id: 5, name: LEVEL_EPROD_NAME.LV5, min: 103.3, max: 130.3 },
  { id: 6, name: LEVEL_EPROD_NAME.LV6, min: 130.3, max: 145.3 },
  { id: 7, name: LEVEL_EPROD_NAME.LV7, min: 145.3, max: 164.3 },
  { id: 8, name: LEVEL_EPROD_NAME.LV8, min: 164.3, max: 179.3 },
  { id: 9, name: LEVEL_EPROD_NAME.LV9, min: 179.3, max: 999 },
];

const ID_PREFIX_PID = "pid_";
const ID_PREFIX_PH = "ph_";

const PHONE_SALE_AGENCY_MARS = AGENCY_MARS;
const PHONE_AGENCY_TYPE = {
  SALE: 0,
  AS: 1,
  STANDARD: 2,
};

const CUSTOMER_SOURCE = {
  PID: 0,
  PHONE: 1,
  EPROD: 2,
  MARS: 3,
  ESHOP: 4,
};

const CUSTOMER_STATUS = {
  INACTIVE: 0,
  ACTIVE: 1,
};

const CRM_PROD_SPEC_KEY_TYPE = {
  SINGLE_CHOICE: 0,
  MULTI_CHOICE: 1,
  ORDER_CHOICE: 2,
  TEXT: 3,
};

const EPROD_REGISTER_STATUS = {
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
  TRANSFERED: 3,
  DELETED: 4,
  VERIFIED: 5,
};

const EPROD_REGISTER_SOURCE = {
  FIXED: 1,
  MOBILE: 2,
};

const CRM_SPLITTER = "&";

const FAQ_CATEGORY = {
  PID: 0,
  PHONE: 1,
  TV: 2,
  STB: 3,
  PC: 4,
  CAMERA: 5,
  ETC: 6,
  APPSTORE: 7,
};

const USER_TYPE = {
  PID: 0,
  FIXED: 1,
};

module.exports = {
  DOWNLOAD_PATH,
  DEFAULT_PAGE_SIZE,
  DEFAULT_MAX_LIMIT,
  FLAG_NONE,
  FLAG_SET,
  FLAG_EXIST,
  FLAG_DELETED,
  FLAG_ACTIVE,
  FLAG_INACTIVE,
  FLAG_READ,
  FLAG_TO_ALL,
  FLAG_USER,
  FLAG_AGENCY,
  FLAG_LOTTERY,
  FLAG_LOCKED,
  FLAG_TESTER,
  FLAG_FAVORITE,
  REPORT_COUNT_FOR_BLOCK,
  REPORT_MAX_COUNT_FOR_SAME,
  ORACLE_VALUE_MAXLEN,
  ROOT_MANAGER_PK,
  CID_LENGTH,
  MANAGER_ROLES,
  NOTIFICATION_STATUS,
  PHONE_TYPE,
  PHONE_NUMBER_MAX_COUNT,
  ACTION_TYPE,
  USER_PROPERTY_TYPE,
  USER_PWD_APP_TYPE,
  USER_PWD_STATUS,
  USER_REG_APP_TYPE,
  USER_REG_STATUS,
  DUTY_TYPE,
  DUTY_ACTION,
  ESHOP_ORDER_STATUS_LIST,
  ESHOP_LOG_TYPE,
  ESHOP_WALLET_LOG_TYPE,
  ESHOP_WALLET_SHOP_ID,
  MERGE_ID_TYPE,
  MERGE_TYPE,
  FIXED_STATUS,
  USER_VERIFY_STATUS,
  API_TIMEOUT,
  APP_UPDATE_TYPE,
  PRODUCT_IMAGE_TYPE,
  POINT_TYPE_PREFIXES,
  POINT_TYPE_VALUES,
  POINT_TYPE_HASHES,
  POINT_MANAGER_MANUAL,
  RESERVE_TYPES,
  RESERVE_SOURCES,
  RESERVE_STATUS,
  PHONE_BOOK_STATUS,
  RESERVE_SMS_STATUS,
  JOBS,
  ACTIVITY_LIMIT_SOURCES,
  ACTIVITY_POINT_PREDEFINED_RELATED_PKS,
  SOFT_POINT_TYPES,
  SOFT_POINT_STATUS,
  SOFT_POINT_PREDEFINED_RELATED_PKS,
  REGISTER_POINT_STATUS,
  FEEDBACK_STATUS,
  THREAD_STATUS,
  FEEDBACK_THREAD_LAST_TYPE,
  FEEDBACK_THREAD_SOURCES,
  FEEDBACK_CATEGORY,
  FEEDBACK_LEVEL,
  FEEDBACK_THREAD_MAX_COUNT_PER_DAY,
  FEEDBACK_MESSAGE_MAX_COUNT_PER_DAY,
  APP_POINT_PAGE,
  SURVEY_CATEGORY,
  DEPARTMENTS,
  SYNC_STATUS,
  ARTICLE_STATES,
  OLD_RESERVE_TYPES,
  OLD_PRIZE_FILL_TYPES,
  OLD_BLOG_RATING_LIMIT,
  OLD_BLOG_RATING_TYPES,
  PHONE_MODEL_SPLITTER,
  REG_POINT_STATUS,
  REG_POINT_TYPES,
  USER_FIXED_FUNC_TYPES,
  USER_FIXED_STATUS,
  OLD_BLOG_HELP_STATUS,
  OLD_BLOG_MANAGER_ID,
  OLD_BLOG_SUBJECT_IDS,
  OLD_BLOG_SEARCH_TYPES,
  OLD_BLOG_ARTICLE_TYPES,
  PRIZE_FILL_TYPES,
  MANAGER_ROLE_PAGE_SUFFIX,
  REPORT_STATUS,
  WEATHER_STATION_ORDER_NONE,
  WEATHER_STATION_DEFAULT,
  LOTTERY_NUMBER_LEN,
  GOODS_TYPE_ACTIVITY_POINT,
  PHONE_REG_MAX_POINTS,
  EPROD_REG_MAX_POINTS,
  INTEGRATED_VALUE_RATES,
  NEWS_SOURCES,
  NEWS_SOURCE_NAMES,
  NEWS_STATUS,
  NEWS_SUMMARY_MAX_LEN,
  NEWS_CATEGORY,
  POLESTAR_CATEGORY,
  PREMIUM_SERVICE_TYPES,
  PREMIUM_SERVICE_WOMENSDAY_SERVICE_PK,
  PREMIUM_SERVICE_WOMENSDAY_RESULT_TIME,
  PREMIUM_SERVICE_WOMENSDAY_DISP_DATE,
  PREMIUM_SERVICE_WOMENSDAY_ARTICLE_PK,
  PREMIUM_SERVICE_WOMENSDAY_ARTICLE_MAX_THUMBS,
  PREMIUM_SERVICE_WOMENSDAY_BLOG_START_DATE,
  PREMIUM_SERVICE_WOMENSDAY_BLOG_END_DATE,
  PREMIUM_SERVICE_26_03_SERVICE_PK,
  ESHOP_COMBINE_TYPE_ID,
  ESHOP_ID_FILTERS,
  CLASSIFY_PHONE_RULE,
  CLASSIFY_PHONE_LEVELS,
  CLASSIFY_EPROD_RULE,
  CLASSIFY_EPROD_LEVELS,
  ID_PREFIX_PID,
  ID_PREFIX_PH,
  PHONE_SALE_AGENCY_MARS,
  PHONE_AGENCY_TYPE,
  CUSTOMER_SOURCE,
  CUSTOMER_STATUS,
  CRM_PROD_SPEC_KEY_TYPE,
  EPROD_REGISTER_STATUS,
  EPROD_REGISTER_SOURCE,
  CRM_SPLITTER,
  FAQ_CATEGORY,
  USER_TYPE,
};
