// routes/authRoutes.js
const express = require('express');
const router = express.Router();
const multer = require('multer');
const { upload } = require('../middleware/upload');
const authController = require('../controllers/authController');
const managerController = require('../controllers/admin/adminManagerController');
const userController = require('../controllers/admin/adminUserController');
const advertiseController = require('../controllers/admin/adminAdvertiseController');
const deviceController = require('../controllers/admin/adminDeviceController');
const messageController = require('../controllers/admin/adminMessageController');
const surveyController = require('../controllers/admin/adminSurveyController');
const expController = require('../controllers/admin/adminExperienceController');
const pointController = require('../controllers/admin/adminPointController');
const reserveController = require('../controllers/admin/adminReserveController');
const baseController = require('../controllers/admin/adminBaseController');
const productController = require('../controllers/admin/adminProductController');
const blogController = require('../controllers/admin/adminBlogController');
const agencyController = require('../controllers/admin/adminAgencyController');
const weatherController = require('../controllers/admin/adminWeatherController');
const premiumController = require('../controllers/admin/adminPremiumController');
const newsController = require('../controllers/admin/adminNewsController');
const classifyController = require('../controllers/admin/adminClassifyController');
const crmController = require('../controllers/admin/adminCrmController');
const commonController = require('../controllers/common/commonPrhnController');
const { validateResetManager, validateDeleteByManagerPk, validateAddManager, validateEditManager, validateChangePasswordManager, validateDeleteByRolePk, validateAddRole, validateEditRole, validateDeleteByPagePk, validateAddPage, validateEditPage, validateRolePages, validateRolePerms, validateUpdateDepart, validateEditUserAdmin } = require('../middleware/adminManagerValidators');
const { validateResetUser, validateDeleteUserByPk, validateAddTester,validateEditTester,validateAddUser, validateEditUser, validateAddPhone, validateDeletePhoneByPk, validateForwardUserPassword, validateForwardUserFixed, validateForwardUserRegister, validateMergeUserId, validateSplitUserId, validateDeleteLocationByPk, validateAddLocation, validateEditLocation, validateAddWhiteUser, validateEditWhiteUser, validateDeleteWhiteUser, validateGetCidLocks, validateAddCidLock, validateDeleteCidLock } = require('../middleware/adminUserValidators');
const { validateDeleteByAdPk, validateAddAdvertise, validateEditAdvertise, validateDeleteLayoutByPk, validateAddLayout, validateEditLayout, validateFetchLayoutAds, validateDeleteLayoutAdByPk, validateAddLayoutAd, validateEditLayoutAd, validateDeleteHomeConfigByPk, validateAddHomeConfig, validateEditHomeConfig, validateDeleteMenu, validateAddMenu, validateEditMenu, validateAddHomePopup, validateEditHomePopup, validateDeleteHomePopup, validateSyncHomePopup, validateAddPageBanner, validateEditPageBanner, validateDeletePageBanner, validateSyncPageBanner, validateSyncAdvertise } = require('../middleware/adminAdvertiseValidators');
const { validateDeleteDevice, validateReportDevice, validateEditReport, validateAddSmartPhone, validateEditSmartPhone, validateDeleteSmartPhone } = require('../middleware/adminDeviceValidators');
const { validateDeleteFeedback, validateAddComment, validateFetchBroadcastByUserPk, validateAddBroadcast, validateEditBroadcast, validateDeleteBroadcast, validateAddNotification, validateEditNotification, validateDeleteNotificationByPk, validateAddFaq, validateEditFaq, validateDeleteFaq, validateEditFeedback, validateEditFeedbackThread, validateAddFeedbackMessage, validateDeleteFeedbackMessage, validateForwardFeedbackMessage, validateLevelFeedbackMessage, validateProcessPhoneNumberMessage, validatePhoneSaleBroadcast } = require('../middleware/adminMessageValidators');
const { validateAddSurvey, validateEditSurvey, validateDeleteSurvey, validateQuestions, validateAddQuestion, validateEditQuestion, validateDeleteQuestion, validateChoices, validateAddChoice, validateEditChoice, validateDeleteChoice, validateStatsSurvey, validateWomenStatsDetail } = require('../middleware/adminSurveyValidators');
const { validateAddDuty, validateEditDuty, validateDeleteDuty } = require('../middleware/adminExperienceValidators');
const { validateAddPointType, validateEditPointType, validateGetActivityLimitBySource, validateAddActivityLimit, validateEditActivityLimit, validateRecalcActivityLimit, validateAddRegisterPointType, validateEditRegisterPointType, validateAddRegisterPointLog, validateEditUserPoint, validateMinusPrizeLog, validateActivityPointBalance, validateRecalcActivityPoint, validateRegisterPointBalance, validateEshopWalletBalance, validateEshopWalletTransactions, validateAppstoreWalletBalance, validateRecalcAppstorePoint, validateRecalcKaraokePoint, validateRecalcBMediaPoint, validateRecalcSoftMinusPoint } = require('../middleware/adminPointValidators');
const { validateAddReservePrefix, validateEditReservePrefix, validateDeleteReservePrefix, validateMinusReservePrefix, validateAddReserveUsers, validateEditReserveUser, validateDeleteReserveUser, validateAddReserveLog, validateEditReserveLog, validateDeleteReserveLog, validateAddOldReservePrefix, validateEditOldReservePrefix, validateAddOldReservations, validateAddOldReserveLog, validateEditOldReserveLog, validateDeleteOldReserveLog, validateSmsReservePrefix, validateSyncPhoneBook, validateSyncPhoneBooks } = require('../middleware/adminReserveValidators');
const { validateAddHoliday, validateEditHoliday, validateDeleteHoliday, validateDeleteUpdateFile,validateAddUpdateFile,validateEditUpdateFile, validateSyncUpdateFile, validateAddTempFile, validateDeleteTempFile, validateAddCompanyContact, validateEditCompanyContact, validateDeleteCompanyContact } = require('../middleware/adminBaseValidators');
const { validateAddProductCategory, validateEditProductCategory, validateDeleteProductCategory, validateAddProduct, validateEditProduct, validateDeleteProduct, validateSyncProduct, validateAddProductImage, validateEditProductImage, validateDeleteProductImage, validateSyncProductImage, validateAddProductSpecKey, validateEditProductSpecKey, validateDeleteProductSpecKey, validateAddProductSpecOrder, validateEditProductSpecOrder, validateDeleteProductSpecOrder, validateGetProductSpecValues, validateSubmitProductSpecValues, validateAddProductModel, validateEditProductModel, validateDeleteProductModel, validateAddRegisterPhoneLog, validateGetEprodRegistAddLog, validateGetEprodRegistMinusLog, validateAddPhoneImeiPrefix, validateDeletePhoneImeiPrefix, validateGetPhoneAccessories, validateAddPhoneAccessory, validateEditPhoneAccessory, validateDeletePhoneAccessory, validateAddPhoneChangelog, validateEditPhoneChangelog, validateDeletePhoneChangelog } = require('../middleware/adminProductValidators');
const { validateAddPhoneAgency, validateEditPhoneAgency, validateDeletePhoneAgency, validateAddEprodAgency, validateEditEprodAgency, validateDeleteEprodAgency, validateEditPhoneSaleAgency, validateDeletePhoneSaleAgency } = require('../middleware/adminAgencyValidators');
const { validateAddPremiumService, validateEditPremiumService, validateDeletePremiumService, validateAddPremiumGood, validateEditPremiumGood, validateDeletePremiumGood, validateAddPremiumUserClass, validateEditPremiumUserClass, validateDeletePremiumUserClass, validateAddUserDeliveryAddress, validateEditUserDeliveryAddress, validateDeleteUserDeliveryAddress, validateAddLotteryNumber, validateEditLotteryNumber, validateDeleteLotteryNumber, validateRefreshLotteryNumber, validateGetSelectedLotteryNumbers, validateGetRemainLotteryNumbers, validateGetPremiumSimpleClasses, validateSyncPremiumService, validateAddIntegratedUserClass, validateEditIntegratedUserClass, validateDeleteIntegratedUserClass, validateRefreshIntegratedUserValue, validateAddPremiumDiscussAward, validateEditPremiumDiscussAward, validateDeletePremiumDiscussAward, validateEditPremiumReception, validateAddPremiumReception, validateAddLotteryCandidate, validateEditLotteryCandidate, validateDeleteLotteryCandidate, validateGetSelectedLotterySubmits, validateGetRemainLotterySubmits, validateRandomLotterySubmit, validateAddLotterySubmit, validateEditLotterySubmit, validateDeleteLotterySubmit, validateEditLotterySubmitAward, validateFinishLotterySubmitAward, validatePuzzQuestions, validateEditPuzzQuestion, validateAddPuzzQuestion, validateDeletePuzzQuestion, validatePuzzChoices, validateDeletePuzzChoice, validateEditPuzzChoice, validateAddPuzzChoice, validateAddPuzzleAward, validateEditPuzzleAward, validateDeletePuzzleAward, validateFinishPuzzleAward, validateEditPuzzleBonus, validateAddPuzzleBonus, validatePuzzleAnswerDetail, validatePuzzleAnswerStats } = require('../middleware/adminPremiumValidators');
const { validateAddNewsCategory, validateEditNewsCategory, validateDeleteNewsCategory, validateAddNewsArticle, validateEditNewsArticle, validateDeleteNewsArticle, validateGetNewsContent } = require('../middleware/adminNewsValidators');
const { validateAddCrmProduct, validateEditCrmProduct, validateDeleteCrmProduct, validateAddCrmProdSpecKey, validateEditCrmProdSpecKey, validateDeleteCrmProdSpecKey, validateAddCrmProdSpecValue, validateEditCrmProdSpecValue, validateDeleteCrmProdSpecValue, validateAddCrmProdSpecOrder, validateEditCrmProdSpecOrder, validateDeleteCrmProdSpecOrder, validateAddCrmProdSurveyOption, validateEditCrmProdSurveyOption, validateDeleteCrmProdSurveyOption, validateImportCrmEprodSales } = require('../middleware/adminCrmValidators');
const RESP_CODES = require('../constants/responseCodes');

// Middleware to handle Multer errors (file upload errors)
const handleMulterErrors = (err, req, res, next) => {
  if (err instanceof multer.MulterError) {
    // Multer specific error (e.g., file size limit, unsupported file type)
    return res.status(RESP_CODES.BAD_REQUEST.code).json({ code: RESP_CODES.BAD_REQUEST.code, message: err.message });
  } else if (err) {
    // Other errors (e.g., server error)
    return res.status(RESP_CODES.INTERNAL_SERVER_ERROR.code).json({ code: RESP_CODES.INTERNAL_SERVER_ERROR.code, message: err.message });
  }
  next();
};

router.get('/managers', authController.verifyAdminToken, managerController.fetchManagers);
router.post('/manager_reset', authController.verifyAdminToken, validateResetManager, managerController.resetPassword);
router.post('/manager_change_password', authController.verifyAdminToken, validateChangePasswordManager, managerController.changePassword);
router.post('/manager_delete', authController.verifyAdminToken, validateDeleteByManagerPk, managerController.deleteByManagerPk);
router.post('/manager_add', authController.verifyAdminToken, validateAddManager, managerController.addManager);
router.post('/manager_edit', authController.verifyAdminToken, validateEditManager, managerController.editManager);

router.get('/manager_roles', authController.verifyAdminToken, managerController.fetchRoles);
router.post('/role_delete', authController.verifyAdminToken, validateDeleteByRolePk, managerController.deleteByRolePk);
router.post('/role_add', authController.verifyAdminToken, validateAddRole, managerController.addRole);
router.post('/role_edit', authController.verifyAdminToken, validateEditRole, managerController.editRole);
router.get('/role_perms', authController.verifyAdminToken, validateRolePages, managerController.getRolePerms);
router.post('/role_perm_update', authController.verifyAdminToken, validateRolePerms, managerController.updateRolePerm);
router.post('/role_depart_update', authController.verifyAdminToken, validateUpdateDepart, managerController.updateRoleDepart);

router.get('/manager_pages', authController.verifyAdminToken, managerController.fetchPages);
router.post('/page_delete', authController.verifyAdminToken, validateDeleteByPagePk, managerController.deleteByPagePk);
router.post('/page_add', authController.verifyAdminToken, validateAddPage, managerController.addPage);
router.post('/page_edit', authController.verifyAdminToken, validateEditPage, managerController.editPage);

router.get('/user_admins', authController.verifyAdminToken, managerController.fetchUserAdmins);
router.post('/user_admin_edit', authController.verifyAdminToken, validateEditUserAdmin, managerController.editUserAdmin);

router.get('/locations', authController.verifyAdminToken, userController.fetchLocations);
router.get('/provinces', authController.verifyAdminToken, commonController.fetchProvinces);
router.post('/location_delete', authController.verifyAdminToken, validateDeleteLocationByPk, userController.deleteLocationByPk);
router.post('/location_add', authController.verifyAdminToken, validateAddLocation, userController.addLocation);
router.post('/location_edit', authController.verifyAdminToken, validateEditLocation, userController.editLocation);

router.get('/testers', authController.verifyAdminToken, userController.fetchTesters);
router.post('/tester_add', authController.verifyAdminToken, validateAddTester, userController.addTester);
router.post('/tester_edit', authController.verifyAdminToken, validateEditTester, userController.editTester);
router.post('/tester_delete', authController.verifyAdminToken, validateEditTester, userController.deleteTesterByPk);

router.get('/users', authController.verifyAdminToken, userController.fetchUsers);
router.post('/user_reset', authController.verifyAdminToken, validateResetUser, userController.resetPassword);
router.post('/user_delete', authController.verifyAdminToken, validateDeleteUserByPk, userController.deleteUserByPk);
router.post('/user_add', authController.verifyAdminToken, validateAddUser, userController.addUser);
router.post('/user_edit', authController.verifyAdminToken, validateEditUser, userController.editUser);
router.get('/users_export', authController.verifyAdminToken, userController.exportUsers);
router.post('/user_phone_add', authController.verifyAdminToken, validateAddPhone, userController.addPhone);
router.post('/user_phone_delete', authController.verifyAdminToken, validateDeletePhoneByPk, userController.deletePhoneByPk);
router.get('/user_edit_log', authController.verifyAdminToken, userController.fetchUserEditLogs);
router.get('/user_password_log', authController.verifyAdminToken, userController.fetchUserPasswordLogs);
router.post('/user_password_forward', authController.verifyAdminToken, validateForwardUserPassword, userController.forwardUserPasswordLog);
router.post('/merge_userid', authController.verifyAdminToken, validateMergeUserId, userController.mergeUserId);
router.post('/split_userid', authController.verifyAdminToken, validateSplitUserId, userController.splitUserId);
router.get('/merge_log', authController.verifyAdminToken, userController.fetchMergeLogs);
router.get('/user_fixed_log', authController.verifyAdminToken, userController.fetchUserFixedLogs);
router.post('/user_fixed_forward', authController.verifyAdminToken, validateForwardUserFixed, userController.forwardUserFixedLog);
router.get('/user_register_log', authController.verifyAdminToken, userController.fetchUserRegisterLogs);
router.post('/user_register_forward', authController.verifyAdminToken, validateForwardUserRegister, userController.forwardUserRegisterLog);
router.get('/user_login_log', authController.verifyAdminToken, userController.fetchUserLoginLogs);
router.get('/user_block_log', authController.verifyAdminToken, userController.fetchUserBlockLogs);
router.get('/user_stats_by_user', authController.verifyAdminToken, userController.fetchUserStatsByUser);
router.get('/user_stats_by_register', authController.verifyAdminToken, userController.fetchUserStatsByRegister);
router.get('/user_stats_by_login', authController.verifyAdminToken, userController.fetchUserStatsByLogin);
router.get('/user_stats_by_phone', authController.verifyAdminToken, userController.fetchUserStatsByPhone);
router.get('/user_stats_on_dashboard', authController.verifyAdminToken, userController.fetchUserStatsOnDashboard);

router.get('/white_users', authController.verifyAdminToken, userController.fetchWhiteUsers);
router.post('/white_user_add', authController.verifyAdminToken, validateAddWhiteUser, userController.addWhiteUser);
router.post('/white_user_edit', authController.verifyAdminToken, validateEditWhiteUser, userController.editWhiteUser);
router.post('/white_user_delete', authController.verifyAdminToken, validateDeleteWhiteUser, userController.deleteWhiteUser);
router.get('/user_cid_locks', authController.verifyAdminToken, validateGetCidLocks, userController.fetchUserCidLockList);
router.post('/user_cid_lock_add', authController.verifyAdminToken, validateAddCidLock, userController.addUserCidLock);
router.post('/user_cid_lock_delete', authController.verifyAdminToken, validateDeleteCidLock, userController.deleteUserCidLock);

router.get('/advertisements', authController.verifyAdminToken, advertiseController.fetchAdvertisements);
router.post('/advertise_delete', authController.verifyAdminToken, validateDeleteByAdPk, advertiseController.deleteByAdPk);
router.post('/advertise_add', authController.verifyAdminToken, upload("ads").fields([{ name: "image_file", maxCount: 1 }, { name: "content_file", maxCount: 1 }]), handleMulterErrors, validateAddAdvertise, advertiseController.addAdvertisement);
router.post('/advertise_edit', authController.verifyAdminToken, upload("ads").fields([{ name: "image_file", maxCount: 1 }, { name: "content_file", maxCount: 1 }]), handleMulterErrors, validateEditAdvertise, advertiseController.editAdvertisement);
router.post('/advertise_sync', authController.verifyAdminToken, validateSyncAdvertise, advertiseController.syncAdvertisement);
router.get('/layouts', authController.verifyAdminToken, advertiseController.fetchLayouts);
router.post('/layout_delete', authController.verifyAdminToken, validateDeleteLayoutByPk, advertiseController.deleteLayoutByPk);
router.post('/layout_add', authController.verifyAdminToken, validateAddLayout, advertiseController.addLayout);
router.post('/layout_edit', authController.verifyAdminToken, validateEditLayout, advertiseController.editLayout);
router.get('/layout_ads', authController.verifyAdminToken, validateFetchLayoutAds, advertiseController.fetchLayoutAds);
router.get('/all_and_layout_ads', authController.verifyAdminToken, validateFetchLayoutAds, advertiseController.fetchAllAndLayoutAds);
router.get('/layout_ads_not_used', authController.verifyAdminToken, validateFetchLayoutAds, advertiseController.fetchAdsNotUsedByLayoutPk);
router.post('/layout_ad_delete', authController.verifyAdminToken, validateDeleteLayoutAdByPk, advertiseController.deleteLayoutAdByPk);
router.post('/layout_ad_add', authController.verifyAdminToken, validateAddLayoutAd, advertiseController.addLayoutAd);
router.post('/layout_ad_edit', authController.verifyAdminToken, validateEditLayoutAd, advertiseController.editLayoutAd);
router.get('/home_configs', authController.verifyAdminToken, advertiseController.fetchHomeConfigs);
router.post('/home_config_delete', authController.verifyAdminToken, validateDeleteHomeConfigByPk, advertiseController.deleteHomeConfigByPk);
router.post('/home_config_add', authController.verifyAdminToken, validateAddHomeConfig, advertiseController.addHomeConfig);
router.post('/home_config_edit', authController.verifyAdminToken, validateEditHomeConfig, advertiseController.editHomeConfig);
router.get('/home_menus', authController.verifyAdminToken, advertiseController.fetchMenus);
router.post('/home_menu_delete', authController.verifyAdminToken, validateDeleteMenu, advertiseController.deleteMenuByPk);
router.post('/home_menu_add', authController.verifyAdminToken, upload("menus").single("icon_file"), handleMulterErrors, validateAddMenu, advertiseController.addMenu);
router.post('/home_menu_edit', authController.verifyAdminToken, upload("menus").single("icon_file"), handleMulterErrors,validateEditMenu, advertiseController.editMenu);
router.get('/home_popups', authController.verifyAdminToken, advertiseController.fetchHomePopups);
router.post('/home_popup_add', authController.verifyAdminToken, upload("popups").single("image_file"), handleMulterErrors, validateAddHomePopup, advertiseController.addHomePopup);
router.post('/home_popup_edit', authController.verifyAdminToken, upload("popups").single("image_file"), handleMulterErrors, validateEditHomePopup, advertiseController.editHomePopup);
router.post('/home_popup_delete', authController.verifyAdminToken, validateDeleteHomePopup, advertiseController.deleteHomePopup);
router.post('/home_popup_sync', authController.verifyAdminToken, validateSyncHomePopup, advertiseController.syncHomePopup);
router.get('/page_banners', authController.verifyAdminToken, advertiseController.fetchPageBanners);
router.post('/page_banner_add', authController.verifyAdminToken, upload("banners").single("image_file"), handleMulterErrors, validateAddPageBanner, advertiseController.addPageBanner);
router.post('/page_banner_edit', authController.verifyAdminToken, upload("banners").single("image_file"), handleMulterErrors, validateEditPageBanner, advertiseController.editPageBanner);
router.post('/page_banner_delete', authController.verifyAdminToken, validateDeletePageBanner, advertiseController.deletePageBanner);
router.post('/page_banner_sync', authController.verifyAdminToken, validateSyncPageBanner, advertiseController.syncPageBanner);

router.get('/devices', authController.verifyAdminToken, deviceController.fetchDevices);
router.post('/device_delete', authController.verifyAdminToken, validateDeleteDevice, deviceController.deleteDevice);
router.post('/device_report', authController.verifyAdminToken, validateReportDevice, deviceController.reportDevice);
router.get('/reports', authController.verifyAdminToken, deviceController.fetchReports);
router.post('/report_edit', authController.verifyAdminToken, validateEditReport, deviceController.editReport);
router.get('/smart_phones', authController.verifyAdminToken, deviceController.fetchSmartPhones);
router.post('/smart_phone_add', authController.verifyAdminToken, validateAddSmartPhone, deviceController.addSmartPhone);
router.post('/smart_phone_edit', authController.verifyAdminToken, validateEditSmartPhone, deviceController.editSmartPhone);
router.post('/smart_phone_delete', authController.verifyAdminToken, validateDeleteSmartPhone, deviceController.deleteSmartPhone);
router.get('/phone_companies', authController.verifyAdminToken, deviceController.fetchPhoneCompanies);
router.post('/phone_models', authController.verifyAdminToken, deviceController.fetchPhoneModels);

router.get('/feedback_threads', authController.verifyAdminToken, messageController.fetchFeedbackThreads);
router.post('/feedback_thread_edit', authController.verifyAdminToken, validateEditFeedbackThread, messageController.editFeedbackThread);
router.post('/feedback_thread_reset_session', authController.verifyAdminToken, messageController.resetFeedbackThreadSession);
router.get('/feedback_messages', authController.verifyAdminToken, messageController.fetchFeedbackMessages);
router.post('/feedback_message_add', authController.verifyAdminToken, validateAddFeedbackMessage, messageController.addFeedbackMessage);
router.post('/feedback_message_delete', authController.verifyAdminToken, validateDeleteFeedbackMessage, messageController.deleteFeedbackMessage);
router.post('/feedback_message_forward', authController.verifyAdminToken, validateForwardFeedbackMessage, messageController.forwardFeedbackMessage);
router.post('/feedback_message_level', authController.verifyAdminToken, validateLevelFeedbackMessage, messageController.levelFeedbackMessage);
router.get('/feedback_replies', authController.verifyAdminToken, messageController.fetchFeedbackReplies);
router.post('/feedback_phone_number_process', authController.verifyAdminToken, validateProcessPhoneNumberMessage, messageController.processPhoneNumberMessage);
router.get('/broadcasts', authController.verifyAdminToken, messageController.fetchBroadcasts);
router.get('/broadcasts_by_user', authController.verifyAdminToken, validateFetchBroadcastByUserPk, messageController.fetchBroadcastsByUserPk);
router.post('/broadcast_add', authController.verifyAdminToken, validateAddBroadcast, messageController.addBroadcast);
router.post('/broadcast_edit', authController.verifyAdminToken, validateEditBroadcast, messageController.editBroadcast);
router.post('/broadcast_delete', authController.verifyAdminToken, validateDeleteBroadcast, messageController.deleteBroadcast);
router.post('/broadcast_phone_sale', authController.verifyAdminToken, validatePhoneSaleBroadcast, messageController.phoneSaleBroadcast);
router.get('/broad_users', authController.verifyAdminToken, messageController.fetchBroadUsers);
router.get('/notifications', authController.verifyAdminToken, messageController.fetchNotifications);
router.post('/notification_add', authController.verifyAdminToken, upload("news").single("image_file"), handleMulterErrors, validateAddNotification, messageController.addNotification);
router.post('/notification_edit', authController.verifyAdminToken, upload("news").single("image_file"), handleMulterErrors, validateEditNotification, messageController.editNotification);
router.post('/notification_delete', authController.verifyAdminToken, validateDeleteNotificationByPk, messageController.deleteNotificationByPk);
router.get('/faqs', authController.verifyAdminToken, messageController.fetchFaqs);
router.post('/faq_add', authController.verifyAdminToken, validateAddFaq, messageController.addFaq);
router.post('/faq_edit', authController.verifyAdminToken, validateEditFaq, messageController.editFaq);
router.post('/faq_delete', authController.verifyAdminToken, validateDeleteFaq, messageController.deleteFaqByPk);

router.get('/surveys', authController.verifyAdminToken, surveyController.fetchSurveys);
router.post('/survey_add', authController.verifyAdminToken, validateAddSurvey, surveyController.addSurvey);
router.post('/survey_edit', authController.verifyAdminToken, validateEditSurvey, surveyController.editSurvey);
router.post('/survey_delete', authController.verifyAdminToken, validateDeleteSurvey, surveyController.deleteSurveyByPk);
router.get('/survey_questions', authController.verifyAdminToken, validateQuestions, surveyController.fetchQuestionsBySurveyPk);
router.post('/survey_question_add', authController.verifyAdminToken, validateAddQuestion, surveyController.addQuestion);
router.post('/survey_question_edit', authController.verifyAdminToken, validateEditQuestion, surveyController.editQuestion);
router.post('/survey_question_delete', authController.verifyAdminToken, validateDeleteQuestion, surveyController.deleteQuestionByPk);
router.get('/survey_choices', authController.verifyAdminToken, validateChoices, surveyController.fetchChoicesByQuestionPk);
router.post('/survey_choice_add', authController.verifyAdminToken, validateAddChoice, surveyController.addChoice);
router.post('/survey_choice_edit', authController.verifyAdminToken, validateEditChoice, surveyController.editChoice);
router.post('/survey_choice_delete', authController.verifyAdminToken, validateDeleteChoice, surveyController.deleteChoiceByPk);
router.get('/survey_responses', authController.verifyAdminToken, surveyController.fetchResponses);
router.get('/survey_stats_by_user', authController.verifyAdminToken, validateStatsSurvey, surveyController.fetchSurveyStatsByUser);
router.get('/survey_stats_by_answer', authController.verifyAdminToken, validateStatsSurvey, surveyController.fetchSurveyStatsByAnswer);
router.post('/survey_stats_womens_calc', authController.verifyAdminToken, surveyController.calcSurveyStatsForWomensDay);
router.get('/survey_stats_womens_rank', authController.verifyAdminToken, surveyController.fetchWomenSurveyRespRank);
router.get('/survey_stats_womens_detail', authController.verifyAdminToken, validateWomenStatsDetail, surveyController.fetchWomenSurveyRespDetail);

router.get('/duties', authController.verifyAdminToken, expController.fetchDuties);
router.post('/duty_add', authController.verifyAdminToken, upload("exp").single("image_file"), handleMulterErrors, validateAddDuty, expController.addDuty);
router.post('/duty_edit', authController.verifyAdminToken, upload("exp").single("image_file"), handleMulterErrors,validateEditDuty, expController.editDuty);
router.post('/duty_delete', authController.verifyAdminToken, validateDeleteDuty, expController.deleteDutyByPk);
router.get('/achievements', authController.verifyAdminToken, expController.fetchAchievements);

router.get('/activity_point_types', authController.verifyAdminToken, pointController.fetchActivityPointTypes);
router.post('/activity_point_type_add', authController.verifyAdminToken, validateAddPointType, pointController.addActivityPointType);
router.post('/activity_point_type_edit', authController.verifyAdminToken, validateEditPointType, pointController.editActivityPointType);
router.get('/activity_point_balance', authController.verifyAdminToken, validateActivityPointBalance, pointController.fetchActivityPointBalance);
router.get('/activity_point_log', authController.verifyAdminToken, pointController.fetchActivityPointLog);
router.get('/activity_point_stats', authController.verifyAdminToken, pointController.fetchActivityPointStats);
router.post('/activity_point_recalc', authController.verifyAdminToken, validateRecalcActivityPoint, pointController.recalcActivityPointStats);
router.get('/activity_limits', authController.verifyAdminToken, pointController.fetchActivityLimits);
router.get('/activity_limit_by_source', authController.verifyAdminToken, validateGetActivityLimitBySource, pointController.fetchActivityLimitBySource);
router.post('/activity_limit_add', authController.verifyAdminToken, validateAddActivityLimit, pointController.addActivityLimit);
router.post('/activity_limit_edit', authController.verifyAdminToken, validateEditActivityLimit, pointController.editActivityLimit);
router.post('/activity_limit_recalc', authController.verifyAdminToken, validateRecalcActivityLimit, pointController.recalcActivityLimit);
router.get('/appstore_wallet_balance', authController.verifyAdminToken, validateAppstoreWalletBalance, pointController.fetchAppstoreWalletBalance);
router.get('/appstore_point_log', authController.verifyAdminToken, pointController.fetchAppstorePointLog);
router.get('/appstore_point_stats', authController.verifyAdminToken, pointController.fetchAppstorePointStats);
router.post('/appstore_point_recalc', authController.verifyAdminToken, validateRecalcAppstorePoint, pointController.recalcAppstorePointStats);
router.get('/karaoke_point_log', authController.verifyAdminToken, pointController.fetchKaraokePointLog);
router.get('/karaoke_point_stats', authController.verifyAdminToken, pointController.fetchKaraokePointStats);
router.post('/karaoke_point_recalc', authController.verifyAdminToken, validateRecalcKaraokePoint, pointController.recalcKaraokePointStats);
router.get('/bmedia_point_log', authController.verifyAdminToken, pointController.fetchBMediaPointLog);
router.get('/bmedia_point_stats', authController.verifyAdminToken, pointController.fetchBMediaPointStats);
router.post('/bmedia_point_recalc', authController.verifyAdminToken, validateRecalcBMediaPoint, pointController.recalcBMediaPointStats);
router.get('/soft_point_log', authController.verifyAdminToken, pointController.fetchSoftPointLog);
router.get('/soft_point_rank', authController.verifyAdminToken, pointController.fetchSoftPointRank);
router.post('/soft_point_recalc', authController.verifyAdminToken, validateRecalcSoftMinusPoint, pointController.recalcSoftMinusPointStats);
router.get('/register_point_types', authController.verifyAdminToken, pointController.fetchRegisterPointTypes);
router.post('/register_point_type_add', authController.verifyAdminToken, validateAddRegisterPointType, pointController.addRegisterPointType);
router.post('/register_point_type_edit', authController.verifyAdminToken, validateEditRegisterPointType, pointController.editRegisterPointType);
router.get('/register_point_balance', authController.verifyAdminToken, validateRegisterPointBalance, pointController.fetchRegisterPointBalance);
router.get('/register_point_log', authController.verifyAdminToken, pointController.fetchRegisterPointLog);
router.post('/register_point_log_add', authController.verifyAdminToken, validateAddRegisterPointLog, pointController.addRegisterPointLog);
router.post('/edit_user_point', authController.verifyAdminToken, validateEditUserPoint, pointController.editUserPoint);
router.post('/prize_log_minus', authController.verifyAdminToken, validateMinusPrizeLog, pointController.minusPrizeLog);
// router.get('/temp_manual_appstore_point', pointController.tempManualAppstorePoint);
// router.get('/temp_manual_karaoke_point', pointController.tempManualKaraokePoint);
// router.get('/temp_manual_bmedia_point', pointController.tempManualBMediaPoint);
// router.get('/temp_recalc_bmedia_point', pointController.tempRecalcBMediaPoint);
// router.get('/temp_repair_activity_point', pointController.tempRepairActivityPoint);
// router.get('/temp_premium_activity_point', pointController.tempPremiumActivityPoint);
// router.get('/temp_premium_discuss_point', pointController.tempWomensDayActivityPoint);
// router.get('/temp_premium_puzzle_point', pointController.tempPuzzleAwardActivityPoint);
// router.get('/temp_period_duty_for_survey', pointController.tempPeriodDutyForSurvey);
router.get('/eshop_wallet_balance', authController.verifyAdminToken, validateEshopWalletBalance, pointController.fetchEshopWalletBalance);
router.get('/eshop_wallet_transactions', authController.verifyAdminToken, validateEshopWalletTransactions, pointController.fetchEshopeWalletTransactions);
router.get('/eshop_cards', authController.verifyAdminToken, pointController.fetchEshopCards);
router.post('/eshop_card_sync', authController.verifyAdminToken, pointController.syncEshopCards);
router.post('/eshop_combine_sync', authController.verifyAdminToken, pointController.syncEshopCombineLog);
router.get('/eshop_point_stats', authController.verifyAdminToken, pointController.fetchEshopPointStats);

router.get('/reserve_prefixes', authController.verifyAdminToken, reserveController.fetchReservePrefixes);
router.get('/reserve_simple_prefixes', authController.verifyAdminToken, reserveController.fetchReserveSimplePrefixes);
router.post('/reserve_prefix_add', authController.verifyAdminToken, validateAddReservePrefix, reserveController.addReservePrefix);
router.post('/reserve_prefix_edit', authController.verifyAdminToken, validateEditReservePrefix, reserveController.editReservePrefix);
router.post('/reserve_prefix_delete', authController.verifyAdminToken, validateDeleteReservePrefix, reserveController.deleteReservePrefix);
router.post('/reserve_prefix_minus', authController.verifyAdminToken, validateMinusReservePrefix, reserveController.minusReservePrefix);
router.post('/reserve_prefix_sms', authController.verifyAdminToken, validateSmsReservePrefix, reserveController.smsReservePrefix);
router.get('/reserve_users', authController.verifyAdminToken, reserveController.fetchReserveUsers);
router.post('/reserve_users_add', authController.verifyAdminToken, validateAddReserveUsers, reserveController.addReserveUsers);
router.post('/reserve_user_edit', authController.verifyAdminToken, validateEditReserveUser, reserveController.editReserveUser);
router.post('/reserve_user_delete', authController.verifyAdminToken, validateDeleteReserveUser, reserveController.deleteReserveUser);
router.get('/reserve_logs', authController.verifyAdminToken, reserveController.fetchReserveLogs);
router.post('/reserve_log_add', authController.verifyAdminToken, validateAddReserveLog, reserveController.addReserveLog);
router.post('/reserve_log_edit', authController.verifyAdminToken, validateEditReserveLog, reserveController.editReserveLog);
router.post('/reserve_log_delete', authController.verifyAdminToken, validateDeleteReserveLog, reserveController.deleteReserveLog);
router.get('/reserve_sms_logs', authController.verifyAdminToken, reserveController.fetchReserveSmsLogs);
router.get('/reserve_sms_filters', authController.verifyAdminToken, reserveController.fetchReserveSmsFilters);
router.get('/old_mobile_products', authController.verifyAdminToken, reserveController.fetchOldMobileProducts);
router.get('/old_reserve_prefixes', authController.verifyAdminToken, reserveController.fetchOldReservePrefixes);
router.get('/old_reserve_simple_prefixes', authController.verifyAdminToken, reserveController.fetchOldReserveSimplePrefixes);
router.post('/old_reserve_prefix_add', authController.verifyAdminToken, validateAddOldReservePrefix, reserveController.addOldReservePrefix);
router.post('/old_reserve_prefix_edit', authController.verifyAdminToken, validateEditOldReservePrefix, reserveController.editOldReservePrefix);
router.get('/old_reservations', authController.verifyAdminToken, reserveController.fetchOldReserveUsers);
router.post('/old_reservations_add', authController.verifyAdminToken, validateAddOldReservations, reserveController.addOldReservations);
router.get('/old_reserve_logs', authController.verifyAdminToken, reserveController.fetchOldReserveLogs);
router.post('/old_reserve_log_add', authController.verifyAdminToken, validateAddOldReserveLog, reserveController.addOldReserveLog);
router.post('/old_reserve_log_edit', authController.verifyAdminToken, validateEditOldReserveLog, reserveController.editOldReserveLog);
router.post('/old_reserve_log_delete', authController.verifyAdminToken, validateDeleteOldReserveLog, reserveController.deleteOldReserveLog);
router.get('/phone_books', authController.verifyAdminToken, reserveController.fetchPhoneBooks);
router.post('/phone_book_sync', authController.verifyAdminToken, validateSyncPhoneBook, reserveController.syncPhoneBook);
router.post('/phone_books_sync', authController.verifyAdminToken, validateSyncPhoneBooks, reserveController.syncPhoneBooks);

router.get('/update_files', authController.verifyAdminToken, baseController.fetchUpdateFiles);
router.post('/update_file_delete', authController.verifyAdminToken, validateDeleteUpdateFile, baseController.deleteUpdateFile);
router.post('/update_file_add', authController.verifyAdminToken, upload("update").single("upload_file"), handleMulterErrors, validateAddUpdateFile, baseController.addUpdateFile);
router.post('/update_file_edit', authController.verifyAdminToken, upload("update").single("upload_file"), handleMulterErrors, validateEditUpdateFile, baseController.editUpdateFile);
router.post('/update_file_sync', authController.verifyAdminToken, validateSyncUpdateFile, baseController.syncUpdateFile);

router.get('/temp_files', authController.verifyAdminToken, baseController.fetchTempFiles);
router.post('/temp_file_add', authController.verifyAdminToken, upload("temp").single("upload_file"), handleMulterErrors, validateAddTempFile, baseController.addTempFile);
router.post('/temp_file_delete', authController.verifyAdminToken, validateDeleteTempFile, baseController.deleteTempFile);
router.get('/holidays', authController.verifyAdminToken, baseController.fetchHolidays);
router.post('/holiday_add', authController.verifyAdminToken, validateAddHoliday, baseController.addHoliday);
router.post('/holiday_edit', authController.verifyAdminToken, validateEditHoliday, baseController.editHoliday);
router.post('/holiday_delete', authController.verifyAdminToken, validateDeleteHoliday, baseController.deleteHoliday);
router.get('/company_contacts', authController.verifyAdminToken, baseController.fetchCompanyContacts);
router.post('/company_contact_add', authController.verifyAdminToken, validateAddCompanyContact, baseController.addCompanyContact);
router.post('/company_contact_edit', authController.verifyAdminToken, validateEditCompanyContact, baseController.editCompanyContact);
router.post('/company_contact_delete', authController.verifyAdminToken, validateDeleteCompanyContact, baseController.deleteCompanyContact);

router.get('/blogs', authController.verifyAdminToken, blogController.fetchBlogs);
router.get('/blogs/detail', authController.verifyAdminToken, blogController.findArticleByPk);
router.get('/blogs/next', authController.verifyAdminToken, blogController.fetchNextPkList);

router.get('/product_categories', authController.verifyAdminToken, productController.fetchProductCategories);
router.post('/product_category_add', authController.verifyAdminToken, validateAddProductCategory, productController.addProductCategory);
router.post('/product_category_edit', authController.verifyAdminToken, validateEditProductCategory, productController.editProductCategory);
router.post('/product_category_delete', authController.verifyAdminToken, validateDeleteProductCategory, productController.deleteProductCategory);
router.get('/products', authController.verifyAdminToken, productController.fetchProducts);
router.get('/product_phones', authController.verifyAdminToken, productController.fetchProductPhones);
router.post('/product_add', authController.verifyAdminToken, upload("products").single("image_file"), handleMulterErrors, validateAddProduct, productController.addProduct);
router.post('/product_edit', authController.verifyAdminToken, upload("products").single("image_file"), handleMulterErrors, validateEditProduct, productController.editProduct);
router.post('/product_delete', authController.verifyAdminToken, validateDeleteProduct, productController.deleteProduct);
router.post('/product_sync', authController.verifyAdminToken, validateSyncProduct, productController.syncProduct);
router.get('/product_images', authController.verifyAdminToken, productController.fetchProductImages);
router.post('/product_image_add', authController.verifyAdminToken, upload("products").single("image_file"), handleMulterErrors, validateAddProductImage, productController.addProductImage);
router.post('/product_image_edit', authController.verifyAdminToken, upload("products").single("image_file"), handleMulterErrors, validateEditProductImage, productController.editProductImage);
router.post('/product_image_delete', authController.verifyAdminToken, validateDeleteProductImage, productController.deleteProductImage);
router.post('/product_image_sync', authController.verifyAdminToken, validateSyncProductImage, productController.syncProductImage);
router.get('/product_spec_keys', authController.verifyAdminToken, productController.fetchProductSpecKeys);
router.post('/product_spec_key_add', authController.verifyAdminToken, validateAddProductSpecKey, productController.addProductSpecKey);
router.post('/product_spec_key_edit', authController.verifyAdminToken, validateEditProductSpecKey, productController.editProductSpecKey);
router.post('/product_spec_key_delete', authController.verifyAdminToken, validateDeleteProductSpecKey, productController.deleteProductSpecKey);
router.get('/product_spec_orders', authController.verifyAdminToken, productController.fetchProductSpecOrders);
router.post('/product_spec_order_add', authController.verifyAdminToken, validateAddProductSpecOrder, productController.addProductSpecOrder);
router.post('/product_spec_order_edit', authController.verifyAdminToken, validateEditProductSpecOrder, productController.editProductSpecOrder);
router.post('/product_spec_order_delete', authController.verifyAdminToken, validateDeleteProductSpecOrder, productController.deleteProductSpecOrder);
router.get('/product_spec_values', authController.verifyAdminToken, validateGetProductSpecValues, productController.fetchProductSpecKeyAndValues);
router.post('/product_spec_values_submit', authController.verifyAdminToken, validateSubmitProductSpecValues, productController.submitProductSpecValues);
router.get('/product_models', authController.verifyAdminToken, productController.fetchProductModels);
router.get('/product_reservable_models', authController.verifyAdminToken, productController.fetchProductReservableModels);
router.post('/product_model_add', authController.verifyAdminToken, validateAddProductModel, productController.addProductModel);
router.post('/product_model_edit', authController.verifyAdminToken, validateEditProductModel, productController.editProductModel);
router.post('/product_model_delete', authController.verifyAdminToken, validateDeleteProductModel, productController.deleteProductModel);
router.get('/register_phone_log', authController.verifyAdminToken, productController.fetchRegisterPhoneLog);
router.post('/register_phone_log_add', authController.verifyAdminToken, validateAddRegisterPhoneLog, productController.addRegisterPhoneLog);
router.get('/register_product_log', authController.verifyAdminToken, productController.fetchRegisterProductLog);
router.get('/eprod_regist_add_log', authController.verifyAdminToken, validateGetEprodRegistAddLog, productController.fetchEprodRegistAddLog);
router.get('/eprod_regist_minus_log', authController.verifyAdminToken, validateGetEprodRegistMinusLog, productController.fetchEprodRegistMinusLog);
router.post('/phone_imei_prefix_add', authController.verifyAdminToken, validateAddPhoneImeiPrefix, productController.addPhoneImeiPrefix);
router.post('/phone_imei_prefix_delete', authController.verifyAdminToken, validateDeletePhoneImeiPrefix, productController.deletePhoneImeiPrefix);
router.get('/phone_accessories', authController.verifyAdminToken, validateGetPhoneAccessories, productController.fetchPhoneAccessories);
router.post('/phone_accessory_add', authController.verifyAdminToken, validateAddPhoneAccessory, productController.addPhoneAccessory);
router.post('/phone_accessory_edit', authController.verifyAdminToken, validateEditPhoneAccessory, productController.editPhoneAccessory);
router.post('/phone_accessory_delete', authController.verifyAdminToken, validateDeletePhoneAccessory, productController.deletePhoneAccessory);
router.get('/phone_changelogs', authController.verifyAdminToken, productController.fetchPhoneChangelogs);
router.post('/phone_changelog_add', authController.verifyAdminToken, validateAddPhoneChangelog, productController.addPhoneChangelog);
router.post('/phone_changelog_edit', authController.verifyAdminToken, validateEditPhoneChangelog, productController.editPhoneChangelog);
router.post('/phone_changelog_delete', authController.verifyAdminToken, validateDeletePhoneChangelog, productController.deletePhoneChangelog);

router.get('/phone_agencies', authController.verifyAdminToken, agencyController.fetchPhoneAgencies);
router.post('/phone_agency_add', authController.verifyAdminToken, validateAddPhoneAgency, agencyController.addPhoneAgency);
router.post('/phone_agency_edit', authController.verifyAdminToken, validateEditPhoneAgency, agencyController.editPhoneAgency);
router.post('/phone_agency_delete', authController.verifyAdminToken, validateDeletePhoneAgency, agencyController.deletePhoneAgency);
router.get('/eprod_agencies', authController.verifyAdminToken, agencyController.fetchEprodAgencies);
router.post('/eprod_agency_add', authController.verifyAdminToken, validateAddEprodAgency, agencyController.addEprodAgency);
router.post('/eprod_agency_edit', authController.verifyAdminToken, validateEditEprodAgency, agencyController.editEprodAgency);
router.post('/eprod_agency_delete', authController.verifyAdminToken, validateDeleteEprodAgency, agencyController.deleteEprodAgency);
router.post('/phone_sale_agencies_sync', authController.verifyAdminToken, agencyController.syncPhoneSaleAgencies);
router.get('/phone_sale_agencies', authController.verifyAdminToken, agencyController.fetchPhoneSaleAgencies);
router.get('/phone_sale_simple_agencies', authController.verifyAdminToken, agencyController.fetchPhoneSaleSimpleAgencies);
router.post('/phone_sale_agency_edit', authController.verifyAdminToken, validateEditPhoneSaleAgency, agencyController.editPhoneSaleAgency);
router.post('/phone_sale_agency_delete', authController.verifyAdminToken, validateDeletePhoneSaleAgency, agencyController.deletePhoneSaleAgency);

router.post('/weather_stations_sync', authController.verifyAdminToken, weatherController.syncGeoInfo);
router.get('/weather_stations', authController.verifyAdminToken, weatherController.fetchWeatherStations);
router.get('/weather_current', authController.verifyAdminToken, weatherController.fetchWeatherCurrent);
router.get('/weather_short', authController.verifyAdminToken, weatherController.fetchWeatherShort);

router.get('/premium_services', authController.verifyAdminToken, premiumController.fetchPremiumServices);
router.get('/premium_simple_services', authController.verifyAdminToken, premiumController.fetchPremiumSimpleServices);
router.post('/premium_service_add', authController.verifyAdminToken, upload("premiums").single("image_file"), handleMulterErrors, validateAddPremiumService, premiumController.addPremiumService);
router.post('/premium_service_edit', authController.verifyAdminToken, upload("premiums").single("image_file"), handleMulterErrors, validateEditPremiumService, premiumController.editPremiumService);
router.post('/premium_service_delete', authController.verifyAdminToken, validateDeletePremiumService, premiumController.deletePremiumService);
router.post('/premium_service_sync', authController.verifyAdminToken, validateSyncPremiumService, premiumController.syncPremiumService);
router.get('/premium_goods', authController.verifyAdminToken, premiumController.fetchPremiumGoods);
router.get('/premium_simple_goods', authController.verifyAdminToken, premiumController.fetchPremiumSimpleGoods);
router.post('/premium_good_add', authController.verifyAdminToken, validateAddPremiumGood, premiumController.addPremiumGood);
router.post('/premium_good_edit', authController.verifyAdminToken, validateEditPremiumGood, premiumController.editPremiumGood);
router.post('/premium_good_delete', authController.verifyAdminToken, validateDeletePremiumGood, premiumController.deletePremiumGood);
router.get('/premium_user_classes', authController.verifyAdminToken, premiumController.fetchPremiumUserClasses);
router.post('/premium_user_class_add', authController.verifyAdminToken, validateAddPremiumUserClass, premiumController.addPremiumUserClass);
router.post('/premium_user_class_edit', authController.verifyAdminToken, validateEditPremiumUserClass, premiumController.editPremiumUserClass);
router.post('/premium_user_class_delete', authController.verifyAdminToken, validateDeletePremiumUserClass, premiumController.deletePremiumUserClass);
router.get('/premium_simple_classes', authController.verifyAdminToken, validateGetPremiumSimpleClasses, premiumController.fetchPremiumSimpleClasses);
router.get('/premium_user_values', authController.verifyAdminToken, premiumController.fetchPremiumUserValues);
router.get('/user_delivery_addresses', authController.verifyAdminToken, premiumController.fetchUserDeliveryAddresses);
router.post('/user_delivery_address_add', authController.verifyAdminToken, validateAddUserDeliveryAddress, premiumController.addUserDeliveryAddress);
router.post('/user_delivery_address_edit', authController.verifyAdminToken, validateEditUserDeliveryAddress, premiumController.editUserDeliveryAddress);
router.post('/user_delivery_address_delete', authController.verifyAdminToken, validateDeleteUserDeliveryAddress, premiumController.deleteUserDeliveryAddress);
router.get('/lottery_numbers', authController.verifyAdminToken, premiumController.fetchLotteryNumbers);
router.post('/lottery_number_add', authController.verifyAdminToken, validateAddLotteryNumber, premiumController.addLotteryNumber);
router.post('/lottery_number_edit', authController.verifyAdminToken, validateEditLotteryNumber, premiumController.editLotteryNumber);
router.post('/lottery_number_delete', authController.verifyAdminToken, validateDeleteLotteryNumber, premiumController.deleteLotteryNumber);
router.post('/lottery_number_refresh', authController.verifyAdminToken, validateRefreshLotteryNumber, premiumController.refreshLotteryNumber);
router.get('/lottery_selected_numbers', authController.verifyAdminToken, validateGetSelectedLotteryNumbers, premiumController.fetchLotterySelectedNumbers);
router.get('/lottery_remain_numbers', authController.verifyAdminToken, validateGetRemainLotteryNumbers, premiumController.fetchLotteryRemainNumbers);
router.get('/lottery_candidates', authController.verifyAdminToken, premiumController.fetchLotteryCandidates);
router.post('/lottery_candidate_add', authController.verifyAdminToken, validateAddLotteryCandidate, premiumController.addLotteryCandidate);
router.post('/lottery_candidate_edit', authController.verifyAdminToken, validateEditLotteryCandidate, premiumController.editLotteryCandidate);
router.post('/lottery_candidate_delete', authController.verifyAdminToken, validateDeleteLotteryCandidate, premiumController.deleteLotteryCandidate);
router.get('/lottery_submits', authController.verifyAdminToken, premiumController.fetchLotterySubmits);
router.get('/lottery_selected_submits', authController.verifyAdminToken, validateGetSelectedLotterySubmits, premiumController.fetchLotterySelectedSubmits);
router.get('/lottery_remain_submits', authController.verifyAdminToken, validateGetRemainLotterySubmits, premiumController.fetchLotteryRemainSubmits);
router.post('/lottery_submit_random', authController.verifyAdminToken, validateRandomLotterySubmit, premiumController.randomLotterySubmit);
router.post('/lottery_submit_add', authController.verifyAdminToken, validateAddLotterySubmit, premiumController.addLotterySubmit);
router.post('/lottery_submit_edit', authController.verifyAdminToken, validateEditLotterySubmit, premiumController.editLotterySubmit);
router.post('/lottery_submit_delete', authController.verifyAdminToken, validateDeleteLotterySubmit, premiumController.deleteLotterySubmit);
router.post('/lottery_award_edit', authController.verifyAdminToken, validateEditLotterySubmitAward, premiumController.editLotterySubmitAward);
router.post('/lottery_award_finish', authController.verifyAdminToken, validateFinishLotterySubmitAward, premiumController.finishLotterySubmitAward);
router.get('/integrated_user_classes', authController.verifyAdminToken, premiumController.fetchIntegratedUserClasses);
router.post('/integrated_user_class_add', authController.verifyAdminToken, validateAddIntegratedUserClass, premiumController.addIntegratedUserClass);
router.post('/integrated_user_class_edit', authController.verifyAdminToken, validateEditIntegratedUserClass, premiumController.editIntegratedUserClass);
router.post('/integrated_user_class_delete', authController.verifyAdminToken, validateDeleteIntegratedUserClass, premiumController.deleteIntegratedUserClass);
router.get('/integrated_simple_classes', authController.verifyAdminToken, premiumController.fetchIntegratedSimpleClasses);
router.get('/integrated_user_values', authController.verifyAdminToken, premiumController.fetchIntegratedUserValues);
router.post('/integrated_user_refresh', authController.verifyAdminToken, validateRefreshIntegratedUserValue, premiumController.refreshIntegratedUserValue);
router.post('/integrated_user_values_recalc', authController.verifyAdminToken, premiumController.recalcIntegratedUserValues);
router.post('/integrated_user_classes_recalc', authController.verifyAdminToken, premiumController.recalcIntegratedUserClasses);
router.get('/premium_discuss_awards', authController.verifyAdminToken, premiumController.fetchPremiumDiscussAwards);
router.post('/premium_discuss_award_add', authController.verifyAdminToken, validateAddPremiumDiscussAward, premiumController.addPremiumDiscussAward);
router.post('/premium_discuss_award_edit', authController.verifyAdminToken, validateEditPremiumDiscussAward, premiumController.editPremiumDiscussAward);
router.post('/premium_discuss_award_delete', authController.verifyAdminToken, validateDeletePremiumDiscussAward, premiumController.deletePremiumDiscussAward);
router.post('/premium_reception_add', authController.verifyAdminToken, validateAddPremiumReception, premiumController.addPremiumReception);
router.post('/premium_reception_edit', authController.verifyAdminToken, validateEditPremiumReception, premiumController.editPremiumReception);
router.get('/puzzle_questions', authController.verifyAdminToken, validatePuzzQuestions, premiumController.fetchPuzzleQuestions);
router.post('/puzzle_question_add', authController.verifyAdminToken, validateAddPuzzQuestion, premiumController.addPuzzleQuestion);
router.post('/puzzle_question_edit', authController.verifyAdminToken, validateEditPuzzQuestion, premiumController.editPuzzleQuestion);
router.post('/puzzle_question_delete', authController.verifyAdminToken, validateDeletePuzzQuestion, premiumController.deletePuzzleQuestion);
router.get('/puzzle_choices', authController.verifyAdminToken, validatePuzzChoices, premiumController.fetchPuzzleChoices);
router.post('/puzzle_choice_add', authController.verifyAdminToken, validateAddPuzzChoice, premiumController.addPuzzleChoice);
router.post('/puzzle_choice_edit', authController.verifyAdminToken, validateEditPuzzChoice, premiumController.editPuzzleChoice);
router.post('/puzzle_choice_delete', authController.verifyAdminToken, validateDeletePuzzChoice, premiumController.deletePuzzleChoice);
router.get('/puzzle_awards', authController.verifyAdminToken, premiumController.fetchPuzzleAwards);
router.post('/puzzle_award_add', authController.verifyAdminToken, validateAddPuzzleAward, premiumController.addPuzzleAward);
router.post('/puzzle_award_edit', authController.verifyAdminToken, validateEditPuzzleAward, premiumController.editPuzzleAward);
router.post('/puzzle_award_delete', authController.verifyAdminToken, validateDeletePuzzleAward, premiumController.deletePuzzleAward);
router.post('/puzzle_award_finish', authController.verifyAdminToken, validateFinishPuzzleAward, premiumController.finishPuzzleAward);
router.get('/puzzle_rank', authController.verifyAdminToken, premiumController.fetchPuzzleRank);
router.post('/puzzle_bonus_add', authController.verifyAdminToken, validateAddPuzzleBonus, premiumController.addPuzzleBonus);
router.post('/puzzle_bonus_edit', authController.verifyAdminToken, validateEditPuzzleBonus, premiumController.editPuzzleBonus);
router.get('/puzzle_answer_detail', authController.verifyAdminToken, validatePuzzleAnswerDetail, premiumController.fetchPuzzleAnswerDetail);
router.get('/puzzle_answer_stats', authController.verifyAdminToken, validatePuzzleAnswerStats, premiumController.fetchPuzzleAnswerStats);

router.get('/news_categories', authController.verifyAdminToken, newsController.fetchNewsCategories);
router.post('/news_category_add', authController.verifyAdminToken, validateAddNewsCategory, newsController.addNewsCategory);
router.post('/news_category_edit', authController.verifyAdminToken, validateEditNewsCategory, newsController.editNewsCategory);
router.post('/news_category_delete', authController.verifyAdminToken, validateDeleteNewsCategory, newsController.deleteNewsCategory);
router.get('/news_articles', authController.verifyAdminToken, newsController.fetchNewsArticles);
router.post('/news_article_add', authController.verifyAdminToken, validateAddNewsArticle, newsController.addNewsArticle);
router.post('/news_article_edit', authController.verifyAdminToken, validateEditNewsArticle, newsController.editNewsArticle);
router.post('/news_article_delete', authController.verifyAdminToken, validateDeleteNewsArticle, newsController.deleteNewsArticle);
router.get('/news_content', authController.verifyAdminToken, validateGetNewsContent, newsController.fetchNewsContent);

router.get('/classify_by_phone', authController.verifyAdminToken, classifyController.fetchClassesByPhone);
router.get('/classify_by_eprod', authController.verifyAdminToken, classifyController.fetchClassesByEprod);

router.get('/migrate_user_to_customer', crmController.migrateUserToCustomer);
router.get('/crm_customers', authController.verifyAdminToken, crmController.fetchCrmCustomers);
router.get('/crm_prod_categories', authController.verifyAdminToken, crmController.fetchProductCategories);
router.get('/crm_prod_root_categories', authController.verifyAdminToken, crmController.fetchProductRootCategories);
router.get('/crm_prod_leaf_categories', authController.verifyAdminToken, crmController.fetchProductLeafCategories);
router.get('/crm_products', authController.verifyAdminToken, crmController.fetchCrmProducts);
router.post('/crm_product_add', authController.verifyAdminToken, validateAddCrmProduct, crmController.addCrmProduct);
router.post('/crm_product_edit', authController.verifyAdminToken, validateEditCrmProduct, crmController.editCrmProduct);
router.post('/crm_product_delete', authController.verifyAdminToken, validateDeleteCrmProduct, crmController.deleteCrmProduct);
router.get('/crm_prod_spec_keys', authController.verifyAdminToken, crmController.fetchCrmProdSpecKeys);
router.get('/crm_prod_spec_key_choices', authController.verifyAdminToken, crmController.fetchCrmProdSpecKeyChoices);
router.post('/crm_prod_spec_key_add', authController.verifyAdminToken, validateAddCrmProdSpecKey, crmController.addCrmProdSpecKey);
router.post('/crm_prod_spec_key_edit', authController.verifyAdminToken, validateEditCrmProdSpecKey, crmController.editCrmProdSpecKey);
router.post('/crm_prod_spec_key_delete', authController.verifyAdminToken, validateDeleteCrmProdSpecKey, crmController.deleteCrmProdSpecKey);
router.get('/crm_prod_spec_values', authController.verifyAdminToken, crmController.fetchCrmProdSpecValues);
router.post('/crm_prod_spec_value_add', authController.verifyAdminToken, validateAddCrmProdSpecValue, crmController.addCrmProdSpecValue);
router.post('/crm_prod_spec_value_edit', authController.verifyAdminToken, validateEditCrmProdSpecValue, crmController.editCrmProdSpecValue);
router.post('/crm_prod_spec_value_delete', authController.verifyAdminToken, validateDeleteCrmProdSpecValue, crmController.deleteCrmProdSpecValue);
router.get('/crm_prod_spec_orders', authController.verifyAdminToken, crmController.fetchCrmProdSpecOrders);
router.post('/crm_prod_spec_order_add', authController.verifyAdminToken, validateAddCrmProdSpecOrder, crmController.addCrmProdSpecOrder);
router.post('/crm_prod_spec_order_edit', authController.verifyAdminToken, validateEditCrmProdSpecOrder, crmController.editCrmProdSpecOrder);
router.post('/crm_prod_spec_order_delete', authController.verifyAdminToken, validateDeleteCrmProdSpecOrder, crmController.deleteCrmProdSpecOrder);
router.get('/crm_prod_survey_options', authController.verifyAdminToken, crmController.fetchCrmProdSurveyOptions);
router.post('/crm_prod_survey_option_add', authController.verifyAdminToken, validateAddCrmProdSurveyOption, crmController.addCrmProdSurveyOption);
router.post('/crm_prod_survey_option_edit', authController.verifyAdminToken, validateEditCrmProdSurveyOption, crmController.editCrmProdSurveyOption);
router.post('/crm_prod_survey_option_delete', authController.verifyAdminToken, validateDeleteCrmProdSurveyOption, crmController.deleteCrmProdSurveyOption);
router.get('/crm_eprod_sales', authController.verifyAdminToken, crmController.fetchCrmEprodSales);
router.post('/crm_eprod_sales_import', authController.verifyAdminToken, validateImportCrmEprodSales, crmController.importCrmEprodSales);
router.get('/crm_eprod_as_sync', crmController.syncCrmEprodAfterService);
router.get('/crm_eprod_as', authController.verifyAdminToken, crmController.fetchCrmEprodAs);
router.get('/crm_mars_cards', authController.verifyAdminToken, crmController.fetchCrmMarsCards);
router.get('/crm_mars_sync', authController.verifyAdminToken, crmController.syncCrmMarsCards);
router.get('/crm_eshop_info', authController.verifyAdminToken, crmController.fetchCrmEshopInfo);
router.get('/crm_eshop_sync', authController.verifyAdminToken, crmController.syncCrmEshopInfo);

module.exports = router;
