// routes/authRoutes.js
const express = require('express');
const router = express.Router();
const { upload } = require('../middleware/upload');
const downloadController = require('../controllers/downloadController');
const homeController = require('../controllers/client/clientHomeController');
const clientMessageController = require('../controllers/client/clientMessageController');
const blogController = require('../controllers/client/clientBlogController');
const commonPrhnController = require('../controllers/common/commonPrhnController');
const commonMessageController = require('../controllers/common/commonMessageController');
const commonWeatherController = require('../controllers/common/commonWeatherController');
const commonNewsController = require('../controllers/common/commonNewsController');
const agencyController = require('../controllers/client/clientAgencyController');
const { validateActivityPointAction, validateCommonLogin, validateMergeFixedId, validateActivityPointLog, validateActivityPointStats, validateActivityPointRank, validateSoftPointLog, validateSoftPointStats, validateSoftPointRank, validateAppstorePointLog, validatePlusAppstorePoint, validateRefundAppstorePoint, validateKaraokePointLog, validatePlusKaraokePoint, validateRefundKaraokePoint, validateBMediaPointLog, validatePlusBMediaPoint, validateRefundBMediaPoint } = require('../middleware/commonPrhnValidators');
const { validateBlogReplies } = require('../middleware/clientBlogValidators');
const { validateAddFeedbackMessage } = require('../middleware/commonMessageValidators');
const { validateAcceptNews, validateCancelNews, validateDenyNews } = require('../middleware/commonNewsValidators');

router.get('/download_file', downloadController.downloadFile);
router.post('/upload_file', upload("temp").fields([{ name: "image_file", maxCount: 1 }, { name: "content_file", maxCount: 1 }]), downloadController.uploadFile);
router.get('/home_common_info', homeController.fetchHomeCommonInfo);
router.get('/notifications', clientMessageController.fetchNotifications);
router.get('/faqs', clientMessageController.fetchFaqs);
router.get('/blog_articles', blogController.fetchOldArticles);
router.get('/blog_replies', validateBlogReplies, blogController.fetchOldReplies);
router.post('/activity_point_action', validateActivityPointAction, commonPrhnController.activityPointAction);
router.post('/common_login', validateCommonLogin, commonPrhnController.commonLogin);
router.post('/merge_fixed_id', validateMergeFixedId, commonPrhnController.mergeFixedId);
router.get('/activity_point_log', validateActivityPointLog, commonPrhnController.fetchActivityPointLog);
router.get('/activity_point_stats', validateActivityPointStats, commonPrhnController.fetchActivityPointStats);
router.get('/activity_point_rank', validateActivityPointRank, commonPrhnController.fetchActivityPointRank);
router.get('/soft_point_log', validateSoftPointLog, commonPrhnController.fetchSoftMinusPointLog);
router.get('/soft_point_stats', validateSoftPointStats, commonPrhnController.fetchSoftPointStats);
router.get('/soft_point_rank', validateSoftPointRank, commonPrhnController.fetchSoftPointRank);
router.get('/appstore_point_log', validateAppstorePointLog, commonPrhnController.fetchAppstorePointLog);
router.post('/appstore_point_plus', validatePlusAppstorePoint, commonPrhnController.plusAppstorePointLog);
router.post('/appstore_point_refund', validateRefundAppstorePoint, commonPrhnController.refundAppstorePointLog);
router.get('/karaoke_point_log', validateKaraokePointLog, commonPrhnController.fetchKaraokePointLog);
router.post('/karaoke_point_plus', validatePlusKaraokePoint, commonPrhnController.plusKaraokePointLog);
router.post('/karaoke_point_refund', validateRefundKaraokePoint, commonPrhnController.refundKaraokePointLog);
router.get('/bmedia_point_log', validateBMediaPointLog, commonPrhnController.fetchBMediaPointLog);
router.post('/bmedia_point_plus', validatePlusBMediaPoint, commonPrhnController.plusBMediaPointLog);
router.post('/bmedia_point_refund', validateRefundBMediaPoint, commonPrhnController.refundBMediaPointLog);
router.get('/feedback_threads', commonMessageController.fetchFeedbackThreads);
router.get('/feedback_messages', commonMessageController.fetchFeedbackMessages);
router.post('/feedback_message_fixed_add', validateAddFeedbackMessage, commonMessageController.addFeedbackMessageFixed);
router.get('/phone_agencies', agencyController.fetchPhoneAgencies);
router.get('/eprod_agencies', agencyController.fetchEprodAgencies);
router.get('/weather_info', commonWeatherController.fetchWeatherInfo);
router.get('/polestar_news', commonNewsController.fetchPolestarNews);
router.get('/base64', commonPrhnController.getBase64Decode);

module.exports = router;
