const express = require('express');
const router = express.Router();
const authController = require('../../controllers/authController');
const premiumController = require('../../controllers/client/clientPremiumController');
const { validateGetPremiumGoods, validateGetPremiumLotteryInfo, validateGetPremiumUserAward, validateSubmitLotteryNumber, validateGetLotteryAwards, validateGetPremiumServiceAwards, validateGetPremiumDiscussAwards, validateRefreshLotteryNumber, validateRandomLotterySubmit, validateGetRemainLotteryNumbers, validateGetSelectedLotteryNumbers, validateAddUserDeliveryAddress, validateEditUserDeliveryAddress, validateAddPremiumReception, validateEditPremiumReception, validateGetRemainLotterySubmits, validateGetSelectedLotterySubmits, validateSendLotterySubmit, validateGetLotterySubmitAwards, validatePuzzleResponse, validateGetPuzzleAwards } = require('../../middleware/clientPremiumValidators');

router.get('/premium_services', authController.verifyUserToken, premiumController.fetchPremiumServices);
router.get('/premium_goods', authController.verifyUserToken, validateGetPremiumGoods, premiumController.fetchPremiumGoods);
router.get('/premium_lottery_info', authController.verifyUserToken, premiumController.fetchPremiumLotteryInfo);
router.get('/premium_lottery_info_25', authController.verifyUserToken, validateGetPremiumLotteryInfo, premiumController.fetchPremiumLotteryInfo25);
router.get('/premium_user_award', authController.verifyUserToken, validateGetPremiumUserAward, premiumController.fetchPremiumUserAward);
router.post('/lottery_number_refresh', authController.verifyUserToken, validateRefreshLotteryNumber, premiumController.refreshLotteryNumber);
router.post('/lottery_number_submit', authController.verifyUserToken, validateSubmitLotteryNumber, premiumController.submitLotteryNumber);
router.get('/lottery_awards', authController.verifyUserToken, validateGetLotteryAwards, premiumController.fetchLotteryAwards);
router.get('/lottery_selected_numbers', authController.verifyUserToken, validateGetSelectedLotteryNumbers, premiumController.fetchLotterySelectedNumbers);
router.get('/lottery_remain_numbers', authController.verifyUserToken, validateGetRemainLotteryNumbers, premiumController.fetchLotteryRemainNumbers);
router.post('/user_delivery_address_add', authController.verifyUserToken, validateAddUserDeliveryAddress, premiumController.addUserDeliveryAddress);
router.post('/user_delivery_address_edit', authController.verifyUserToken, validateEditUserDeliveryAddress, premiumController.editUserDeliveryAddress);
router.get('/premium_service_awards', authController.verifyUserToken, validateGetPremiumServiceAwards, premiumController.fetchPremiumServiceAwards);
router.get('/premium_discuss_award', authController.verifyUserToken, validateGetPremiumDiscussAwards, premiumController.fetchPremiumDiscussAward);
router.post('/premium_reception_add', authController.verifyUserToken, validateAddPremiumReception, premiumController.addPremiumReception);
router.post('/premium_reception_edit', authController.verifyUserToken, validateEditPremiumReception, premiumController.editPremiumReception);
router.post('/lottery_submit_random', authController.verifyUserToken, validateRandomLotterySubmit, premiumController.randomLotterySubmit);
router.get('/lottery_selected_submits', authController.verifyUserToken, validateGetSelectedLotterySubmits, premiumController.fetchLotterySelectedSubmits);
router.get('/lottery_remain_submits', authController.verifyUserToken, validateGetRemainLotterySubmits, premiumController.fetchLotteryRemainSubmits);
router.post('/lottery_submit_add', authController.verifyUserToken, validateSendLotterySubmit, premiumController.addLotterySubmit);
router.get('/lottery_submit_awards', authController.verifyUserToken, validateGetLotterySubmitAwards, premiumController.fetchLotterySubmitAwards);
router.get('/lottery_submit_award', authController.verifyUserToken, validateGetLotterySubmitAwards, premiumController.fetchLotterySubmitAward);
router.get('/premium_puzzle_info', authController.verifyUserToken, premiumController.fetchPremiumPuzzleInfo);
router.post('/puzzle_response_submit', authController.verifyUserToken, validatePuzzleResponse, premiumController.submitPuzzleResponse);
router.get('/puzzle_awards', authController.verifyUserToken, validateGetPuzzleAwards, premiumController.fetchPuzzleAwards);
router.get('/puzzle_award', authController.verifyUserToken, validateGetPuzzleAwards, premiumController.fetchPuzzleAward);
router.get('/puzzle_rank', authController.verifyUserToken, premiumController.fetchPuzzleRank);

module.exports = router;
