-- temp files
CREATE SEQUENCE "TEMP_FILES_S" MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE temp_files (
  table_pk NUMBER PRIMARY KEY,
  title VARCHAR2(255),
  file_url VARCHAR2(255),
  created_at DATE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "TEMP_FILES"."TITLE" IS 'purpose of file upload, e.g. for eshop, or for mine';
COMMENT ON COLUMN "TEMP_FILES"."FILE_URL" IS 'uploaded file url';

CREATE OR REPLACE TRIGGER temp_file_pk_trigger
BEFORE INSERT ON temp_files
FOR EACH ROW
BEGIN
  IF :NEW.table_pk IS NULL THEN
    SELECT "TEMP_FILES_S".NEXTVAL
    INTO :NEW.table_pk
    FROM dual;
  END IF;
END;
/

-- holidays
CREATE SEQUENCE "HOLIDAYS_S" MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE holidays (
  table_pk NUMBER PRIMARY KEY,
  simple_date VARCHAR2(5) NOT NULL,
  name VARCHAR2(128),
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "HOLIDAYS"."SIMPLE_DATE" IS 'simple date of holiday, XX-XX format';
COMMENT ON COLUMN "HOLIDAYS"."NAME" IS 'name of holiday';

CREATE OR REPLACE TRIGGER holidays_pk_trigger
BEFORE INSERT ON holidays
FOR EACH ROW
BEGIN
  IF :NEW.table_pk IS NULL THEN
    SELECT "HOLIDAYS_S".NEXTVAL
    INTO :NEW.table_pk
    FROM dual;
  END IF;
END;
/

-- company contacts
CREATE SEQUENCE "COMPANY_CONTACTS_S" MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE company_contacts (
  contact_pk NUMBER PRIMARY KEY,
  contact_name VARCHAR2(128) NOT NULL,
  phone_number VARCHAR2(64) NOT NULL,
  position NUMBER(2) DEFAULT 0,
  is_deleted NUMBER(1) DEFAULT 0,
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "COMPANY_CONTACTS"."CONTACT_NAME" IS 'contact name';
COMMENT ON COLUMN "COMPANY_CONTACTS"."PHONE_NUMBER" IS 'phone number';

CREATE OR REPLACE TRIGGER company_contact_pk_trigger
BEFORE INSERT ON company_contacts
FOR EACH ROW
BEGIN
  IF :NEW.contact_pk IS NULL THEN
    SELECT "COMPANY_CONTACTS_S".NEXTVAL
    INTO :NEW.contact_pk
    FROM dual;
  END IF;
END;
/
