-- user class phone
CREATE TABLE uclass_phone_values (
  user_pk NUMBER PRIMARY KEY,
  phone_9 NUMBER(3) DEFAULT 0,
  phone_7 NUMBER(3) DEFAULT 0,
  phone_5 NUMBER(3) DEFAULT 0,
  phone_3 NUMBER(3) DEFAULT 0,
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "UCLASS_PHONE_VALUES"."USER_PK" IS 'users.user_pk';
COMMENT ON COLUMN "UCLASS_PHONE_VALUES"."PHONE_9" IS '9-category phone register count';
COMMENT ON COLUMN "UCLASS_PHONE_VALUES"."PHONE_7" IS '7-category phone register count';
COMMENT ON COLUMN "UCLASS_PHONE_VALUES"."PHONE_5" IS '5-category phone register count';
COMMENT ON COLUMN "UCLASS_PHONE_VALUES"."PHONE_3" IS '3-category phone register count';

-- user class eprod
CREATE TABLE uclass_eprod_values (
  user_id VARCHAR2(50) PRIMARY KEY,
  tv_3 NUMBER(3) DEFAULT 0,
  tv_2 NUMBER(3) DEFAULT 0,
  tv_1 NUMBER(3) DEFAULT 0,
  stb NUMBER(3) DEFAULT 0,
  notecom NUMBER(3) DEFAULT 0,
  pc NUMBER(3) DEFAULT 0,
  camera NUMBER(3) DEFAULT 0,
  phone NUMBER(3) DEFAULT 0,
  other NUMBER(3) DEFAULT 0,
  created_at DATE DEFAULT CURRENT_TIMESTAMP,
  updated_at DATE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."USER_ID" IS 'users.user_id';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."TV_3" IS 'TV (75-100in, smart tv)';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."TV_2" IS 'TV (50-65in)';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."TV_1" IS 'TV (19-43in)';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."STB" IS 'STB';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."NOTECOM" IS 'notecom (notecom, split, pad)';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."PC" IS 'PC (all-in-one, PC, mini-pc)';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."CAMERA" IS 'CAMERA, RECORDER';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."PHONE" IS 'wireless line phone';
COMMENT ON COLUMN "UCLASS_EPROD_VALUES"."OTHER" IS 'other (projector, display, QR-scanner, ion-gen, etc)';
