-- Converted from Oracle: 01_table_managers.sql
-- Generated by tools/oracle2pg.py - review before running.

-- managers = admins
CREATE SEQUENCE IF NOT EXISTS managers_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE managers (
  manager_pk BIGINT PRIMARY KEY,
  manager_id VARCHAR(50) UNIQUE NOT NULL,
  manager_name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role_pk BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN managers.manager_id IS 'manager id';
COMMENT ON COLUMN managers.manager_name IS 'manager name';
COMMENT ON COLUMN managers.role_pk IS 'manager_roles.role_pk';

ALTER TABLE managers ALTER COLUMN manager_pk SET DEFAULT nextval('managers_s');
ALTER SEQUENCE managers_s OWNED BY managers.manager_pk;

-- NOTE: You SHOULD set role_pk as foreign key after creating manager_roles table

-- manager_roles table
CREATE SEQUENCE IF NOT EXISTS manager_roles_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE manager_roles (
  role_pk BIGINT PRIMARY KEY,
  role_name VARCHAR(128) UNIQUE NOT NULL,
  default_page VARCHAR(255),
  department VARCHAR(10) DEFAULT '00000' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_manager_role_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_manager_role_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN manager_roles.role_name IS 'role name';
COMMENT ON COLUMN manager_roles.default_page IS 'default page after login as this manager';
COMMENT ON COLUMN manager_roles.department IS 'permission for departments';

ALTER TABLE manager_roles ALTER COLUMN role_pk SET DEFAULT nextval('manager_roles_s');
ALTER SEQUENCE manager_roles_s OWNED BY manager_roles.role_pk;

-- NOW set foreign key of role_pk for managers table
-- ALTER TABLE managers ADD CONSTRAINT fk_manager_role_pk FOREIGN KEY (role_pk) REFERENCES manager_roles(role_pk);

-- manager pages table (these pages representing specific role have permission to certain page)
CREATE SEQUENCE IF NOT EXISTS manager_pages_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE manager_pages (
  page_pk BIGINT PRIMARY KEY,
  page_url VARCHAR(255) NOT NULL,
  page_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_manager_page_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_manager_page_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

ALTER TABLE manager_pages ALTER COLUMN page_pk SET DEFAULT nextval('manager_pages_s');
ALTER SEQUENCE manager_pages_s OWNED BY manager_pages.page_pk;

-- permissions between manager role and pages
CREATE SEQUENCE IF NOT EXISTS manager_permissions_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE manager_permissions (
  table_pk BIGINT PRIMARY KEY,
  role_pk BIGINT NOT NULL,
  page_pk BIGINT NOT NULL,
  permission SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_manager_perm_role_pk FOREIGN KEY (role_pk) REFERENCES manager_roles(role_pk),
  CONSTRAINT fk_manager_perm_page_pk FOREIGN KEY (page_pk) REFERENCES manager_pages(page_pk),
  CONSTRAINT fk_manager_perm_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_manager_perm_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT ck_manager_perm_permission CHECK (permission IN (0, 1, 2, 3)),
  CONSTRAINT uq_role_page UNIQUE (role_pk, page_pk)
);

COMMENT ON COLUMN manager_permissions.permission IS '0: none, 1: read, 2: write, 3: super';

ALTER TABLE manager_permissions ALTER COLUMN table_pk SET DEFAULT nextval('manager_permissions_s');
ALTER SEQUENCE manager_permissions_s OWNED BY manager_permissions.table_pk;

INSERT INTO manager_permissions (role_pk, page_pk, permission)
VALUES (1, 1, 2);
INSERT INTO manager_permissions (role_pk, page_pk, permission)
VALUES (1, 2, 2);
INSERT INTO manager_permissions (role_pk, page_pk, permission)
VALUES (1, 3, 2);

-- user_admins
CREATE SEQUENCE IF NOT EXISTS user_admins_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_admins (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  manager_pk BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_admin_manager_pk FOREIGN KEY (manager_pk) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN user_admins.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_admins.manager_pk IS 'managers.manager_pk';

ALTER TABLE user_admins ALTER COLUMN table_pk SET DEFAULT nextval('user_admins_s');
ALTER SEQUENCE user_admins_s OWNED BY user_admins.table_pk;

