-- Converted from Oracle: 02_table_users.sql
-- Generated by tools/oracle2pg.py - review before running.

-- Address (locations)
CREATE TABLE locations (
  location_pk BIGINT PRIMARY KEY,
  location_name VARCHAR(100) NOT NULL,
  location_code VARCHAR(8) NOT NULL,
  parent_code VARCHAR(8),
  position SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN locations.location_name IS 'Location Name';
COMMENT ON COLUMN locations.parent_code IS 'Parent(locations.location_code), If 0 or NULL, its province';
COMMENT ON COLUMN locations.location_code IS 'location code reverse direction of location_pk';

-- User
CREATE SEQUENCE IF NOT EXISTS users_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE users (
  user_pk BIGINT PRIMARY KEY,
  user_id VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  user_name VARCHAR(50) NOT NULL,
  user_alias VARCHAR(50),
  user_avatar VARCHAR(255),
  gender CHAR(1),
  birthday TIMESTAMP,
  job SMALLINT,
  location_pk BIGINT,
  id_card VARCHAR(50),
  cid VARCHAR(12) UNIQUE,
  status SMALLINT DEFAULT 1,
  locked SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_location_fk FOREIGN KEY (location_pk) REFERENCES locations(location_pk),
  CONSTRAINT ck_user_gender CHECK (gender IN ('M', 'F'))
);

COMMENT ON COLUMN users.gender IS 'Gender (M, F)';
COMMENT ON COLUMN users.location_pk IS 'Address Location';
COMMENT ON COLUMN users.id_card IS 'Citizen No';
COMMENT ON COLUMN users.cid IS 'CID';
COMMENT ON COLUMN users.status IS 'user status (0: inactive, 1: active)';
COMMENT ON COLUMN users.locked IS 'allow only registered cid for login';

ALTER TABLE users ALTER COLUMN user_pk SET DEFAULT nextval('users_s');
ALTER SEQUENCE users_s OWNED BY users.user_pk;

CREATE INDEX idx_users_cid ON users (cid);

-- User Phones (User can directly input his phone BIGINT or we can reference phone BIGINT sent with feedbacks)
CREATE SEQUENCE IF NOT EXISTS user_phone_numbers_s INCREMENT BY 1 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE user_phone_numbers (
  phone_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  phone_type SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_phone_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT uq_user_phone_type UNIQUE (user_pk, phone_type, phone_number)
);

COMMENT ON COLUMN user_phone_numbers.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_phone_numbers.phone_number IS 'phone BIGINT';
COMMENT ON COLUMN user_phone_numbers.phone_type IS '0: User input, 1: By report, 2: by feedback, 3: by manager, 4: eprod register';

ALTER TABLE user_phone_numbers ALTER COLUMN phone_pk SET DEFAULT nextval('user_phone_numbers_s');
ALTER SEQUENCE user_phone_numbers_s OWNED BY user_phone_numbers.phone_pk;

-- user verify codes and status
CREATE SEQUENCE IF NOT EXISTS user_verify_codes_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_verify_codes (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  cid VARCHAR(12),
  status SMALLINT DEFAULT 0,
  verify_code INTEGER NOT NULL,
  expire_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_verify_code_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_verify_codes.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_verify_codes.cid IS 'CID or mirae SIM';
COMMENT ON COLUMN user_verify_codes.status IS 'verify status (0: none, 1: verified)';
COMMENT ON COLUMN user_verify_codes.verify_code IS 'verify code (100000 ~ 999999)';
COMMENT ON COLUMN user_verify_codes.expire_at IS 'expire_at (duration 5 mins)';

ALTER TABLE user_verify_codes ALTER COLUMN table_pk SET DEFAULT nextval('user_verify_codes_s');
ALTER SEQUENCE user_verify_codes_s OWNED BY user_verify_codes.table_pk;

-- user merge ids
CREATE TABLE user_merge_ids (
  pvendor_pk BIGINT PRIMARY KEY,
  pvendor_id VARCHAR(50) UNIQUE NOT NULL,
  fixed_pk BIGINT,
  fixed_id VARCHAR(50),
  fixed_status SMALLINT DEFAULT 0,
  appstore_pk VARCHAR(36),
  appstore_id VARCHAR(50),
  eshop_pk BIGINT,
  eshop_id VARCHAR(50),
  mass_pk VARCHAR(36),
  mass_id VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_id_user_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk)
);

-- merge log
CREATE SEQUENCE IF NOT EXISTS user_merge_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_merge_log (
  table_pk BIGINT PRIMARY KEY,
  pvendor_pk BIGINT NOT NULL,
  pvendor_id VARCHAR(50) NOT NULL,
  id_type SMALLINT NOT NULL,
  merge_id VARCHAR(50),
  merge_type SMALLINT DEFAULT 0 NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  CONSTRAINT fk_merge_log_prhn_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk)
);

ALTER TABLE user_merge_log ALTER COLUMN table_pk SET DEFAULT nextval('user_merge_log_s');
ALTER SEQUENCE user_merge_log_s OWNED BY user_merge_log.table_pk;

-- special data (for 923)
CREATE TABLE special_923 (
  table_pk BIGINT PRIMARY KEY,
  user_name VARCHAR(50) NOT NULL,
  gender CHAR(1),
  birth_year SMALLINT
);

-- user edit log
CREATE SEQUENCE IF NOT EXISTS user_edit_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_edit_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  property_type SMALLINT NOT NULL,
  old_value VARCHAR(50),
  new_value VARCHAR(50),
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  CONSTRAINT fk_user_edit_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_edit_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_edit_log.property_type IS '0: user_name, 1: birthday, 2: id_card, 3: cid, 4: job, 5: location, 6: gender';
COMMENT ON COLUMN user_edit_log.old_value IS 'property type old value';
COMMENT ON COLUMN user_edit_log.new_value IS 'property type new value';
COMMENT ON COLUMN user_edit_log.action_type IS '0: by user, 1: by manager';
COMMENT ON COLUMN user_edit_log.action_by IS 'users.user_pk or managers.manager_pk';

ALTER TABLE user_edit_log ALTER COLUMN table_pk SET DEFAULT nextval('user_edit_log_s');
ALTER SEQUENCE user_edit_log_s OWNED BY user_edit_log.table_pk;

-- user change password log (its neccessary because pvendor_id and prhn_pwd is also used for eshop, appstore, os_4)
CREATE SEQUENCE IF NOT EXISTS user_password_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_password_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  user_id VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  app_type SMALLINT NOT NULL,
  status SMALLINT NOT NULL,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_pwd_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_password_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_password_log.user_id IS 'users.user_id';
COMMENT ON COLUMN user_password_log.password IS 'users.password';
COMMENT ON COLUMN user_password_log.app_type IS '1: appstore, 2: eshop, 3: mass (os_4)';
COMMENT ON COLUMN user_password_log.status IS '0: pending, 1: success, 2: ignored';
COMMENT ON COLUMN user_password_log.action_type IS '0: by user, 1: by manager';
COMMENT ON COLUMN user_password_log.action_by IS 'users.user_pk or managers.manager_pk';

ALTER TABLE user_password_log ALTER COLUMN table_pk SET DEFAULT nextval('user_password_log_s');
ALTER SEQUENCE user_password_log_s OWNED BY user_password_log.table_pk;

-- user register log (user should be registered for eshop, appstore, os_4)
CREATE SEQUENCE IF NOT EXISTS user_register_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_register_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  cid VARCHAR(12),
  iccid VARCHAR(64),
  app_type SMALLINT NOT NULL,
  status SMALLINT NOT NULL,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_reg_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_register_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_register_log.cid IS 'cid';
COMMENT ON COLUMN user_register_log.iccid IS 'iccid';
COMMENT ON COLUMN user_register_log.app_type IS '1: appstore, 2: eshop, 3: mass (os_4)';
COMMENT ON COLUMN user_register_log.status IS '0: pending, 1: success, 2: ignored';
COMMENT ON COLUMN user_register_log.action_type IS '0: by user, 1: by manager';
COMMENT ON COLUMN user_register_log.action_by IS 'users.user_pk or managers.manager_pk';

ALTER TABLE user_register_log ALTER COLUMN table_pk SET DEFAULT nextval('user_register_log_s');
ALTER SEQUENCE user_register_log_s OWNED BY user_register_log.table_pk;

-- user fixed log (merge fixed id fail log)
CREATE SEQUENCE IF NOT EXISTS user_fixed_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_fixed_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  user_id VARCHAR(50) NOT NULL,
  fixed_id VARCHAR(50) NOT NULL,
  func_type SMALLINT NOT NULL,
  status SMALLINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_fixed_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_fixed_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_fixed_log.user_id IS 'previous users.user_id, for mobile, should be updated to fixed_id';
COMMENT ON COLUMN user_fixed_log.fixed_id IS 'customers.user_userid';
COMMENT ON COLUMN user_fixed_log.func_type IS '1: appstore, 2: eprod soft point, 3: eprod reg point';
COMMENT ON COLUMN user_fixed_log.status IS '0: pending, 1: success, 2: ignored';

ALTER TABLE user_fixed_log ALTER COLUMN table_pk SET DEFAULT nextval('user_fixed_log_s');
ALTER SEQUENCE user_fixed_log_s OWNED BY user_fixed_log.table_pk;

-- user login log
CREATE SEQUENCE IF NOT EXISTS user_login_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_login_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  cid VARCHAR(12),
  phone_brand VARCHAR(100) NOT NULL,
  phone_model VARCHAR(100) NOT NULL,
  phone_imei VARCHAR(20) NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_login_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN user_login_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_login_log.cid IS 'cid';
COMMENT ON COLUMN user_login_log.cid IS 'SIM CID';
COMMENT ON COLUMN user_login_log.phone_brand IS 'phone brand';
COMMENT ON COLUMN user_login_log.phone_model IS 'phone model';
COMMENT ON COLUMN user_login_log.phone_imei IS 'phone imei';

ALTER TABLE user_login_log ALTER COLUMN table_pk SET DEFAULT nextval('user_login_log_s');
ALTER SEQUENCE user_login_log_s OWNED BY user_login_log.table_pk;

-- user block log
CREATE SEQUENCE IF NOT EXISTS user_block_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_block_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_block_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_user_block_log_action_by FOREIGN KEY (action_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN user_block_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_block_log.reason IS 'block reason';
COMMENT ON COLUMN user_block_log.status IS '0: active, 1: blocked';
COMMENT ON COLUMN user_block_log.action_by IS 'managers.manager_pk';

ALTER TABLE user_block_log ALTER COLUMN table_pk SET DEFAULT nextval('user_block_log_s');
ALTER SEQUENCE user_block_log_s OWNED BY user_block_log.table_pk;

-- user white list
CREATE SEQUENCE IF NOT EXISTS user_white_list_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_white_list (
  table_pk BIGINT PRIMARY KEY,
  user_name VARCHAR(50) NOT NULL,
  cid VARCHAR(12) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN user_white_list.user_name IS 'user name';
COMMENT ON COLUMN user_white_list.cid IS 'CID';

ALTER TABLE user_white_list ALTER COLUMN table_pk SET DEFAULT nextval('user_white_list_s');
ALTER SEQUENCE user_white_list_s OWNED BY user_white_list.table_pk;

-- user cid lock list
CREATE SEQUENCE IF NOT EXISTS user_cid_lock_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE user_cid_lock (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  cid VARCHAR(12) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_cid_lock_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT uq_user_cid_lock UNIQUE (user_pk, cid)
);

COMMENT ON COLUMN user_cid_lock.user_pk IS 'users.user_pk';
COMMENT ON COLUMN user_cid_lock.cid IS 'CID to be allowed';

ALTER TABLE user_cid_lock ALTER COLUMN table_pk SET DEFAULT nextval('user_cid_lock_s');
ALTER SEQUENCE user_cid_lock_s OWNED BY user_cid_lock.table_pk;

-- export locations
SELECT location_pk, location_name, location_code, parent_code, TO_CHAR(updated_at, 'YYYY-MM-DD HH24:MI:SS') updated_at 
FROM locations
order by updated_at desc
