-- Converted from Oracle: 03_table_ads.sql
-- Generated by tools/oracle2pg.py - review before running.

-- predefined layouts
CREATE TABLE predef_layouts (
  predef_id VARCHAR(255) PRIMARY KEY,
  predef_name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_1x1', '1x1 table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_1x2', '1x2 table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_1x3', '1x3 table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_1x4', '1x4 table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_1xn', '1xn table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_2x2', '2x2 table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('t_2xn', '2xn table');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x2_21_11_11', 'grid 2x2 with right 2 pieces');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x2_11_11_21', 'grid 2x2 with left 2 pieces');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_21_12_12', 'grid 2x3 with right 2 pieces');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_12_12_21', 'grid 2x3 with left 2 pieces');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_12_11_11_21', 'grid 2x3 but 2 pieces in left-bottom');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_21_12_11_11', 'grid 2x3 but 2 pieces in right-bottom');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_21_11_11_12', 'grid 2x3 but 2 pieces in right-top');
INSERT INTO predef_layouts(predef_id, predef_name) VALUES ('g_2x3_11_11_12_21', 'grid 2x3 but 2 pieces in left-top');

-- advertisements
CREATE SEQUENCE IF NOT EXISTS advertisements_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE advertisements (
  ad_pk BIGINT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  image_url VARCHAR(255),
  image_ratio NUMERIC(7,4),
  image_sync SMALLINT DEFAULT 0,
  content_url VARCHAR(255),
  content_sync SMALLINT DEFAULT 0,
  phone_number VARCHAR(20),
  ad_action VARCHAR(255),
  duty_action SMALLINT,
  note VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_ad_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_ad_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN advertisements.title IS 'Title of advertisement';
COMMENT ON COLUMN advertisements.content IS 'Content of advertisement';
COMMENT ON COLUMN advertisements.image_url IS 'Uploaded Image';
COMMENT ON COLUMN advertisements.image_ratio IS 'Aspect ratio of image width : height';
COMMENT ON COLUMN advertisements.image_sync IS 'image sync status with mobile server, 0: pending, 1: approved';
COMMENT ON COLUMN advertisements.content_url IS 'Content Image';
COMMENT ON COLUMN advertisements.content_sync IS 'content image sync status with mobile server, 0: pending, 1: approved';
COMMENT ON COLUMN advertisements.phone_number IS 'Related phone BIGINT';
COMMENT ON COLUMN advertisements.ad_action IS 'advertise action when it is clicked';
COMMENT ON COLUMN advertisements.duty_action IS 'duties.action';
COMMENT ON COLUMN advertisements.note IS 'Comment for this ad';

ALTER TABLE advertisements ALTER COLUMN ad_pk SET DEFAULT nextval('advertisements_s');
ALTER SEQUENCE advertisements_s OWNED BY advertisements.ad_pk;

-- layouts
CREATE SEQUENCE IF NOT EXISTS layouts_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE layouts (
  layout_pk BIGINT PRIMARY KEY,
  predef_id VARCHAR(255) NOT NULL,
  layout_name VARCHAR(255) NOT NULL,
  autoplay SMALLINT DEFAULT 1,
  show_name SMALLINT DEFAULT 0,
  show_more SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_layout_predef_id FOREIGN KEY (predef_id) REFERENCES predef_layouts(predef_id),
  CONSTRAINT fk_layout_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_layout_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT ck_layout_autoplay CHECK (autoplay IN (0, 1)),
  CONSTRAINT ck_layout_show_name CHECK (show_name IN (0, 1)),
  CONSTRAINT ck_layout_show_more CHECK (show_more IN (0, 1))
);

COMMENT ON COLUMN layouts.predef_id IS 'predef_layouts.layout_id';
COMMENT ON COLUMN layouts.layout_name IS 'layout name, can be shown on display by show_name flag';
COMMENT ON COLUMN layouts.autoplay IS 'autoplay carousel';
COMMENT ON COLUMN layouts.show_name IS 'show layout name on phone';
COMMENT ON COLUMN layouts.show_more IS 'chevron right icon right to the layout name to navigate more';

ALTER TABLE layouts ALTER COLUMN layout_pk SET DEFAULT nextval('layouts_s');
ALTER SEQUENCE layouts_s OWNED BY layouts.layout_pk;

-- layout vs advertisements
CREATE SEQUENCE IF NOT EXISTS layout_ads_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE layout_ads (
  table_pk BIGINT PRIMARY KEY,
  layout_pk BIGINT NOT NULL,
  pre_index SMALLINT NOT NULL,
  ad_pk BIGINT NOT NULL,
  position SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NOT NULL,
  CONSTRAINT fk_layout_ads_layout FOREIGN KEY (layout_pk) REFERENCES layouts(layout_pk),
  CONSTRAINT fk_layout_ads_ad FOREIGN KEY (ad_pk) REFERENCES advertisements(ad_pk),
  CONSTRAINT fk_layout_ads_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_layout_ads_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN layout_ads.layout_pk IS 'layouts.layout_pk';
COMMENT ON COLUMN layout_ads.pre_index IS 'predefined index of layout';
COMMENT ON COLUMN layout_ads.ad_pk IS 'advertisements.ad_pk';
COMMENT ON COLUMN layout_ads.position IS 'display order';

ALTER TABLE layout_ads ALTER COLUMN table_pk SET DEFAULT nextval('layout_ads_s');
ALTER SEQUENCE layout_ads_s OWNED BY layout_ads.table_pk;

-- homepage configs
CREATE SEQUENCE IF NOT EXISTS home_configs_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE home_configs (
  table_pk BIGINT PRIMARY KEY,
  config_name VARCHAR(255) NOT NULL,
  layout_pk BIGINT,
  section_name VARCHAR(255),
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  is_test SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NOT NULL,
  CONSTRAINT fk_home_configs_layout FOREIGN KEY (layout_pk) REFERENCES layouts(layout_pk),
  CONSTRAINT fk_home_configs_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_home_configs_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT chk_layout_or_section CHECK (
    (layout_pk IS NOT NULL AND section_name IS NULL) OR
    (layout_pk IS NULL AND section_name IS NOT NULL)
  )
);

COMMENT ON COLUMN home_configs.config_name IS 'config name to distinguish layout or section';
COMMENT ON COLUMN home_configs.layout_pk IS 'layouts.layout_pk';
COMMENT ON COLUMN home_configs.position IS 'display order';
COMMENT ON COLUMN home_configs.section_name IS 'predefined name with app to show section that is not layout';
COMMENT ON COLUMN home_configs.is_deleted IS 'soft delete flag';
COMMENT ON COLUMN home_configs.is_test IS 'flag to indicate it is used for test';

ALTER TABLE home_configs ALTER COLUMN table_pk SET DEFAULT nextval('home_configs_s');
ALTER SEQUENCE home_configs_s OWNED BY home_configs.table_pk;

-- home_menus
CREATE SEQUENCE IF NOT EXISTS home_menus_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE home_menus (
  menu_pk BIGINT PRIMARY KEY,
  icon_name VARCHAR(255),
  icon_url VARCHAR(255),
  menu_name VARCHAR(255) NOT NULL,
  menu_action VARCHAR(255),
  message VARCHAR(255),
  position SMALLINT DEFAULT 0,
  note VARCHAR(255),
  is_deleted SMALLINT DEFAULT 0,
  is_test SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NOT NULL,
  CONSTRAINT fk_home_menus_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_home_menus_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT chk_action_or_message CHECK (
    (menu_action IS NOT NULL) OR
    (menu_action IS NULL AND message IS NOT NULL)
  )
);

COMMENT ON COLUMN home_menus.icon_name IS 'name of the icon, used for pre-allocated icon files';
COMMENT ON COLUMN home_menus.icon_url IS 'url of the icon, used for dynamic icon loading';
COMMENT ON COLUMN home_menus.menu_name IS 'name of the menu item';
COMMENT ON COLUMN home_menus.menu_action IS 'action to perform when then menu is clicked (can be NULL)';
COMMENT ON COLUMN home_menus.message IS 'toast message to show when menu_action is NULL';
COMMENT ON COLUMN home_menus.note IS 'note (action can be activity, and if you temporally clear action, please backup to here)';
COMMENT ON COLUMN home_menus.position IS 'sort order';
COMMENT ON COLUMN home_menus.is_deleted IS 'soft delete flag';
COMMENT ON COLUMN home_menus.is_test IS 'test flag, 1: for test';

ALTER TABLE home_menus ALTER COLUMN menu_pk SET DEFAULT nextval('home_menus_s');
ALTER SEQUENCE home_menus_s OWNED BY home_menus.menu_pk;

-- home popups
CREATE SEQUENCE IF NOT EXISTS home_popups_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE home_popups (
  table_pk BIGINT PRIMARY KEY,
  image_url VARCHAR(255),
  image_sync SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_home_popup_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_home_popup_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN home_popups.image_url IS 'URL of the image';
COMMENT ON COLUMN home_popups.image_status IS 'sync status with mobile server, 0: pending, 1: approved';
COMMENT ON COLUMN home_popups.position IS 'sort order';

ALTER TABLE home_popups ALTER COLUMN table_pk SET DEFAULT nextval('home_popups_s');
ALTER SEQUENCE home_popups_s OWNED BY home_popups.table_pk;

-- page banners
CREATE SEQUENCE IF NOT EXISTS page_banners_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE page_banners (
  table_pk BIGINT PRIMARY KEY,
  image_url VARCHAR(255),
  image_ratio NUMERIC(7,4),
  page_type SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  action VARCHAR(255),
  status SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN page_banners.image_url IS 'URL of the banner image';
COMMENT ON COLUMN page_banners.image_ratio IS 'Aspect ratio of image width : height';
COMMENT ON COLUMN page_banners.page_type IS '0: experience, 1: products';
COMMENT ON COLUMN page_banners.action IS 'action';
COMMENT ON COLUMN page_banners.status IS '0: pending, 1: approved';
COMMENT ON COLUMN page_banners.position IS 'sort order';

ALTER TABLE page_banners ALTER COLUMN table_pk SET DEFAULT nextval('page_banners_s');
ALTER SEQUENCE page_banners_s OWNED BY page_banners.table_pk;

