-- Converted from Oracle: 04_table_blogs.sql
-- Generated by tools/oracle2pg.py - review before running.

-- blog categories
CREATE SEQUENCE IF NOT EXISTS blog_categories_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE blog_categories (
  category_pk BIGINT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN blog_categories.name IS 'Category Name';
COMMENT ON COLUMN blog_categories.description IS 'Category Description';

ALTER TABLE blog_categories ALTER COLUMN category_id SET DEFAULT nextval('blog_categories_s');
ALTER SEQUENCE blog_categories_s OWNED BY blog_categories.category_id;

INSERT INTO blog_categories (name, description) VALUES ('Phone', 'About phones');
INSERT INTO blog_categories (name, description) VALUES ('EProd', 'About electronic products');

-- Blogs
CREATE SEQUENCE IF NOT EXISTS blogs_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE blogs (
  blog_pk BIGINT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  cleaned_content VARCHAR(4000),
  image_url VARCHAR(255),
  status SMALLINT DEFAULT 0,
  category_pk BIGINT,
  post_type VARCHAR(10) NOT NULL,
  series_group_id BIGINT,
  -- series_part_number BIGINT,
  parent_pk BIGINT,
  user_pk BIGINT NOT NULL,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_blog_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_blog_category_id FOREIGN KEY (category_pk) REFERENCES blog_categories(category_pk),
  CONSTRAINT fk_blog_parent_pk FOREIGN KEY (parent_pk) REFERENCES blogs(blog_pk),
  CONSTRAINT ck_blog_status CHECK (status IN (0, 1, 2, 3)),
  CONSTRAINT ck_blog_post_type CHECK (post_type IN ('general', 'help', 'topic', 'series')),
  CONSTRAINT ck_blog_is_deleted CHECK (is_deleted IN (0, 1))
);

COMMENT ON COLUMN blogs.title IS 'Blog Title';
COMMENT ON COLUMN blogs.content IS 'Blog Content (containing html tag)';
COMMENT ON COLUMN blogs.cleaned_content IS 'Blog Content (html tag stripped)';
COMMENT ON COLUMN blogs.image_url IS 'blog if image containes';
COMMENT ON COLUMN blogs.status IS '(0: Pending, 1: Published, 2: Manager Checking, 3: Draft)';
COMMENT ON COLUMN blogs.category_id IS 'blog_categories.category_id';
COMMENT ON COLUMN blogs.post_type IS 'general, help, topic, series';
COMMENT ON COLUMN blogs.series_group_id IS 'Group identifier for articles in a series (NULL for non-series blogs)';
COMMENT ON COLUMN blogs.parent_pk IS 'Self-referencing blog (for replies) = blogs.blog_pk';
COMMENT ON COLUMN blogs.user_pk IS 'users.user_pk that whom posts blog';

ALTER TABLE blogs ALTER COLUMN blog_pk SET DEFAULT nextval('blogs_s');
ALTER SEQUENCE blogs_s OWNED BY blogs.blog_pk;

