-- Converted from Oracle: 05_table_devices.sql
-- Generated by tools/oracle2pg.py - review before running.

-- devices
CREATE SEQUENCE IF NOT EXISTS devices_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE devices (
  device_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  cid VARCHAR(12) NOT NULL,
  phone_brand VARCHAR(100) NOT NULL,
  phone_model VARCHAR(100) NOT NULL,
  phone_imei VARCHAR(20) NOT NULL,
  last_logged_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  report_status SMALLINT DEFAULT -1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_devices_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT uq_devices_user_cid_imei UNIQUE (user_pk, cid, phone_imei)
);

COMMENT ON COLUMN devices.user_pk IS 'users.user_pk';
COMMENT ON COLUMN devices.cid IS 'SIM CID';
COMMENT ON COLUMN devices.phone_brand IS 'phone brand';
COMMENT ON COLUMN devices.phone_model IS 'phone model';
COMMENT ON COLUMN devices.phone_imei IS 'phone imei';
COMMENT ON COLUMN devices.last_logged_in IS 'timestamp last login time';
COMMENT ON COLUMN devices.is_deleted IS '1: deleted';
COMMENT ON COLUMN devices.report_status IS 'report status, -1: none, device_reports.status';

ALTER TABLE devices ALTER COLUMN device_pk SET DEFAULT nextval('devices_s');
ALTER SEQUENCE devices_s OWNED BY devices.device_pk;

CREATE SEQUENCE IF NOT EXISTS device_reports_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE device_reports (
  report_pk BIGINT PRIMARY KEY,
  device_pk BIGINT NOT NULL,
  report_type SMALLINT DEFAULT 0 NOT NULL,
  report_by BIGINT NOT NULL,
  target_pk BIGINT,
  status SMALLINT DEFAULT 0,
  resolve_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_device_report_dev_pk FOREIGN KEY (device_pk) REFERENCES devices(device_pk),
  CONSTRAINT fk_device_report_target_pk FOREIGN KEY (target_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_device_report_resolve_by FOREIGN KEY (resolve_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN device_reports.device_pk IS 'devices.device_pk';
COMMENT ON COLUMN device_reports.report_type IS '0: by user, 1: by manager';
COMMENT ON COLUMN device_reports.report_by IS 'users.user_pk or managers.manager_pk';
COMMENT ON COLUMN device_reports.target_pk IS 'users.user_pk';
COMMENT ON COLUMN device_reports.status IS '0: pending, 1: accepted, 2: denied, 3: canceled';
COMMENT ON COLUMN device_reports.resolve_by IS 'managers.manager_pk';

ALTER TABLE device_reports ALTER COLUMN report_pk SET DEFAULT nextval('device_reports_s');
ALTER SEQUENCE device_reports_s OWNED BY device_reports.report_pk;

-- smart phones
CREATE SEQUENCE IF NOT EXISTS smart_phones_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE smart_phones (
  phone_pk BIGINT PRIMARY KEY,
  phone_brand VARCHAR(100) NOT NULL,
  phone_model VARCHAR(100) NOT NULL,
  phone_name VARCHAR(128) NOT NULL,
  COMPANY VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_smart_phone UNIQUE (phone_brand, phone_model)
);

COMMENT ON COLUMN smart_phones.phone_brand IS 'phone brand';
COMMENT ON COLUMN smart_phones.phone_model IS 'phone model';
COMMENT ON COLUMN smart_phones.phone_name IS 'phone name';
COMMENT ON COLUMN smart_phones.company IS 'company name';

ALTER TABLE smart_phones ALTER COLUMN phone_pk SET DEFAULT nextval('smart_phones_s');
ALTER SEQUENCE smart_phones_s OWNED BY smart_phones.phone_pk;

