-- Converted from Oracle: 06_table_messages.sql
-- Generated by tools/oracle2pg.py - review before running.

-- feedback_threads
CREATE SEQUENCE IF NOT EXISTS feedback_threads_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE feedback_threads (
  thread_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  title VARCHAR(512) NOT NULL,
  category SMALLINT DEFAULT 0 NOT NULL,
  thread_source SMALLINT DEFAULT 0,
  last_message VARCHAR(4000),
  last_type SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  is_read SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  session_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_thread_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_feedback_thread_manager_pk FOREIGN KEY (session_by) REFERENCES managers(manager_pk)
);

ALTER TABLE feedback_threads ALTER COLUMN thread_pk SET DEFAULT nextval('feedback_threads_s');
ALTER SEQUENCE feedback_threads_s OWNED BY feedback_threads.thread_pk;

-- feedback_messages
CREATE SEQUENCE IF NOT EXISTS feedback_messages_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE feedback_messages (
  message_pk BIGINT PRIMARY KEY,
  thread_pk BIGINT NOT NULL,
  message VARCHAR(4000) NOT NULL,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_msg_thread_pk FOREIGN KEY (thread_pk) REFERENCES feedback_threads(thread_pk)
);

COMMENT ON COLUMN feedback_messages.thread_pk IS 'feedback_threads.thread_pk';
COMMENT ON COLUMN feedback_messages.message IS 'message';
COMMENT ON COLUMN feedback_messages.action_type IS '0: user feedback, 1: manager reply';
COMMENT ON COLUMN feedback_messages.action_by IS 'when action_type is 0, its users.user_pk, when 1 managers.manager_pk';

ALTER TABLE feedback_messages ALTER COLUMN message_pk SET DEFAULT nextval('feedback_messages_s');
ALTER SEQUENCE feedback_messages_s OWNED BY feedback_messages.message_pk;

-- feedback category log
CREATE SEQUENCE IF NOT EXISTS feedback_category_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE feedback_category_log (
  table_pk BIGINT PRIMARY KEY,
  thread_pk BIGINT NOT NULL,
  category SMALLINT DEFAULT 0 NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  action_by BIGINT NOT NULL,
  CONSTRAINT fk_fb_category_log_thread_pk FOREIGN KEY (thread_pk) REFERENCES feedback_threads(thread_pk),
  CONSTRAINT fk_fb_category_log_action_by FOREIGN KEY (action_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN feedback_category_log.thread_pk IS 'feedback_threads.thread_pk';
COMMENT ON COLUMN feedback_category_log.category IS 'feedback_threads.category';
COMMENT ON COLUMN feedback_category_log.action_by IS 'managers.manager_pk';

ALTER TABLE feedback_category_log ALTER COLUMN table_pk SET DEFAULT nextval('feedback_category_log_s');
ALTER SEQUENCE feedback_category_log_s OWNED BY feedback_category_log.table_pk;

-- feedback status log
CREATE SEQUENCE IF NOT EXISTS feedback_status_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE feedback_status_log (
  table_pk BIGINT PRIMARY KEY,
  thread_pk BIGINT NOT NULL,
  status SMALLINT DEFAULT 0,
  note VARCHAR(128),
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  action_type SMALLINT DEFAULT 0 NOT NULL,
  action_by BIGINT NOT NULL,
  CONSTRAINT fk_fb_status_log_thread_pk FOREIGN KEY (thread_pk) REFERENCES feedback_threads(thread_pk)
);

COMMENT ON COLUMN feedback_status_log.thread_pk IS 'feedback_threads.thread_pk';
COMMENT ON COLUMN feedback_status_log.status IS '0: discussing, 1: resolved, 2: finished';
COMMENT ON COLUMN feedback_status_log.note IS 'note when resolve by manager';
COMMENT ON COLUMN feedback_status_log.action_type IS '0: by user, 1: by manager';
COMMENT ON COLUMN feedback_status_log.action_by IS 'users.user_pk or managers.manager_pk';

ALTER TABLE feedback_status_log ALTER COLUMN table_pk SET DEFAULT nextval('feedback_status_log_s');
ALTER SEQUENCE feedback_status_log_s OWNED BY feedback_status_log.table_pk;

-- feedback forward log
CREATE SEQUENCE IF NOT EXISTS feedback_forward_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE feedback_forward_log (
  table_pk BIGINT PRIMARY KEY,
  message_pk BIGINT UNIQUE NOT NULL,
  thread_pk BIGINT NOT NULL,
  qc_level SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  action_by BIGINT NOT NULL,
  CONSTRAINT fk_fb_qc_log_msg_pk FOREIGN KEY (message_pk) REFERENCES feedback_messages(message_pk),
  CONSTRAINT fk_fb_qc_log_thread_pk FOREIGN KEY (thread_pk) REFERENCES feedback_threads(thread_pk),
  CONSTRAINT fk_fb_qc_log_action_by FOREIGN KEY (action_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN feedback_forward_log.message_pk IS 'feedback_messages.message_pk';
COMMENT ON COLUMN feedback_forward_log.thread_pk IS 'feedback_messages.thread_pk';
COMMENT ON COLUMN feedback_forward_log.action_by IS 'managers.manager_pk';

ALTER TABLE feedback_forward_log ALTER COLUMN table_pk SET DEFAULT nextval('feedback_forward_log_s');
ALTER SEQUENCE feedback_forward_log_s OWNED BY feedback_forward_log.table_pk;

-- broadcasts
CREATE SEQUENCE IF NOT EXISTS broadcast_contents_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE broadcast_contents (
  broadcast_pk BIGINT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(4000) NOT NULL,
  to_all SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_by BIGINT,
  CONSTRAINT fk_broadcasts_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_broadcasts_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN broadcast_contents.title IS 'Title of the broadcast message';
COMMENT ON COLUMN broadcast_contents.content IS 'Content of the broadcast message';
COMMENT ON COLUMN broadcast_contents.to_all IS 'broadcast to all users';
COMMENT ON COLUMN broadcast_contents.is_deleted IS '0: Active, 1: Deleted';

ALTER TABLE broadcast_contents ALTER COLUMN broadcast_pk SET DEFAULT nextval('broadcast_contents_s');
ALTER SEQUENCE broadcast_contents_s OWNED BY broadcast_contents.broadcast_pk;

CREATE SEQUENCE IF NOT EXISTS broadcast_users_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE broadcast_users (
  table_pk BIGINT PRIMARY KEY,
  broadcast_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  is_read SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  CONSTRAINT fk_broaduser_broadcast_pk FOREIGN KEY (broadcast_pk) REFERENCES broadcast_contents(broadcast_pk),
  CONSTRAINT fk_broaduser_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_broaduser_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN broadcast_users.broadcast_pk IS 'broadcast_contents.broadcast_pk';
COMMENT ON COLUMN broadcast_users.user_pk IS 'users.user_pk';
COMMENT ON COLUMN broadcast_users.is_read IS '0: none, 1: read';
COMMENT ON COLUMN broadcast_users.is_deleted IS '0: Not deleted, 1: Deleted';

ALTER TABLE broadcast_users ALTER COLUMN table_pk SET DEFAULT nextval('broadcast_users_s');
ALTER SEQUENCE broadcast_users_s OWNED BY broadcast_users.table_pk;

-- notifications
CREATE SEQUENCE IF NOT EXISTS notifications_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE notifications (
  notification_pk BIGINT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  cleaned_content VARCHAR(4000) NOT NULL,
  image_url VARCHAR(255),
  status SMALLINT DEFAULT 0,
  category SMALLINT DEFAULT 0,
  goto VARCHAR(1000),
  is_popular SMALLINT DEFAULT 0,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_notifications_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_notifications_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT chk_notifications_period CHECK (end_date >= start_date)
);

COMMENT ON COLUMN notifications.title IS 'notification title';
COMMENT ON COLUMN notifications.content IS 'notification content (including HTML)';
COMMENT ON COLUMN notifications.cleaned_content IS 'notification content (HTML stripped)';
COMMENT ON COLUMN notifications.image_url IS 'image path';
COMMENT ON COLUMN notifications.status IS '0: pending, 1: draft, 2: show';
COMMENT ON COLUMN notifications.category IS '0: PRHN, 1: other';
COMMENT ON COLUMN notifications.goto IS 'action, it can be activity for app, url for web';
COMMENT ON COLUMN notifications.is_popular IS '1: popular, 0: none';
COMMENT ON COLUMN notifications.start_date IS 'start date';
COMMENT ON COLUMN notifications.end_date IS 'end date';
COMMENT ON COLUMN notifications.position IS 'sort order';
COMMENT ON COLUMN notifications.is_deleted IS 'soft delete flag';

ALTER TABLE notifications ALTER COLUMN notification_pk SET DEFAULT nextval('notifications_s');
ALTER SEQUENCE notifications_s OWNED BY notifications.notification_pk;

-- faqs
CREATE SEQUENCE IF NOT EXISTS faqs_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE faqs (
  faq_pk BIGINT PRIMARY KEY,
  question VARCHAR(500) NOT NULL,
  answer TEXT NOT NULL,
  category SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_faqs_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_faqs_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN faqs.question IS 'question';
COMMENT ON COLUMN faqs.answer IS 'answer';
COMMENT ON COLUMN faqs.category IS '0: pid, 1: phone, 2: TV, 3: STB, 4: PC, 5: camera, 6: etc, 7: appstore';
COMMENT ON COLUMN faqs.position IS 'sort order';
COMMENT ON COLUMN faqs.is_deleted IS 'soft delete flag';

ALTER TABLE faqs ALTER COLUMN faq_pk SET DEFAULT nextval('faqs_s');
ALTER SEQUENCE faqs_s OWNED BY faqs.faq_pk;

