-- Converted from Oracle: 07_table_surveys.sql
-- Generated by tools/oracle2pg.py - review before running.

-- surveys
CREATE SEQUENCE IF NOT EXISTS surveys_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE surveys (
  survey_pk BIGINT PRIMARY KEY,
  survey_category SMALLINT DEFAULT 0,
  survey_name VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_by BIGINT NOT NULL,
  updated_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_surveys_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_surveys_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT chk_surveys_period CHECK (end_date >= start_date)
);

COMMENT ON COLUMN surveys.survey_name IS 'Name of the survey';
COMMENT ON COLUMN surveys.position IS 'sort order';

ALTER TABLE surveys ALTER COLUMN survey_pk SET DEFAULT nextval('surveys_s');
ALTER SEQUENCE surveys_s OWNED BY surveys.survey_pk;

-- survey questions
CREATE SEQUENCE IF NOT EXISTS survey_questions_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE survey_questions (
  question_pk BIGINT PRIMARY KEY,
  survey_pk BIGINT NOT NULL,
  question_text VARCHAR(1024) NOT NULL,
  question_type SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  publish_num VARCHAR(24),
  created_by BIGINT NOT NULL,
  updated_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_survey_q_survey_pk FOREIGN KEY (survey_pk) REFERENCES surveys(survey_pk),
  CONSTRAINT fk_survey_q_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_surveys_q_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN survey_questions.survey_pk IS 'surveys.survey_pk';
COMMENT ON COLUMN survey_questions.question_text IS 'text of the survey question';
COMMENT ON COLUMN survey_questions.question_type IS '0: single choice, 1: multiple choice, 2: text';
COMMENT ON COLUMN survey_questions.position IS 'sort order';
COMMENT ON COLUMN survey_questions.publish_num IS 'publish approve BIGINT';

ALTER TABLE survey_questions ALTER COLUMN question_pk SET DEFAULT nextval('survey_questions_s');
ALTER SEQUENCE survey_questions_s OWNED BY survey_questions.question_pk;

-- survey choices
CREATE SEQUENCE IF NOT EXISTS survey_choices_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE survey_choices (
  choice_pk BIGINT PRIMARY KEY,
  question_pk BIGINT NOT NULL,
  choice_text VARCHAR(255) NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_by BIGINT,
  CONSTRAINT fk_survey_c_question_pk FOREIGN KEY (question_pk) REFERENCES survey_questions(question_pk),
  CONSTRAINT fk_survey_c_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_surveys_c_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN survey_choices.question_pk IS 'survey_questions.question_pk';
COMMENT ON COLUMN survey_choices.choice_text IS 'choice text';
COMMENT ON COLUMN survey_choices.position IS 'sort order';

ALTER TABLE survey_choices ALTER COLUMN choice_pk SET DEFAULT nextval('survey_choices_s');
ALTER SEQUENCE survey_choices_s OWNED BY survey_choices.choice_pk;

-- survey responses
CREATE SEQUENCE IF NOT EXISTS survey_responses_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE survey_responses (
  response_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  question_pk BIGINT NOT NULL,
  choice_pk BIGINT,
  response_text VARCHAR(1000),
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_survey_r_user FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_survey_r_question FOREIGN KEY (question_pk) REFERENCES survey_questions(question_pk),
  CONSTRAINT fk_survey_r_choice FOREIGN KEY (choice_pk) REFERENCES survey_choices(choice_pk),
  CONSTRAINT uq_survey_c_q_user UNIQUE (user_pk, question_pk, choice_pk)
);

COMMENT ON COLUMN survey_responses.user_pk IS 'users.user_pk';
COMMENT ON COLUMN survey_responses.question_pk IS 'survey_questions.question_pk';
COMMENT ON COLUMN survey_responses.choice_pk IS 'survey_choices.choice_pk, can be NULL for text reponses';
COMMENT ON COLUMN survey_responses.response_text IS 'text response when choice_pk is NULL';

ALTER TABLE survey_responses ALTER COLUMN response_pk SET DEFAULT nextval('survey_responses_s');
ALTER SEQUENCE survey_responses_s OWNED BY survey_responses.response_pk;

