-- Converted from Oracle: 08_table_experience.sql
-- Generated by tools/oracle2pg.py - review before running.

-- duties
CREATE SEQUENCE IF NOT EXISTS duties_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE duties (
  duty_pk BIGINT PRIMARY KEY,
  duty_title VARCHAR(255) NOT NULL,
  icon_name VARCHAR(255),
  icon_url VARCHAR(255),
  point_type INTEGER DEFAULT 0 NOT NULL,
  action SMALLINT,
  content TEXT,
  image_url VARCHAR(255),
  duty_type SMALLINT DEFAULT 0 NOT NULL,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  disp_date TIMESTAMP,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_duties_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_duties_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN duties.duty_title IS 'title of the duty';
COMMENT ON COLUMN duties.icon_name IS 'name of the duty icon';
COMMENT ON COLUMN duties.icon_url IS 'url of the duty icon';
COMMENT ON COLUMN duties.point_type IS 'activity_point_types.type_pk, if 4-length, it can be prefix';
COMMENT ON COLUMN duties.action IS 'predefined action related to the duty';
COMMENT ON COLUMN duties.content IS 'content of the duty (html)';
COMMENT ON COLUMN duties.image_url IS 'url for the image related to the duty';
COMMENT ON COLUMN duties.duty_type IS '0: daily, 1: periodically';
COMMENT ON COLUMN duties.start_date IS 'start date (only for periodically duties)';
COMMENT ON COLUMN duties.end_date IS 'end date (only for periodically duties)';
COMMENT ON COLUMN duties.disp_date IS 'display date (only for periodically duties)';

ALTER TABLE duties ALTER COLUMN duty_pk SET DEFAULT nextval('duties_s');
ALTER SEQUENCE duties_s OWNED BY duties.duty_pk;

-- achievements
CREATE SEQUENCE IF NOT EXISTS achievements_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE achievements (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  duty_pk BIGINT NOT NULL,
  point_type INTEGER DEFAULT 0 NOT NULL,
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_achieve_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_achieve_duty_pk FOREIGN KEY (duty_pk) REFERENCES duties(duty_pk)
);

COMMENT ON COLUMN achievements.user_pk IS 'users.user_pk';
COMMENT ON COLUMN achievements.duty_pk IS 'duties.duty_pk';
COMMENT ON COLUMN achievements.point_type IS 'activity_point_types.type_pk';
COMMENT ON COLUMN achievements.points IS 'point achieved, once duty point is changed, it can be used for logging';

ALTER TABLE achievements ALTER COLUMN table_pk SET DEFAULT nextval('achievements_s');
ALTER SEQUENCE achievements_s OWNED BY achievements.table_pk;

