-- Converted from Oracle: 09_table_update.sql
-- Generated by tools/oracle2pg.py - review before running.

-- app_updates
CREATE TABLE app_updates (
  table_pk BIGINT PRIMARY KEY,
  type SMALLINT NOT NULL,
  version_code SMALLINT NOT NULL,
  last_time TIMESTAMP,
  db_file_time TIMESTAMP,
  status SMALLINT NOT NULL,
  file_url VARCHAR(255),
  note VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN app_updates.type IS 'update type (0: none - no need to update, 1: patch for same version, 2: apk update, 3: patch test)';
COMMENT ON COLUMN app_updates.version_code IS 'release apk version code';
COMMENT ON COLUMN app_updates.last_time IS 'last update time';
COMMENT ON COLUMN app_updates.db_file_time IS 'last db file update time';
COMMENT ON COLUMN app_updates.status IS '0: inactive, 1: active';
COMMENT ON COLUMN app_updates.note IS 'message shown on update confirm dialog';

-- testers
CREATE SEQUENCE IF NOT EXISTS testers_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE testers (
  tester_pk BIGINT PRIMARY KEY,
  tester_name VARCHAR(64) NOT NULL,
  phone_imei VARCHAR(20) UNIQUE NOT NULL,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN testers.tester_name IS 'tester name';
COMMENT ON COLUMN testers.phone_imei IS 'IMEI of the device';

ALTER TABLE testers ALTER COLUMN tester_pk SET DEFAULT nextval('testers_s');
ALTER SEQUENCE testers_s OWNED BY testers.tester_pk;

