-- Converted from Oracle: 10_table_points.sql
-- Generated by tools/oracle2pg.py - review before running.

-- activity point types with predefined pks
CREATE TABLE activity_point_types (
  type_pk INTEGER PRIMARY KEY,
  main_type VARCHAR(100) NOT NULL,
  sub_type VARCHAR(100),
  note VARCHAR(255),
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_act_point_type_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_act_point_type_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN activity_point_types.type_pk IS '6-length predefined type, first 2 for main type, second 2 for sub type, last 2 for everyday';
COMMENT ON COLUMN activity_point_types.main_type IS 'main type';
COMMENT ON COLUMN activity_point_types.sub_type IS 'sub type';
COMMENT ON COLUMN activity_point_types.note IS 'comment for point type';
COMMENT ON COLUMN activity_point_types.points IS 'point to be achieved';

-- activity point log
CREATE SEQUENCE IF NOT EXISTS activity_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE activity_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  type_pk INTEGER NOT NULL,
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  reason VARCHAR(255),
  related_pk BIGINT,
  everyday_cnt SMALLINT,
  ip_address VARCHAR(45),
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN activity_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN activity_point_log.type_pk IS 'activity_point_types.type_pk';
COMMENT ON COLUMN activity_point_log.points IS 'point achieved';
COMMENT ON COLUMN activity_point_log.reason IS 'description of action, can be null, only available for add/delete points by manager';
COMMENT ON COLUMN activity_point_log.related_pk IS 'foreign key to the relevant table (for ora_blog, achievement), -1 activity point when merge fixed id';
COMMENT ON COLUMN activity_point_log.everyday_cnt IS 'everyday login count when merge fixed_id';
COMMENT ON COLUMN activity_point_log.ip_address IS 'ip address when point achieved by using fixed network';

ALTER TABLE activity_point_log ALTER COLUMN table_pk SET DEFAULT nextval('activity_point_log_s');
ALTER SEQUENCE activity_point_log_s OWNED BY activity_point_log.table_pk;

-- activity point stats
CREATE SEQUENCE IF NOT EXISTS activity_point_stats_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE activity_point_stats (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  total_points NUMERIC(8,1) DEFAULT 0,
  limit_points NUMERIC(8,1) DEFAULT 0,
  minus_points NUMERIC(8,1) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_point_stats_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN activity_point_stats.user_pk IS 'users.user_pk';
COMMENT ON COLUMN activity_point_stats.total_points IS 'total point achieved';
COMMENT ON COLUMN activity_point_stats.limit_points IS 'points archieved until activity limit date';
COMMENT ON COLUMN activity_point_stats.minus_points IS 'total minus points by phone book';

ALTER TABLE activity_point_stats ALTER COLUMN table_pk SET DEFAULT nextval('activity_point_stats_s');
ALTER SEQUENCE activity_point_stats_s OWNED BY activity_point_stats.table_pk;

-- activity limits to represent summarizing points of limit date
CREATE SEQUENCE IF NOT EXISTS activity_limits_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE activity_limits (
  table_pk BIGINT PRIMARY KEY,
  activity_source SMALLINT UNIQUE NOT NULL,
  limit_time TIMESTAMP,
  status SMALLINT DEFAULT 0,
  target_rank SMALLINT DEFAULT 0,
  top_count SMALLINT DEFAULT 0,
  surroundings SMALLINT DEFAULT 0,
  description VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN activity_limits.activity_source IS '0: activity_point, 1: soft point, 2: register point';
COMMENT ON COLUMN activity_limits.limit_time IS 'activity limit time';
COMMENT ON COLUMN activity_limits.status IS '0: inactive, 1: active';
COMMENT ON COLUMN activity_limits.target_rank IS 'target rank';
COMMENT ON COLUMN activity_limits.top_count IS 'top count to be displayed';
COMMENT ON COLUMN activity_limits.surroundings IS 'surroundings to be displayed';
COMMENT ON COLUMN activity_limits.description IS 'description';

ALTER TABLE activity_limits ALTER COLUMN table_pk SET DEFAULT nextval('activity_limits_s');
ALTER SEQUENCE activity_limits_s OWNED BY activity_limits.table_pk;

-- appstore point log
CREATE SEQUENCE IF NOT EXISTS appstore_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE appstore_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  reason VARCHAR(255),
  equ_num VARCHAR(64),
  pay_points NUMERIC(10,3) DEFAULT 0,
  soft_points NUMERIC(8,3) DEFAULT 0 NOT NULL,
  related_pk VARCHAR(48),
  is_agency SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_appstore_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN appstore_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN appstore_point_log.status IS '0: plus, 1: minus, 2: refund';
COMMENT ON COLUMN appstore_point_log.reason IS 'appstore: app name';
COMMENT ON COLUMN appstore_point_log.equ_num IS 'device BIGINT';
COMMENT ON COLUMN appstore_point_log.pay_points IS 'pay points, exactly won';
COMMENT ON COLUMN appstore_point_log.soft_points IS 'soft points';
COMMENT ON COLUMN appstore_point_log.related_pk IS 'foreign key to the relevant table of appstore, -1 appstore point when merge appstore id';
COMMENT ON COLUMN appstore_point_log.is_agency IS '0: user, 1: agency';

ALTER TABLE appstore_point_log ALTER COLUMN table_pk SET DEFAULT nextval('appstore_point_log_s');
ALTER SEQUENCE appstore_point_log_s OWNED BY appstore_point_log.table_pk;

-- appstore point stats
CREATE SEQUENCE IF NOT EXISTS appstore_point_stats_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE appstore_point_stats (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  total_points NUMERIC(8,3) DEFAULT 0,
  limit_points NUMERIC(8,3) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_app_point_stats_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN appstore_point_stats.user_pk IS 'users.user_pk';
COMMENT ON COLUMN appstore_point_stats.total_points IS 'total point achieved';
COMMENT ON COLUMN appstore_point_stats.limit_points IS 'points archieved until activity limit date';

ALTER TABLE appstore_point_stats ALTER COLUMN table_pk SET DEFAULT nextval('appstore_point_stats_s');
ALTER SEQUENCE appstore_point_stats_s OWNED BY appstore_point_stats.table_pk;

-- karaoke point log
CREATE SEQUENCE IF NOT EXISTS karaoke_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE karaoke_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  reason VARCHAR(255),
  equ_num VARCHAR(64),
  pay_points NUMERIC(10,3) DEFAULT 0,
  soft_points NUMERIC(8,3) DEFAULT 0 NOT NULL,
  related_pk VARCHAR(48),
  is_agency SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_karaoke_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN karaoke_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN karaoke_point_log.status IS '0: plus, 1: minus, 2: refund';
COMMENT ON COLUMN karaoke_point_log.reason IS 'karaoke, or other reason';
COMMENT ON COLUMN karaoke_point_log.equ_num IS 'device BIGINT';
COMMENT ON COLUMN karaoke_point_log.pay_points IS 'pay points, exactly won';
COMMENT ON COLUMN karaoke_point_log.soft_points IS 'soft points';
COMMENT ON COLUMN karaoke_point_log.related_pk IS 'foreign key to the relevant table, -2 karaoke point when merge fixed id';
COMMENT ON COLUMN karaoke_point_log.is_agency IS '0: user, 1: agency';

ALTER TABLE karaoke_point_log ALTER COLUMN table_pk SET DEFAULT nextval('karaoke_point_log_s');
ALTER SEQUENCE karaoke_point_log_s OWNED BY karaoke_point_log.table_pk;

-- karaoke point stats
CREATE SEQUENCE IF NOT EXISTS karaoke_point_stats_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE karaoke_point_stats (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  total_points NUMERIC(8,3) DEFAULT 0,
  limit_points NUMERIC(8,3) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_kara_point_stats_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN karaoke_point_stats.user_pk IS 'users.user_pk';
COMMENT ON COLUMN karaoke_point_stats.total_points IS 'total point achieved';
COMMENT ON COLUMN karaoke_point_stats.limit_points IS 'points archieved until activity limit date';

ALTER TABLE karaoke_point_stats ALTER COLUMN table_pk SET DEFAULT nextval('karaoke_point_stats_s');
ALTER SEQUENCE karaoke_point_stats_s OWNED BY karaoke_point_stats.table_pk;

-- bmedia point log
CREATE SEQUENCE IF NOT EXISTS bmedia_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE bmedia_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  reason VARCHAR(255),
  equ_num VARCHAR(64),
  pay_points NUMERIC(10,3) DEFAULT 0,
  soft_points NUMERIC(8,3) DEFAULT 0 NOT NULL,
  related_pk VARCHAR(48),
  is_agency SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bmedia_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN bmedia_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN bmedia_point_log.status IS '0: plus, 1: minus, 2: refund';
COMMENT ON COLUMN bmedia_point_log.reason IS 'source of media';
COMMENT ON COLUMN bmedia_point_log.equ_num IS 'device BIGINT';
COMMENT ON COLUMN bmedia_point_log.pay_points IS 'pay points, exactly won';
COMMENT ON COLUMN bmedia_point_log.soft_points IS 'soft points';
COMMENT ON COLUMN bmedia_point_log.related_pk IS 'foreign key to the relevant table, -3 bmedia point when merge fixed id';
COMMENT ON COLUMN bmedia_point_log.is_agency IS '0: user, 1: agency';

ALTER TABLE bmedia_point_log ALTER COLUMN table_pk SET DEFAULT nextval('bmedia_point_log_s');
ALTER SEQUENCE bmedia_point_log_s OWNED BY bmedia_point_log.table_pk;

-- bmedia point stats
CREATE SEQUENCE IF NOT EXISTS bmedia_point_stats_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE bmedia_point_stats (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  total_points NUMERIC(8,3) DEFAULT 0,
  limit_points NUMERIC(8,3) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_media_point_stats_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN bmedia_point_stats.user_pk IS 'users.user_pk';
COMMENT ON COLUMN bmedia_point_stats.total_points IS 'total point achieved';
COMMENT ON COLUMN bmedia_point_stats.limit_points IS 'points archieved until activity limit date';

ALTER TABLE bmedia_point_stats ALTER COLUMN table_pk SET DEFAULT nextval('bmedia_point_stats_s');
ALTER SEQUENCE bmedia_point_stats_s OWNED BY bmedia_point_stats.table_pk;

-- soft point log
CREATE SEQUENCE IF NOT EXISTS soft_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE soft_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  point_type SMALLINT DEFAULT 0 NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  reason VARCHAR(255),
  equ_num VARCHAR(64),
  pay_points NUMERIC(10,3) DEFAULT 0,
  soft_points NUMERIC(8,3) DEFAULT 0 NOT NULL,
  related_pk VARCHAR(48),
  is_agency SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_soft_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN soft_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN soft_point_log.point_type IS '0: appstore, 1: karaoke, 2: bmedia, 3: manager';
COMMENT ON COLUMN soft_point_log.status IS '0: plus, 1: minus, 2: refund';
COMMENT ON COLUMN soft_point_log.reason IS 'appstore: app name, karaoke: karaoke, bmedia: source of media';
COMMENT ON COLUMN soft_point_log.equ_num IS 'device BIGINT';
COMMENT ON COLUMN soft_point_log.pay_points IS 'pay points, exactly won';
COMMENT ON COLUMN soft_point_log.soft_points IS 'soft points';
COMMENT ON COLUMN soft_point_log.related_pk IS 'foreign key to the relevant table (for bmedia, appstore), -1 appstore point when merge appstore id, -2 karaoke point when merge fixed id, -3 bmedia point when merge fixed id';
COMMENT ON COLUMN soft_point_log.is_agency IS '0: user, 1: agency';

ALTER TABLE soft_point_log ALTER COLUMN table_pk SET DEFAULT nextval('soft_point_log_s');
ALTER SEQUENCE soft_point_log_s OWNED BY soft_point_log.table_pk;

-- soft point stats
CREATE SEQUENCE IF NOT EXISTS soft_point_stats_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE soft_point_stats (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT UNIQUE NOT NULL,
  total_points NUMERIC(8,3) DEFAULT 0,
  limit_points NUMERIC(8,3) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_soft_point_stats_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN soft_point_stats.user_pk IS 'users.user_pk';
COMMENT ON COLUMN soft_point_stats.total_points IS 'total point achieved';
COMMENT ON COLUMN soft_point_stats.limit_points IS 'points archieved until activity limit date';

ALTER TABLE soft_point_stats ALTER COLUMN table_pk SET DEFAULT nextval('soft_point_stats_s');
ALTER SEQUENCE soft_point_stats_s OWNED BY soft_point_stats.table_pk;

-- register point log
CREATE SEQUENCE IF NOT EXISTS register_point_log_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE register_point_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  point_type SMALLINT DEFAULT 0 NOT NULL,
  status SMALLINT DEFAULT 0 NOT NULL,
  product_pk BIGINT,
  product_name VARCHAR(128),
  equ_num VARCHAR(64),
  reason VARCHAR(255),
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_register_point_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN register_point_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN register_point_log.point_type IS '0: phone, 1: eprod, 2: manager';
COMMENT ON COLUMN register_point_log.status IS '0: plus, 1: minus, 2: refund';
COMMENT ON COLUMN register_point_log.product_pk IS 'products.product_pk, NULL when point_type is manager';
COMMENT ON COLUMN register_point_log.product_name IS 'product name';
COMMENT ON COLUMN register_point_log.equ_num IS 'device BIGINT, phone: IMEI, eprod: SN';
COMMENT ON COLUMN register_point_log.reason IS 'only available for add/delete points by manager';
COMMENT ON COLUMN register_point_log.points IS 'register points';

ALTER TABLE register_point_log ALTER COLUMN table_pk SET DEFAULT nextval('register_point_log_s');
ALTER SEQUENCE register_point_log_s OWNED BY register_point_log.table_pk;

-- recalc activity points to stats
update ACTIVITY_POINT_STATS
set total_points=(
  select T1.calc_points from 
  (SELECT user_pk, SUM(points) calc_points FROM activity_point_log
  GROUP BY user_pk) T1
  where T1.user_pk=ACTIVITY_POINT_STATS.user_pk
)

update activity_point_stats
set total_points=0
where total_points IS NULL

-- limit points
update ACTIVITY_POINT_STATS
set limit_points=(
  select T1.calc_points from 
  (SELECT user_pk, SUM(points) calc_points FROM activity_point_log
  WHERE TO_CHAR(ACTION_AT, 'YYYY-MM-DD') <= '2025-07-09'
  GROUP BY user_pk) T1
  where T1.user_pk=ACTIVITY_POINT_STATS.user_pk
)

update activity_point_stats
set limit_points=0
where limit_points IS NULL
