-- Converted from Oracle: 11_table_reservation.sql
-- Generated by tools/oracle2pg.py - review before running.

-- prefix
CREATE SEQUENCE IF NOT EXISTS reserve_prefix_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE reserve_prefix (
  prefix_pk BIGINT PRIMARY KEY,
  prefix_str VARCHAR(6) NOT NULL,
  suffix_str VARCHAR(4),
  start_no SMALLINT DEFAULT 0 NOT NULL,
  end_no SMALLINT DEFAULT 0 NOT NULL,
  reserve_source SMALLINT DEFAULT 0 NOT NULL,
  product_name VARCHAR(128) NOT NULL,
  description VARCHAR(4000),
  publish_num VARCHAR(24),
  normal_cnt SMALLINT DEFAULT 0,
  reward_cnt SMALLINT DEFAULT 0,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  disp_date TIMESTAMP,
  note VARCHAR(4000),
  summary VARCHAR(64),
  agency_ids VARCHAR(255),
  phone_pk BIGINT,
  mars_str VARCHAR(64),
  is_minus SMALLINT DEFAULT 1,
  is_private SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_reserve_prefix_phone_pk FOREIGN KEY (phone_pk) REFERENCES products(product_pk),
  CONSTRAINT chk_reserve_no_interval CHECK (end_no >= start_no),
  CONSTRAINT chk_reserve_prefix_period CHECK (end_date >= start_date)
);

COMMENT ON COLUMN reserve_prefix.prefix_str IS 'prefix string';
COMMENT ON COLUMN reserve_prefix.suffix_str IS 'suffix string';
COMMENT ON COLUMN reserve_prefix.start_no IS 'reservation start no';
COMMENT ON COLUMN reserve_prefix.end_no IS 'reservation end no';
COMMENT ON COLUMN reserve_prefix.reserve_source IS 'reserve source (0: eshop, 1: soft, 2: eprod register, 3: bonus, 4: credit, 5: lottery, 6: phone register, 7: agency soft appstore, 8: agency soft eprod, 9: agency sale eprod, 10: agency as eprod, 11: agency as phone)';
COMMENT ON COLUMN reserve_prefix.product_name IS 'product name to reserve';
COMMENT ON COLUMN reserve_prefix.description IS 'description';
COMMENT ON COLUMN reserve_prefix.publish_num IS 'publish approve BIGINT';
COMMENT ON COLUMN reserve_prefix.normal_cnt IS 'normal reserve count';
COMMENT ON COLUMN reserve_prefix.reward_cnt IS 'reward reserve count';
COMMENT ON COLUMN reserve_prefix.start_date IS 'start date of reservation';
COMMENT ON COLUMN reserve_prefix.end_date IS 'end date of reservation';
COMMENT ON COLUMN reserve_prefix.disp_date IS 'display date of reservation';
COMMENT ON COLUMN reserve_prefix.note IS 'comment';
COMMENT ON COLUMN reserve_prefix.summary IS 'short summary';
COMMENT ON COLUMN reserve_prefix.agency_ids IS 'comma separated phone_sale_agencies.agency_id';
COMMENT ON COLUMN reserve_prefix.phone_pk IS 'when reserve source is 6, products.product_pk';
COMMENT ON COLUMN reserve_prefix.mars_str IS 'when reserve source is 0, matched string with mars';
COMMENT ON COLUMN reserve_prefix.is_minus IS '0: dont apply minus point (lottery), 1: apply minus points';
COMMENT ON COLUMN reserve_prefix.is_private IS '0: public, 1: private';

ALTER TABLE reserve_prefix ALTER COLUMN prefix_pk SET DEFAULT nextval('reserve_prefix_s');
ALTER SEQUENCE reserve_prefix_s OWNED BY reserve_prefix.prefix_pk;

-- reserve users
CREATE SEQUENCE IF NOT EXISTS reserve_users_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE reserve_users (
  table_pk BIGINT PRIMARY KEY,
  prefix_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  reserve_cnt SMALLINT DEFAULT 0,
  reserve_type SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_reserve_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT uq_reserve_user_prefix_user UNIQUE (prefix_pk, user_pk)
);

COMMENT ON COLUMN reserve_users.prefix_pk IS 'reserve_prefix.prefix_pk';
COMMENT ON COLUMN reserve_users.user_pk IS 'users.user_pk';
COMMENT ON COLUMN reserve_users.reserve_cnt IS 'reserve avaliable count';
COMMENT ON COLUMN reserve_users.reserve_type IS '0: normal, 1: reward';
COMMENT ON COLUMN reserve_users.is_deleted IS 'soft delete flag';

ALTER TABLE reserve_users ALTER COLUMN table_pk SET DEFAULT nextval('reserve_users_s');
ALTER SEQUENCE reserve_users_s OWNED BY reserve_users.table_pk;

-- reserve log
CREATE SEQUENCE IF NOT EXISTS reserve_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE reserve_log (
  table_pk BIGINT PRIMARY KEY,
  prefix_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  reserve_name VARCHAR(50),
  id_card VARCHAR(50),
  phone_number VARCHAR(12),
  reserve_no SMALLINT,
  reserve_type SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  agency_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reserve_log_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_reserve_log_agency_id FOREIGN KEY (agency_id) REFERENCES phone_sale_agencies(agency_id),
  CONSTRAINT uq_reserve_log_prefix_no UNIQUE (prefix_pk, reserve_no)
);

COMMENT ON COLUMN reserve_log.prefix_pk IS 'reserve_prefix.prefix_pk';
COMMENT ON COLUMN reserve_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN reserve_log.reserve_name IS 'reserved user name';
COMMENT ON COLUMN reserve_log.id_card IS 'reserved id card';
COMMENT ON COLUMN reserve_log.phone_number IS 'reserved phone BIGINT';
COMMENT ON COLUMN reserve_log.reserve_no IS 'auto-generated reserve number (0 - 9999)';
COMMENT ON COLUMN reserve_log.reserve_type IS '0: normal, 1: reward';
COMMENT ON COLUMN reserve_log.status IS '0: pending, 1: reserved, 2: paid, 3: saled, 4: eshop error';
COMMENT ON COLUMN reserve_log.agency_id IS 'phone_sale_agencies.agency_id';

ALTER TABLE reserve_log ALTER COLUMN table_pk SET DEFAULT nextval('reserve_log_s');
ALTER SEQUENCE reserve_log_s OWNED BY reserve_log.table_pk;

-- reserve sms log
CREATE SEQUENCE IF NOT EXISTS reserve_sms_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE reserve_sms_log (
  table_pk BIGINT PRIMARY KEY,
  product_pk BIGINT NOT NULL,
  phone_imei VARCHAR(15) NOT NULL UNIQUE,
  reserve_name VARCHAR(50),
  id_card VARCHAR(50),
  phone_number VARCHAR(12),
  province_name VARCHAR(48),
  agency_id BIGINT,
  product_name VARCHAR(128) NOT NULL,
  status SMALLINT DEFAULT 0,
  reserve_code VARCHAR(17) UNIQUE,
  user_pk BIGINT,
  created_at TIMESTAMP,
  CONSTRAINT fk_reserve_sms_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk),
  CONSTRAINT fk_reserve_sms_agency_id FOREIGN KEY (agency_id) REFERENCES phone_sale_agencies(agency_id),
  CONSTRAINT fk_reserve_sms_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN reserve_sms_log.product_pk IS 'products.product_pk';
COMMENT ON COLUMN reserve_sms_log.phone_imei IS 'phone imei';
COMMENT ON COLUMN reserve_sms_log.reserve_name IS 'reserve name';
COMMENT ON COLUMN reserve_sms_log.id_card IS 'id card';
COMMENT ON COLUMN reserve_sms_log.phone_number IS 'phone BIGINT';
COMMENT ON COLUMN reserve_sms_log.province_name IS 'province name';
COMMENT ON COLUMN reserve_sms_log.agency_id IS 'phone_sale_agencies.agency_id';
COMMENT ON COLUMN reserve_sms_log.product_name IS 'reserve phone name';
COMMENT ON COLUMN reserve_sms_log.status IS '0: sms accept, 1: reserve pending, 2: sale finish';
COMMENT ON COLUMN reserve_sms_log.reserve_code IS 'reservation code';
COMMENT ON COLUMN reserve_sms_log.user_pk IS 'users.user_pk';

ALTER TABLE reserve_sms_log ALTER COLUMN table_pk SET DEFAULT nextval('reserve_sms_log_s');
ALTER SEQUENCE reserve_sms_log_s OWNED BY reserve_sms_log.table_pk;

-- reward log
CREATE SEQUENCE IF NOT EXISTS reward_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE reward_log (
  table_pk BIGINT PRIMARY KEY,
  prefix_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  money_value BIGINT,
  order_number BIGINT NOT NULL,
  qr_path VARCHAR(255),
  request_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  confirm_at TIMESTAMP
);

COMMENT ON COLUMN reward_log.prefix_pk IS 'reserve_prefix.prefix_pk';
COMMENT ON COLUMN reward_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN reward_log.money_value IS 'reward money value used for reservation';
COMMENT ON COLUMN reward_log.order_number IS 'order BIGINT from wallet server';
COMMENT ON COLUMN reward_log.qr_path IS 'url of generated QR';
COMMENT ON COLUMN reward_log.request_at IS 'request pay at';
COMMENT ON COLUMN reward_log.confirm_at IS 'confirm pay at';

ALTER TABLE reward_log ALTER COLUMN table_pk SET DEFAULT nextval('reward_log_s');
ALTER SEQUENCE reward_log_s OWNED BY reward_log.table_pk;

