-- Converted from Oracle: 13_table_products.sql
-- Generated by tools/oracle2pg.py - review before running.

-- product categories
CREATE SEQUENCE IF NOT EXISTS product_categories_s INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_categories (
  category_pk BIGINT PRIMARY KEY,
  category_name VARCHAR(64),
  node_value VARCHAR(64),
  parent_pk BIGINT,
  position SMALLINT DEFAULT 0,
  is_leaf SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN product_categories.category_name IS 'category name';
COMMENT ON COLUMN product_categories.node_value IS 'unique value representing node by reverse 2-chars';
COMMENT ON COLUMN product_categories.parent_pk IS 'product_categories.category_pk';
COMMENT ON COLUMN product_categories.position IS 'sort order';
COMMENT ON COLUMN product_categories.is_leaf IS '0: not leaf, 1: leaf';

ALTER TABLE product_categories ALTER COLUMN category_pk SET DEFAULT nextval('product_categories_s');
ALTER SEQUENCE product_categories_s OWNED BY product_categories.category_pk;

-- products
CREATE SEQUENCE IF NOT EXISTS products_s INCREMENT BY 3 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE products (
  product_pk BIGINT PRIMARY KEY,
  product_name VARCHAR(128),
  simple_name VARCHAR(64),
  category_pk BIGINT NOT NULL,
  root_pk BIGINT NOT NULL,
  image_url VARCHAR(255),
  price NUMERIC(8,1) DEFAULT 0,
  position SMALLINT DEFAULT 0,
  is_new SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_category_pk FOREIGN KEY (category_pk) REFERENCES product_categories(category_pk),
  CONSTRAINT fk_product_root_pk FOREIGN KEY (root_pk) REFERENCES product_categories(category_pk)
);

COMMENT ON COLUMN products.product_name IS 'product name';
COMMENT ON COLUMN products.simple_name IS 'product simple name';
COMMENT ON COLUMN products.category_pk IS 'product_categories.category_pk';
COMMENT ON COLUMN products.root_pk IS 'product_categories.category_pk, whose parent_pk is 0';
COMMENT ON COLUMN products.image_url IS 'image that shown on product list';
COMMENT ON COLUMN products.price IS 'price';
COMMENT ON COLUMN products.is_new IS '0: not new, 1: new';
COMMENT ON COLUMN products.status IS '0: pending, 1: approved';

ALTER TABLE products ALTER COLUMN product_pk SET DEFAULT nextval('products_s');
ALTER SEQUENCE products_s OWNED BY products.product_pk;

-- product images
CREATE SEQUENCE IF NOT EXISTS product_images_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_images (
  table_pk BIGINT PRIMARY KEY,
  product_pk BIGINT NOT NULL,
  image_type SMALLINT,
  image_url VARCHAR(255),
  image_ratio NUMERIC(7,4),
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_img_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk)
);

COMMENT ON COLUMN product_images.product_pk IS 'products.product_pk';
COMMENT ON COLUMN product_images.image_type IS '0: main, 1: intro';
COMMENT ON COLUMN product_images.image_url IS 'image that shown on product list';
COMMENT ON COLUMN product_images.image_ratio IS 'Aspect ratio of image width : height';
COMMENT ON COLUMN product_images.status IS '0: pending, 1: approved';

ALTER TABLE product_images ALTER COLUMN table_pk SET DEFAULT nextval('product_images_s');
ALTER SEQUENCE product_images_s OWNED BY product_images.table_pk;

-- product spec keys
CREATE SEQUENCE IF NOT EXISTS product_spec_keys_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_spec_keys (
  spec_pk BIGINT PRIMARY KEY,
  spec_name VARCHAR(64),
  spec_type SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN product_spec_keys.spec_name IS 'spec name';
COMMENT ON COLUMN product_spec_keys.spec_type IS '0: string, 1: textarea, 2: BIGINT';

ALTER TABLE product_spec_keys ALTER COLUMN spec_pk SET DEFAULT nextval('product_spec_keys_s');
ALTER SEQUENCE product_spec_keys_s OWNED BY product_spec_keys.spec_pk;

-- product spec values
CREATE SEQUENCE IF NOT EXISTS product_spec_values_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_spec_values (
  table_pk BIGINT PRIMARY KEY,
  product_pk BIGINT,
  spec_pk BIGINT,
  spec_value VARCHAR(255),
  position SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_prod_spec_val_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk),
  CONSTRAINT fk_prod_spec_val_spec_pk FOREIGN KEY (spec_pk) REFERENCES product_spec_keys(spec_pk),
  CONSTRAINT uq_product_spec_value UNIQUE (product_pk, spec_pk)
);

COMMENT ON COLUMN product_spec_values.product_pk IS 'products.product_pk';
COMMENT ON COLUMN product_spec_values.spec_pk IS 'product_spec_keys.spec_pk';
COMMENT ON COLUMN product_spec_values.spec_value IS 'spec value';

ALTER TABLE product_spec_values ALTER COLUMN table_pk SET DEFAULT nextval('product_spec_values_s');
ALTER SEQUENCE product_spec_values_s OWNED BY product_spec_values.table_pk;

-- product spec orders
CREATE SEQUENCE IF NOT EXISTS product_spec_orders_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_spec_orders (
  table_pk BIGINT PRIMARY KEY,
  root_pk BIGINT NOT NULL,
  spec_pk BIGINT NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_prod_spec_order_root_pk FOREIGN KEY (root_pk) REFERENCES product_categories(category_pk),
  CONSTRAINT fk_prod_spec_order_spec_pk FOREIGN KEY (spec_pk) REFERENCES product_spec_keys(spec_pk)
);

COMMENT ON COLUMN product_spec_orders.root_pk IS 'product_categories.category_pk';
COMMENT ON COLUMN product_spec_orders.spec_pk IS 'product_spec_keys.spec_pk';

ALTER TABLE product_spec_orders ALTER COLUMN table_pk SET DEFAULT nextval('product_spec_orders_s');
ALTER SEQUENCE product_spec_orders_s OWNED BY product_spec_orders.table_pk;

-- product models
CREATE SEQUENCE IF NOT EXISTS product_models_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE product_models (
  model_pk BIGINT PRIMARY KEY,
  product_pk BIGINT UNIQUE NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  reservable SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_prod_model_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk),
  CONSTRAINT fk_prod_model_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_prod_model_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN product_models.product_pk IS 'products.product_pk';
COMMENT ON COLUMN product_models.model_name IS 'product model name';
COMMENT ON COLUMN product_models.reservable IS '1: reservable new phone by registering this phone model';
COMMENT ON COLUMN product_models.is_deleted IS '0: not deleted, 1: deleted';

ALTER TABLE product_models ALTER COLUMN model_pk SET DEFAULT nextval('product_models_s');
ALTER SEQUENCE product_models_s OWNED BY product_models.model_pk;

-- register_point_types
CREATE SEQUENCE IF NOT EXISTS register_point_types_s INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE register_point_types (
  type_pk BIGINT PRIMARY KEY,
  product_pk BIGINT UNIQUE NOT NULL,
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_reg_point_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk),
  CONSTRAINT fk_reg_point_created_by FOREIGN KEY (created_by) REFERENCES managers(manager_pk),
  CONSTRAINT fk_reg_point_updated_by FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN register_point_types.product_pk IS 'products.product_pk';
COMMENT ON COLUMN register_point_types.points IS 'point to be achieved';

ALTER TABLE register_point_types ALTER COLUMN type_pk SET DEFAULT nextval('register_point_types_s');
ALTER SEQUENCE register_point_types_s OWNED BY register_point_types.type_pk;

-- register_phone_log
CREATE SEQUENCE IF NOT EXISTS register_phone_log_s INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE register_phone_log (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  product_pk BIGINT NOT NULL,
  points NUMERIC(8,1) DEFAULT 0 NOT NULL,
  phone_imei VARCHAR(20) NOT NULL,
  cid VARCHAR(12) NOT NULL,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reg_phone_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk)
);

COMMENT ON COLUMN register_phone_log.user_pk IS 'users.user_pk';
COMMENT ON COLUMN register_phone_log.product_pk IS 'products.product_pk';
COMMENT ON COLUMN register_phone_log.points IS 'point to be achieved';
COMMENT ON COLUMN register_phone_log.phone_imei IS 'phone imei';
COMMENT ON COLUMN register_phone_log.cid IS 'SIM CID';
COMMENT ON COLUMN register_phone_log.is_deleted IS '1: deleted';

ALTER TABLE register_phone_log ALTER COLUMN table_pk SET DEFAULT nextval('register_phone_log_s');
ALTER SEQUENCE register_phone_log_s OWNED BY register_phone_log.table_pk;

-- phone imei prefix
CREATE SEQUENCE IF NOT EXISTS phone_imei_prefix_s INCREMENT BY 10 MINVALUE 1000 MAXVALUE 9223372036854775807 START WITH 1000;

CREATE TABLE phone_imei_prefix (
  prefix_pk BIGINT PRIMARY KEY,
  product_pk BIGINT NOT NULL,
  prefix_str VARCHAR(15) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_phone_imei_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk)
);

COMMENT ON COLUMN phone_imei_prefix.product_pk IS 'products.product_pk';
COMMENT ON COLUMN phone_imei_prefix.prefix_str IS 'IMEI prefix';

ALTER TABLE phone_imei_prefix ALTER COLUMN prefix_pk SET DEFAULT nextval('phone_imei_prefix_s');
ALTER SEQUENCE phone_imei_prefix_s OWNED BY phone_imei_prefix.prefix_pk;

-- phone accessories
CREATE SEQUENCE IF NOT EXISTS phone_accessories_s INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE phone_accessories (
  accessory_pk BIGINT PRIMARY KEY,
  product_pk BIGINT NOT NULL,
  product_name VARCHAR(128),
  accessory_name VARCHAR(128),
  resource_price NUMERIC(6,2) DEFAULT 0,
  service_price NUMERIC(6,2) DEFAULT 0,
  allow_num VARCHAR(32),
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_phone_acc_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk),
  CONSTRAINT uq_phone_acc_prod_name UNIQUE (product_pk, accessory_name)
);

COMMENT ON COLUMN phone_accessories.product_pk IS 'products.product_pk';
COMMENT ON COLUMN phone_accessories.product_name IS 'products.simple_name';
COMMENT ON COLUMN phone_accessories.accessory_name IS 'accessory name';
COMMENT ON COLUMN phone_accessories.resource_price IS 'resource price';
COMMENT ON COLUMN phone_accessories.service_price IS 'service price';
COMMENT ON COLUMN phone_accessories.allow_num IS 'price allow BIGINT';
COMMENT ON COLUMN phone_accessories.is_deleted IS '1: deleted';

ALTER TABLE phone_accessories ALTER COLUMN accessory_pk SET DEFAULT nextval('phone_accessories_s');
ALTER SEQUENCE phone_accessories_s OWNED BY phone_accessories.accessory_pk;

-- phone changelog
CREATE SEQUENCE IF NOT EXISTS phone_changelog_s INCREMENT BY 2 MINVALUE 1000 MAXVALUE 9223372036854775807 START WITH 1000;

CREATE TABLE phone_changelog (
  table_pk BIGINT PRIMARY KEY,
  product_pk BIGINT NOT NULL,
  product_name VARCHAR(128),
  title VARCHAR(512),
  content TEXT,
  publish_num VARCHAR(128),
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_phone_log_product_pk FOREIGN KEY (product_pk) REFERENCES products(product_pk)
);

COMMENT ON COLUMN phone_changelog.product_pk IS 'products.product_pk';
COMMENT ON COLUMN phone_changelog.product_name IS 'products.simple_name';
COMMENT ON COLUMN phone_changelog.title IS 'title';
COMMENT ON COLUMN phone_changelog.content IS 'content';
COMMENT ON COLUMN phone_changelog.publish_num IS 'publish accept BIGINT';
COMMENT ON COLUMN phone_changelog.position IS 'position';
COMMENT ON COLUMN phone_changelog.is_deleted IS '1: deleted';

ALTER TABLE phone_changelog ALTER COLUMN table_pk SET DEFAULT nextval('phone_changelog_s');
ALTER SEQUENCE phone_changelog_s OWNED BY phone_changelog.table_pk;

