-- Converted from Oracle: 14_table_base.sql
-- Generated by tools/oracle2pg.py - review before running.

-- temp files
CREATE SEQUENCE IF NOT EXISTS temp_files_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE temp_files (
  table_pk BIGINT PRIMARY KEY,
  title VARCHAR(255),
  file_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN temp_files.title IS 'purpose of file upload, e.g. for eshop, or for mine';
COMMENT ON COLUMN temp_files.file_url IS 'uploaded file url';

ALTER TABLE temp_files ALTER COLUMN table_pk SET DEFAULT nextval('temp_files_s');
ALTER SEQUENCE temp_files_s OWNED BY temp_files.table_pk;

-- holidays
CREATE SEQUENCE IF NOT EXISTS holidays_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE holidays (
  table_pk BIGINT PRIMARY KEY,
  simple_date VARCHAR(5) NOT NULL,
  name VARCHAR(128),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN holidays.simple_date IS 'simple date of holiday, XX-XX format';
COMMENT ON COLUMN holidays.name IS 'name of holiday';

ALTER TABLE holidays ALTER COLUMN table_pk SET DEFAULT nextval('holidays_s');
ALTER SEQUENCE holidays_s OWNED BY holidays.table_pk;

-- company contacts
CREATE SEQUENCE IF NOT EXISTS company_contacts_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE company_contacts (
  contact_pk BIGINT PRIMARY KEY,
  contact_name VARCHAR(128) NOT NULL,
  phone_number VARCHAR(64) NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN company_contacts.contact_name IS 'contact name';
COMMENT ON COLUMN company_contacts.phone_number IS 'phone BIGINT';

ALTER TABLE company_contacts ALTER COLUMN contact_pk SET DEFAULT nextval('company_contacts_s');
ALTER SEQUENCE company_contacts_s OWNED BY company_contacts.contact_pk;

