-- Converted from Oracle: 15_table_agency.sql
-- Generated by tools/oracle2pg.py - review before running.

-- phone agencies
CREATE SEQUENCE IF NOT EXISTS phone_agencies_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE phone_agencies (
  agency_pk BIGINT PRIMARY KEY,
  agency_name VARCHAR(255) NOT NULL,
  phone_numbers VARCHAR(128) NOT NULL,
  business VARCHAR(8),
  location_pk BIGINT,
  location_more VARCHAR(255),
  location_environs VARCHAR(255),
  shmap_pos VARCHAR(64),
  agency_rating NUMERIC(5,2) DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_p_agency_location_pk FOREIGN KEY (location_pk) REFERENCES locations(location_pk)
);

ALTER TABLE phone_agencies ALTER COLUMN agency_pk SET DEFAULT nextval('phone_agencies_s');
ALTER SEQUENCE phone_agencies_s OWNED BY phone_agencies.agency_pk;

-- eprod agencies
CREATE SEQUENCE IF NOT EXISTS eprod_agencies_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE eprod_agencies (
  agency_pk BIGINT PRIMARY KEY,
  agency_name VARCHAR(255) NOT NULL,
  phone_numbers VARCHAR(128) NOT NULL,
  business VARCHAR(8),
  location_pk BIGINT,
  location_more VARCHAR(255),
  location_environs VARCHAR(255),
  shmap_pos VARCHAR(64),
  agency_rating NUMERIC(5,2) DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_e_agency_location_pk FOREIGN KEY (location_pk) REFERENCES locations(location_pk)
);

ALTER TABLE eprod_agencies ALTER COLUMN agency_pk SET DEFAULT nextval('eprod_agencies_s');
ALTER SEQUENCE eprod_agencies_s OWNED BY eprod_agencies.agency_pk;

-- phone sale agencies (for phone book)
CREATE TABLE phone_sale_agencies (
  agency_id BIGINT UNIQUE NOT NULL,
  agency_name VARCHAR(255) NOT NULL,
  agency_superior VARCHAR(128),
  location_name VARCHAR(255),
  location_detail VARCHAR(255),
  status SMALLINT DEFAULT 1,
  is_deleted SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  created_at TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

