-- Converted from Oracle: 16_table_weather.sql
-- Generated by tools/oracle2pg.py - review before running.

-- weather stations
CREATE TABLE weather_stations (
  area_code BIGINT PRIMARY KEY,
  area_name VARCHAR(64) NOT NULL,
  current_order SMALLINT DEFAULT 999,
  short_order SMALLINT DEFAULT 999,
  middle_order SMALLINT DEFAULT 999,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- weather current
CREATE TABLE weather_current (
  id BIGINT PRIMARY KEY,
  area_code BIGINT NOT NULL,
  temperature NUMERIC(3,1) DEFAULT 0,
  humidity NUMERIC(3,1) DEFAULT 0,
  wind VARCHAR(128),
  cloud VARCHAR(256),
  symbol SMALLINT DEFAULT 0,
  symbol_ SMALLINT DEFAULT 0,
  pressure INTEGER DEFAULT 0,
  sunshine NUMERIC(5,1) DEFAULT 0,
  visidist VARCHAR(50),
  updatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_weather_current_area_code FOREIGN KEY (area_code) REFERENCES weather_stations(area_code)
);

CREATE INDEX idx_weather_current_area_code ON weather_current (area_code);

-- weather short
CREATE TABLE weather_short (
  id BIGINT PRIMARY KEY,
  area_code BIGINT NOT NULL,
  wind1 VARCHAR(128),
  cloud1 VARCHAR(256),
  symbol1 SMALLINT DEFAULT 0,
  symbol_night1 SMALLINT DEFAULT 0,
  symbol1_ SMALLINT DEFAULT 0,
  symbol_night1_ SMALLINT DEFAULT 0,
  templ1 NUMERIC(3,0) DEFAULT 0,
  temph1 NUMERIC(3,0) DEFAULT 0,
  wind2 VARCHAR(128),
  cloud2 VARCHAR(256),
  symbol2 SMALLINT DEFAULT 0,
  symbol_night2 SMALLINT DEFAULT 0,
  symbol2_ SMALLINT DEFAULT 0,
  symbol_night2_ SMALLINT DEFAULT 0,
  templ2 NUMERIC(3,0) DEFAULT 0,
  temph2 NUMERIC(3,0) DEFAULT 0,
  othernote VARCHAR(256),
  enabled VARCHAR(1) default 'Y',
  updatetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_weather_short_area_code FOREIGN KEY (area_code) REFERENCES weather_stations(area_code),
  CONSTRAINT ck_weather_short_enabled CHECK (enabled IN ('Y', 'N'))
);

CREATE INDEX idx_weather_short_area_code ON weather_short (area_code);
