-- Converted from Oracle: 17_table_premium.sql
-- Generated by tools/oracle2pg.py - review before running.

-- premium services
CREATE SEQUENCE IF NOT EXISTS premium_services_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_services (
  service_pk BIGINT PRIMARY KEY,
  service_name VARCHAR(255) NOT NULL,
  service_description VARCHAR(4000),
  publish_num VARCHAR(24),
  lottery_start_date TIMESTAMP,
  lottery_end_date TIMESTAMP,
  follow_start_date TIMESTAMP,
  follow_end_date TIMESTAMP,
  service_disp_date TIMESTAMP,
  service_type SMALLINT DEFAULT 0,
  image_url VARCHAR(255),
  image_ratio NUMERIC(7,4) DEFAULT 0,
  image_status SMALLINT DEFAULT 0,
  service_note VARCHAR(4000),
  goods_description VARCHAR(4000),
  is_deleted SMALLINT DEFAULT 0,
  is_test SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN premium_services.service_name IS 'premium service name';
COMMENT ON COLUMN premium_services.service_description IS 'premium service description to be shown for user';
COMMENT ON COLUMN premium_services.publish_num IS 'publish approve BIGINT';
COMMENT ON COLUMN premium_services.lottery_start_date IS 'start date of lottery';
COMMENT ON COLUMN premium_services.lottery_end_date IS 'end date of lottery';
COMMENT ON COLUMN premium_services.follow_start_date IS 'start date of setting delivery address for followings';
COMMENT ON COLUMN premium_services.follow_end_date IS 'end date of setting delivery address for followings';
COMMENT ON COLUMN premium_services.service_disp_date IS 'display date of service';
COMMENT ON COLUMN premium_services.service_type IS '0: 2025 yearend service, 1: lottery, 2: 2026.3.8 service, 3: puzzle';
COMMENT ON COLUMN premium_services.image_url IS 'image that shown on premium service page';
COMMENT ON COLUMN premium_services.image_ratio IS 'Aspect ratio of image width : height';
COMMENT ON COLUMN premium_services.image_status IS '0: pending, 1: approved';
COMMENT ON COLUMN premium_services.service_note IS 'premium service note';
COMMENT ON COLUMN premium_services.goods_description IS 'premium goods description with publish accept code';
COMMENT ON COLUMN premium_services.is_deleted IS '1: deleted, 0: none';
COMMENT ON COLUMN premium_services.is_test IS 'test flag, 1: for test';

ALTER TABLE premium_services ALTER COLUMN service_pk SET DEFAULT nextval('premium_services_s');
ALTER SEQUENCE premium_services_s OWNED BY premium_services.service_pk;

-- premium goods
CREATE SEQUENCE IF NOT EXISTS premium_goods_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_goods (
  goods_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  goods_name VARCHAR(255) NOT NULL,
  goods_type SMALLINT DEFAULT 0 NOT NULL,
  price NUMERIC(8,2) DEFAULT 0,
  points NUMERIC(11,2) DEFAULT 0,
  related_pk BIGINT,
  class_pk BIGINT,
  real_count SMALLINT DEFAULT 0,
  fake_count SMALLINT DEFAULT 0,
  goods_note VARCHAR(4000),
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_premium_goods_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_premium_goods_class_pk FOREIGN KEY (class_pk) REFERENCES premium_user_class(class_pk),
  CONSTRAINT uq_premium_service_goods UNIQUE (service_pk, class_pk, goods_name)
);

COMMENT ON COLUMN premium_goods.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_goods.goods_name IS 'goods name';
COMMENT ON COLUMN premium_goods.goods_type IS 'goods type, 1: deliverable material goods, 2: non-deliverable material goods, 3: e-product reserve coupon, 4: immaterial points, 5: immaterial commerce points, 6: immaterial soft points, 7: immaterial activity points, 8: immaterial free app, 9: immaterial e-product guarantee, 10: phone free repair coupon';
COMMENT ON COLUMN premium_goods.price IS 'goods price, can be used for sort';
COMMENT ON COLUMN premium_goods.points IS 'immaterial points including commerce/soft/activity points';
COMMENT ON COLUMN premium_goods.related_pk IS 'related pk for certain material goods, can be eshop.goods_pk, products.product_pk';
COMMENT ON COLUMN premium_goods.class_pk IS 'premium_user_class.class_pk';
COMMENT ON COLUMN premium_goods.real_count IS 'real count';
COMMENT ON COLUMN premium_goods.fake_count IS 'fake count';
COMMENT ON COLUMN premium_goods.goods_note IS 'goods note';
COMMENT ON COLUMN premium_goods.is_deleted IS '1: deleted, 0: none';

ALTER TABLE premium_goods ALTER COLUMN goods_pk SET DEFAULT nextval('premium_goods_s');
ALTER SEQUENCE premium_goods_s OWNED BY premium_goods.goods_pk;

-- lottery numbers (for 2025 yearend premium)
CREATE SEQUENCE IF NOT EXISTS lottery_numbers_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE lottery_numbers (
  lottery_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  lottery_number INTEGER DEFAULT 0 NOT NULL,
  goods_pk BIGINT,
  lottery_at TIMESTAMP,
  award_at TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lottery_number_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_lottery_number_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_lottery_number_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT uq_lottery_service_user_no UNIQUE (service_pk, lottery_number)
);

COMMENT ON COLUMN lottery_numbers.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN lottery_numbers.user_pk IS 'users.user_pk';
COMMENT ON COLUMN lottery_numbers.lottery_number IS 'lottery BIGINT';
COMMENT ON COLUMN lottery_numbers.goods_pk IS 'premium_goods.goods_pk, elected by manager before starting lottery';
COMMENT ON COLUMN lottery_numbers.lottery_at IS 'lottery BIGINT selection time by user';
COMMENT ON COLUMN lottery_numbers.award_at IS 'award time by manager or user';
COMMENT ON COLUMN lottery_numbers.is_deleted IS '1: deleted, 0: none';

ALTER TABLE lottery_numbers ALTER COLUMN lottery_pk SET DEFAULT nextval('lottery_numbers_s');
ALTER SEQUENCE lottery_numbers_s OWNED BY lottery_numbers.lottery_pk;

-- lottery remain numbers
CREATE SEQUENCE IF NOT EXISTS lottery_remains_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE lottery_remains (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  lottery_number INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lottery_remain_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT uq_lottery_service_number UNIQUE (service_pk, lottery_number)
);

COMMENT ON COLUMN lottery_remains.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN lottery_remains.lottery_number IS 'lottery BIGINT';

ALTER TABLE lottery_remains ALTER COLUMN table_pk SET DEFAULT nextval('lottery_remains_s');
ALTER SEQUENCE lottery_remains_s OWNED BY lottery_remains.table_pk;

-- lottery candidates
CREATE SEQUENCE IF NOT EXISTS lottery_candidates_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE lottery_candidates (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  class_pk BIGINT,
  lottery_count SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lottery_cand_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_lottery_cand_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_lottery_cand_class_pk FOREIGN KEY (class_pk) REFERENCES premium_user_class(class_pk),
  CONSTRAINT uq_lottery_candidates UNIQUE (service_pk, user_pk, class_pk)
);

COMMENT ON COLUMN lottery_candidates.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN lottery_candidates.user_pk IS 'users.user_pk';
COMMENT ON COLUMN lottery_candidates.class_pk IS 'premium_user_class.class_pk';
COMMENT ON COLUMN lottery_candidates.lottery_count IS 'available lottery count';
COMMENT ON COLUMN lottery_candidates.is_deleted IS '1: deleted, 0: none';

ALTER TABLE lottery_candidates ALTER COLUMN table_pk SET DEFAULT nextval('lottery_candidates_s');
ALTER SEQUENCE lottery_candidates_s OWNED BY lottery_candidates.table_pk;

-- lottery numbers
CREATE SEQUENCE IF NOT EXISTS lottery_submits_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE lottery_submits (
  lottery_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  class_pk BIGINT NOT NULL,
  lottery_number INTEGER DEFAULT 0 NOT NULL,
  goods_pk BIGINT,
  lottery_at TIMESTAMP,
  award_at TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lottery_submit_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_lottery_submit_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_lottery_submit_class_pk FOREIGN KEY (class_pk) REFERENCES premium_user_class(class_pk),
  CONSTRAINT fk_lottery_submit_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT uq_lottery_submits UNIQUE (service_pk, lottery_number)
);

COMMENT ON COLUMN lottery_submits.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN lottery_submits.user_pk IS 'users.user_pk';
COMMENT ON COLUMN lottery_submits.class_pk IS 'premium_user_class.class_pk';
COMMENT ON COLUMN lottery_submits.lottery_number IS 'lottery BIGINT';
COMMENT ON COLUMN lottery_submits.goods_pk IS 'premium_goods.goods_pk, elected by manager';
COMMENT ON COLUMN lottery_submits.lottery_at IS 'lottery BIGINT selection time by user';
COMMENT ON COLUMN lottery_submits.award_at IS 'award time by manager or user';
COMMENT ON COLUMN lottery_submits.is_deleted IS '1: deleted, 0: none';

ALTER TABLE lottery_submits ALTER COLUMN lottery_pk SET DEFAULT nextval('lottery_submits_s');
ALTER SEQUENCE lottery_submits_s OWNED BY lottery_submits.lottery_pk;

-- premium point awards
CREATE SEQUENCE IF NOT EXISTS premium_point_awards_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_point_awards (
  table_pk BIGINT PRIMARY KEY,
  lottery_pk BIGINT NOT NULL UNIQUE,
  goods_pk BIGINT NOT NULL,
  points NUMERIC(8,2) DEFAULT 0,
  target_id VARCHAR(64) NOT NULL,
  related_pk BIGINT,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_premium_point_lottery_pk FOREIGN KEY (lottery_pk) REFERENCES lottery_numbers(lottery_pk),
  CONSTRAINT fk_premium_point_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk)
);

COMMENT ON COLUMN premium_point_awards.lottery_pk IS 'lottery_numbers.lottery_pk';
COMMENT ON COLUMN premium_point_awards.goods_pk IS 'premium_goods.goods_pk';
COMMENT ON COLUMN premium_point_awards.points IS 'immaterial points specified by premium_goods.points';
COMMENT ON COLUMN premium_point_awards.target_id IS 'target id to be charged, can be eshop card BIGINT, appstore id, pid';
COMMENT ON COLUMN premium_point_awards.related_pk IS 'transaction pk of each system after charged';
COMMENT ON COLUMN premium_point_awards.status IS '0: pending, 1: success, 2: fail';

ALTER TABLE premium_point_awards ALTER COLUMN table_pk SET DEFAULT nextval('premium_point_awards_s');
ALTER SEQUENCE premium_point_awards_s OWNED BY premium_point_awards.table_pk;

-- premium user values
CREATE SEQUENCE IF NOT EXISTS premium_user_values_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_user_values (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  user_value NUMERIC(11,3) DEFAULT 0 NOT NULL,
  commerce_value NUMERIC(11,2) DEFAULT 0 NOT NULL,
  exp_value NUMERIC(11,2) DEFAULT 0 NOT NULL,
  soft_points NUMERIC(11,3) DEFAULT 0 NOT NULL,
  phone_reg_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  eprod_reg_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  activity_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  class_name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_premium_val_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_premium_val_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT uq_premium_service_user_pk UNIQUE (service_pk, user_pk)
);

COMMENT ON COLUMN premium_user_values.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_user_values.user_pk IS 'users.user_pk';
COMMENT ON COLUMN premium_user_values.user_value IS 'integrated value calculated by service formula (specified on note)';
COMMENT ON COLUMN premium_user_values.commerce_value IS 'accumulated commerce value of eshop';
COMMENT ON COLUMN premium_user_values.exp_value IS 'accumulated experience value of eshop';
COMMENT ON COLUMN premium_user_values.soft_points IS 'accumulated soft points (= appstore point + bmedia point + karaoke point)';
COMMENT ON COLUMN premium_user_values.phone_reg_points IS 'accumulated phone register points';
COMMENT ON COLUMN premium_user_values.eprod_reg_points IS 'accumulated eprod register points';
COMMENT ON COLUMN premium_user_values.activity_points IS 'accumulated activity points';
COMMENT ON COLUMN premium_user_values.class_name IS 'premium_user_class.class_name, for avoid loading speed by joining';

ALTER TABLE premium_user_values ALTER COLUMN table_pk SET DEFAULT nextval('premium_user_values_s');
ALTER SEQUENCE premium_user_values_s OWNED BY premium_user_values.table_pk;

-- premium user class
CREATE SEQUENCE IF NOT EXISTS premium_user_class_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_user_class (
  class_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  class_name VARCHAR(64) NOT NULL,
  start_value NUMERIC(11,3) DEFAULT 0 NOT NULL,
  end_value NUMERIC(11,3) DEFAULT 0,
  lottery_min_num INTEGER DEFAULT 0,
  lottery_max_num INTEGER DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_premium_class_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT uq_premium_class_service_name UNIQUE (service_pk, class_name)
);

COMMENT ON COLUMN premium_user_class.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_user_class.class_name IS 'user class name';
COMMENT ON COLUMN premium_user_class.start_value IS 'min value for this class';
COMMENT ON COLUMN premium_user_class.end_value IS 'max value for this class (not included), if NULL, no end limit';
COMMENT ON COLUMN premium_user_class.lottery_min_num IS 'min lottery BIGINT for this class';
COMMENT ON COLUMN premium_user_class.lottery_max_num IS 'max lottery BIGINT for this class (included)';
COMMENT ON COLUMN premium_user_class.is_deleted IS '1: deleted, 0: none';

ALTER TABLE premium_user_class ALTER COLUMN class_pk SET DEFAULT nextval('premium_user_class_s');
ALTER SEQUENCE premium_user_class_s OWNED BY premium_user_class.class_pk;

-- user delivery address
CREATE SEQUENCE IF NOT EXISTS user_delivery_address_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE user_delivery_address (
  delivery_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  receptionist VARCHAR(64),
  location_pk BIGINT NOT NULL,
  location_more VARCHAR(255),
  location_environs VARCHAR(255),
  phone_numbers VARCHAR(128) NOT NULL,
  id_card VARCHAR(50),
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_delivery_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_user_delivery_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_user_delivery_location_pk FOREIGN KEY (location_pk) REFERENCES locations(location_pk),
  CONSTRAINT uq_user_delivery_svc_user_pk UNIQUE (service_pk, user_pk)
);

ALTER TABLE user_delivery_address ALTER COLUMN delivery_pk SET DEFAULT nextval('user_delivery_address_s');
ALTER SEQUENCE user_delivery_address_s OWNED BY user_delivery_address.delivery_pk;

-- premium material deliveries
CREATE SEQUENCE IF NOT EXISTS premium_material_deliveries_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_material_deliveries (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  lottery_number INTEGER DEFAULT 0 NOT NULL,
  goods_pk BIGINT NOT NULL,
  delivery_pk BIGINT NOT NULL,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_material_deliver_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_material_deliver_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_material_deliver_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT fk_material_deliver_addr_pk FOREIGN KEY (delivery_pk) REFERENCES user_delivery_address(delivery_pk),
  CONSTRAINT uq_mat_deliver_svc_user_pk UNIQUE (service_pk, user_pk),
  CONSTRAINT uq_mat_deliver_svc_number UNIQUE (service_pk, lottery_number)
);

COMMENT ON COLUMN premium_material_deliveries.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_material_deliveries.user_pk IS 'users.user_pk';
COMMENT ON COLUMN premium_material_deliveries.lottery_number IS 'lottery_numbers.lottery_number';
COMMENT ON COLUMN premium_material_deliveries.goods_pk IS 'premium_goods.goods_pk';
COMMENT ON COLUMN premium_material_deliveries.delivery_pk IS 'user_delivery_address.delivery_pk';
COMMENT ON COLUMN premium_material_deliveries.status IS '0: pending, 1: delivered, 2: delivering';

ALTER TABLE premium_material_deliveries ALTER COLUMN table_pk SET DEFAULT nextval('premium_material_deliveries_s');
ALTER SEQUENCE premium_material_deliveries_s OWNED BY premium_material_deliveries.table_pk;

-- premium material agencies
CREATE SEQUENCE IF NOT EXISTS premium_material_agencies_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_material_agencies (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  lottery_number INTEGER DEFAULT 0 NOT NULL,
  goods_pk BIGINT NOT NULL,
  id_name VARCHAR(36),
  id_card VARCHAR(36),
  phone_number VARCHAR(12) NOT NULL,
  agency_pk BIGINT,
  status SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_material_agency_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_material_agency_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_material_agency_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT uq_mat_agency_svc_user_pk UNIQUE (service_pk, user_pk),
  CONSTRAINT uq_mat_agency_svc_number UNIQUE (service_pk, lottery_number)
);

COMMENT ON COLUMN premium_material_agencies.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_material_agencies.user_pk IS 'users.user_pk';
COMMENT ON COLUMN premium_material_agencies.lottery_number IS 'lottery_numbers.lottery_number';
COMMENT ON COLUMN premium_material_agencies.goods_pk IS 'premium_goods.goods_pk';
COMMENT ON COLUMN premium_material_agencies.id_name IS 'name on id card for verification';
COMMENT ON COLUMN premium_material_agencies.id_card IS 'BIGINT on id card for verification';
COMMENT ON COLUMN premium_material_agencies.phone_number IS 'phone BIGINT for verification';
COMMENT ON COLUMN premium_material_agencies.agency_pk IS '';
COMMENT ON COLUMN premium_material_agencies.status IS '0: pending, 1: delivered';

ALTER TABLE premium_material_agencies ALTER COLUMN table_pk SET DEFAULT nextval('premium_material_agencies_s');
ALTER SEQUENCE premium_material_agencies_s OWNED BY premium_material_agencies.table_pk;

-- integrated user class
CREATE SEQUENCE IF NOT EXISTS integrated_user_class_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE integrated_user_class (
  class_pk BIGINT PRIMARY KEY,
  class_level SMALLINT DEFAULT 0 NOT NULL UNIQUE,
  class_name VARCHAR(64) NOT NULL UNIQUE,
  start_value NUMERIC(11,3) DEFAULT 0 NOT NULL,
  end_value NUMERIC(11,3) DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN integrated_user_class.class_level IS 'user class level (0, 1, 2, 3)';
COMMENT ON COLUMN integrated_user_class.class_name IS 'user class name';
COMMENT ON COLUMN integrated_user_class.start_value IS 'min value for this class';
COMMENT ON COLUMN integrated_user_class.end_value IS 'max value for this class (not included), if NULL, no end limit';
COMMENT ON COLUMN integrated_user_class.is_deleted IS '1: deleted, 0: none';

ALTER TABLE integrated_user_class ALTER COLUMN class_pk SET DEFAULT nextval('integrated_user_class_s');
ALTER SEQUENCE integrated_user_class_s OWNED BY integrated_user_class.class_pk;

-- integrated user values
CREATE SEQUENCE IF NOT EXISTS integrated_user_values_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE integrated_user_values (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL UNIQUE,
  user_value NUMERIC(11,3) DEFAULT 0 NOT NULL,
  commerce_value NUMERIC(11,2) DEFAULT 0 NOT NULL,
  exp_value NUMERIC(11,2) DEFAULT 0 NOT NULL,
  soft_points NUMERIC(11,3) DEFAULT 0 NOT NULL,
  phone_reg_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  eprod_reg_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  activity_points NUMERIC(11,1) DEFAULT 0 NOT NULL,
  class_name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_integrated_val_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk)
);

COMMENT ON COLUMN integrated_user_values.user_pk IS 'users.user_pk';
COMMENT ON COLUMN integrated_user_values.user_value IS 'integrated value calculated by integrate formula';
COMMENT ON COLUMN integrated_user_values.commerce_value IS 'accumulated commerce value of eshop';
COMMENT ON COLUMN integrated_user_values.exp_value IS 'accumulated experience value of eshop';
COMMENT ON COLUMN integrated_user_values.soft_points IS 'accumulated soft points (= appstore point + bmedia point + karaoke point)';
COMMENT ON COLUMN integrated_user_values.phone_reg_points IS 'accumulated phone register points';
COMMENT ON COLUMN integrated_user_values.eprod_reg_points IS 'accumulated eprod register points';
COMMENT ON COLUMN integrated_user_values.activity_points IS 'accumulated activity points';
COMMENT ON COLUMN integrated_user_values.class_name IS 'integrated_user_class.class_name, for avoid loading speed by joining';

ALTER TABLE integrated_user_values ALTER COLUMN table_pk SET DEFAULT nextval('integrated_user_values_s');
ALTER SEQUENCE integrated_user_values_s OWNED BY integrated_user_values.table_pk;

-- premium discussions
CREATE SEQUENCE IF NOT EXISTS premium_discuss_awards_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_discuss_awards (
  award_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  class_pk BIGINT NOT NULL,
  goods_pk BIGINT NOT NULL,
  award_at TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_discuss_award_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_discuss_award_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_discuss_award_class_pk FOREIGN KEY (class_pk) REFERENCES premium_user_class(class_pk),
  CONSTRAINT fk_discuss_award_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT fk_discuss_award_admin_pk FOREIGN KEY (updated_by) REFERENCES managers(manager_pk)
);

COMMENT ON COLUMN premium_discuss_awards.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN premium_discuss_awards.user_pk IS 'users.user_pk';
COMMENT ON COLUMN premium_discuss_awards.class_pk IS 'premium_user_class.class_pk';
COMMENT ON COLUMN premium_discuss_awards.goods_pk IS 'premium_goods.goods_pk';
COMMENT ON COLUMN premium_discuss_awards.award_at IS 'award time by manager or user';
COMMENT ON COLUMN premium_discuss_awards.is_deleted IS '1: deleted, 0: none';

ALTER TABLE premium_discuss_awards ALTER COLUMN award_pk SET DEFAULT nextval('premium_discuss_awards_s');
ALTER SEQUENCE premium_discuss_awards_s OWNED BY premium_discuss_awards.award_pk;

-- premium receptions
CREATE SEQUENCE IF NOT EXISTS premium_receptions_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE premium_receptions (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  related_pk BIGINT,
  receptionist VARCHAR(64) NOT NULL,
  location_pk BIGINT,
  location_more VARCHAR(255),
  location_environs VARCHAR(255),
  phone_numbers VARCHAR(128) NOT NULL,
  id_card VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_premium_recepts_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_premium_recepts_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_premium_recepts_location_pk FOREIGN KEY (location_pk) REFERENCES locations(location_pk),
  CONSTRAINT uq_premium_recepts_fields UNIQUE (service_pk, user_pk, related_pk)
);

ALTER TABLE premium_receptions ALTER COLUMN table_pk SET DEFAULT nextval('premium_receptions_s');
ALTER SEQUENCE premium_receptions_s OWNED BY premium_receptions.table_pk;

-- womens day premium service by surveys
CREATE TABLE premium_women_survey_stats (
  choice_pk BIGINT PRIMARY KEY,
  question_pk BIGINT NOT NULL,
  count BIGINT DEFAULT 0 NOT NULL,
  points NUMERIC(4,1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_women_survey_choice_pk FOREIGN KEY (choice_pk) REFERENCES survey_choices(choice_pk),
  CONSTRAINT fk_women_survey_question_pk FOREIGN KEY (question_pk) REFERENCES survey_questions(question_pk)
);

COMMENT ON COLUMN premium_women_survey_stats.choice_pk IS 'survey_choices.choice_pk';
COMMENT ON COLUMN premium_women_survey_stats.question_pk IS 'survey_questions.question_pk';
COMMENT ON COLUMN premium_women_survey_stats.count IS 'survey response stats count';
COMMENT ON COLUMN premium_women_survey_stats.points IS 'survey response points for womens day';

-- puzzle questions
CREATE SEQUENCE IF NOT EXISTS puzzle_questions_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE puzzle_questions (
  question_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  question_text VARCHAR(1024) NOT NULL,
  question_type SMALLINT DEFAULT 0,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  publish_num VARCHAR(24),
  notice_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_puzz_quz_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk)
);

COMMENT ON COLUMN puzzle_questions.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN puzzle_questions.question_text IS 'text of the puzzle question';
COMMENT ON COLUMN puzzle_questions.question_type IS '0: single-choice, only single-choice for puzzle';
COMMENT ON COLUMN puzzle_questions.position IS 'sort order';
COMMENT ON COLUMN puzzle_questions.publish_num IS 'publish approve BIGINT';
COMMENT ON COLUMN puzzle_questions.notice_at IS 'question display time';

ALTER TABLE puzzle_questions ALTER COLUMN question_pk SET DEFAULT nextval('puzzle_questions_s');
ALTER SEQUENCE puzzle_questions_s OWNED BY puzzle_questions.question_pk;

-- puzzle choices
CREATE SEQUENCE IF NOT EXISTS puzzle_choices_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE puzzle_choices (
  choice_pk BIGINT PRIMARY KEY,
  question_pk BIGINT NOT NULL,
  choice_text VARCHAR(255) NOT NULL,
  position SMALLINT DEFAULT 0,
  is_correct SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_puzz_c_quz_pk FOREIGN KEY (question_pk) REFERENCES puzzle_questions(question_pk)
);

COMMENT ON COLUMN puzzle_choices.question_pk IS 'puzzle_questions.question_pk';
COMMENT ON COLUMN puzzle_choices.choice_text IS 'choice text';
COMMENT ON COLUMN puzzle_choices.position IS 'sort order';
COMMENT ON COLUMN puzzle_choices.is_correct IS '1: correct choice';

ALTER TABLE puzzle_choices ALTER COLUMN choice_pk SET DEFAULT nextval('puzzle_choices_s');
ALTER SEQUENCE puzzle_choices_s OWNED BY puzzle_choices.choice_pk;

-- puzzle responses
CREATE SEQUENCE IF NOT EXISTS puzzle_responses_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE puzzle_responses (
  response_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  question_pk BIGINT NOT NULL,
  choice_pk BIGINT NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_puzz_resp_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_puzz_resp_quz_pk FOREIGN KEY (question_pk) REFERENCES puzzle_questions(question_pk),
  CONSTRAINT fk_puzz_resp_choice FOREIGN KEY (choice_pk) REFERENCES puzzle_choices(choice_pk),
  CONSTRAINT uq_puzz_q_c_user UNIQUE (user_pk, question_pk, choice_pk)
);

COMMENT ON COLUMN puzzle_responses.user_pk IS 'users.user_pk';
COMMENT ON COLUMN puzzle_responses.question_pk IS 'puzzle_questions.question_pk';
COMMENT ON COLUMN puzzle_responses.choice_pk IS 'puzzle_choices.choice_pk';
COMMENT ON COLUMN puzzle_responses.action_at IS 'response time';

ALTER TABLE puzzle_responses ALTER COLUMN response_pk SET DEFAULT nextval('puzzle_responses_s');
ALTER SEQUENCE puzzle_responses_s OWNED BY puzzle_responses.response_pk;

-- puzzle awards
CREATE SEQUENCE IF NOT EXISTS puzzle_awards_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE puzzle_awards (
  award_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  class_pk BIGINT NOT NULL,
  goods_pk BIGINT,
  award_at TIMESTAMP,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_puzz_award_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_puzz_award_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_puzz_award_class_pk FOREIGN KEY (class_pk) REFERENCES premium_user_class(class_pk),
  CONSTRAINT fk_puzz_award_goods_pk FOREIGN KEY (goods_pk) REFERENCES premium_goods(goods_pk),
  CONSTRAINT fk_puzz_award_admin_pk FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT uq_puzz_awards UNIQUE (service_pk, user_pk, class_pk)
);

COMMENT ON COLUMN puzzle_awards.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN puzzle_awards.user_pk IS 'users.user_pk';
COMMENT ON COLUMN puzzle_awards.class_pk IS 'premium_user_class.class_pk';
COMMENT ON COLUMN puzzle_awards.goods_pk IS 'premium_goods.goods_pk, elected by manager';
COMMENT ON COLUMN puzzle_awards.award_at IS 'award time by manager or user';
COMMENT ON COLUMN puzzle_awards.is_deleted IS '1: deleted, 0: none';

ALTER TABLE puzzle_awards ALTER COLUMN award_pk SET DEFAULT nextval('puzzle_awards_s');
ALTER SEQUENCE puzzle_awards_s OWNED BY puzzle_awards.award_pk;

CREATE SEQUENCE IF NOT EXISTS puzzle_bonus_s INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100000;

CREATE TABLE puzzle_bonus (
  table_pk BIGINT PRIMARY KEY,
  service_pk BIGINT NOT NULL,
  user_pk BIGINT NOT NULL,
  points NUMERIC(8,3) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT,
  CONSTRAINT fk_puzz_bonus_service_pk FOREIGN KEY (service_pk) REFERENCES premium_services(service_pk),
  CONSTRAINT fk_puzz_bonus_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_puzz_bonus_admin_pk FOREIGN KEY (updated_by) REFERENCES managers(manager_pk),
  CONSTRAINT uq_puzz_bonus UNIQUE (service_pk, user_pk)
);

COMMENT ON COLUMN puzzle_bonus.service_pk IS 'premium_services.service_pk';
COMMENT ON COLUMN puzzle_bonus.user_pk IS 'users.user_pk';

ALTER TABLE puzzle_bonus ALTER COLUMN table_pk SET DEFAULT nextval('puzzle_bonus_s');
ALTER SEQUENCE puzzle_bonus_s OWNED BY puzzle_bonus.table_pk;

