-- Converted from Oracle: 18_table_news.sql
-- Generated by tools/oracle2pg.py - review before running.

-- news categories
CREATE SEQUENCE IF NOT EXISTS news_categories_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE news_categories (
  category_pk BIGINT PRIMARY KEY,
  category_name VARCHAR(128) NOT NULL UNIQUE,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN news_categories.category_name IS 'category name';
COMMENT ON COLUMN news_categories.position IS 'display order';
COMMENT ON COLUMN news_categories.is_deleted IS '1: deleted';

ALTER TABLE news_categories ALTER COLUMN category_pk SET DEFAULT nextval('news_categories_s');
ALTER SEQUENCE news_categories_s OWNED BY news_categories.category_pk;

-- news articles
CREATE SEQUENCE IF NOT EXISTS news_articles_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE news_articles (
  article_pk BIGINT PRIMARY KEY,
  article_title VARCHAR(512) NOT NULL,
  article_summary VARCHAR(512) NOT NULL,
  cleaned_content VARCHAR(4000) NOT NULL,
  image_url VARCHAR(255),
  category_pk BIGINT,
  article_source SMALLINT DEFAULT 0 NOT NULL,
  status SMALLINT DEFAULT 0,
  publish_org VARCHAR(64),
  publish_num VARCHAR(64),
  hash_summary VARCHAR(255),
  reason VARCHAR(1024),
  provider_pk BIGINT,
  is_deleted SMALLINT DEFAULT 0,
  notice_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_news_article_cat_pk FOREIGN KEY (category_pk) REFERENCES news_categories(category_pk)
);

COMMENT ON COLUMN news_articles.article_title IS 'article title';
COMMENT ON COLUMN news_articles.article_summary IS 'article summary including 1 or 2 sentences';
COMMENT ON COLUMN news_articles.cleaned_content IS 'html stripped content, for content search';
COMMENT ON COLUMN news_articles.image_url IS 'image url if exists';
COMMENT ON COLUMN news_articles.category_pk IS 'news_categories.category_pk';
COMMENT ON COLUMN news_articles.article_source IS '1: morning, 2: polestar';
COMMENT ON COLUMN news_articles.status IS '0: draft or copy, 1: user pending, 2: admin accept, 3: admin deny, 4: pub pending, 5: pub accept, 6: pub deny, 7: pub cancel, 8: notice, 9: news cancel (by provider)';
COMMENT ON COLUMN news_articles.publish_org IS 'original publish approve BIGINT';
COMMENT ON COLUMN news_articles.publish_num IS 'company publish approve BIGINT';
COMMENT ON COLUMN news_articles.hash_summary IS 'hash of summary when pub accepted for prevent modification';
COMMENT ON COLUMN news_articles.reason IS 'reject reason';
COMMENT ON COLUMN news_articles.provider_pk IS 'article id of provider (morning, polestar, ...)';
COMMENT ON COLUMN news_articles.notice_at IS 'notice(display) time';
COMMENT ON COLUMN news_articles.is_deleted IS '1: deleted';

ALTER TABLE news_articles ALTER COLUMN article_pk SET DEFAULT nextval('news_articles_s');
ALTER SEQUENCE news_articles_s OWNED BY news_articles.article_pk;

-- news moning
CREATE TABLE news_morning (
  article_pk BIGINT NOT NULL,
  article_content TEXT,
  article_origin VARCHAR(255),
  cert_data VARCHAR(1024),
  sign_data VARCHAR(1024),
  hash_content VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_news_morning_news_pk FOREIGN KEY (article_pk) REFERENCES news_articles(article_pk)
);

COMMENT ON COLUMN news_morning.article_pk IS 'news_articles.article_pk';
COMMENT ON COLUMN news_morning.article_content IS 'article content';
COMMENT ON COLUMN news_morning.article_origin IS 'origin of article';
COMMENT ON COLUMN news_morning.cert_data IS 'cert data';
COMMENT ON COLUMN news_moring.sign_data IS 'signature data';
COMMENT ON COLUMN news_morning.hash_content IS 'hash of content when pub accepted for prevent modification';

CREATE INDEX idx_news_morning_pk ON news_morning (article_pk);

-- news polestar
CREATE TABLE news_polestar (
  article_pk BIGINT NOT NULL,
  article_content TEXT,
  article_origin VARCHAR(255),
  cert_data VARCHAR(1024),
  sign_data VARCHAR(1024),
  hash_content VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_news_polestar_news_pk FOREIGN KEY (article_pk) REFERENCES news_articles(article_pk)
);

COMMENT ON COLUMN news_polestar.article_pk IS 'news_articles.article_pk';
COMMENT ON COLUMN news_polestar.article_content IS 'article content';
COMMENT ON COLUMN news_polestar.article_origin IS 'origin of article';
COMMENT ON COLUMN news_polestar.cert_data IS 'cert data';
COMMENT ON COLUMN news_polestar.sign_data IS 'signature data';
COMMENT ON COLUMN news_polestar.hash_content IS 'hash of content when pub accepted for prevent modification';

CREATE INDEX idx_news_polestar_pk ON news_polestar (article_pk);

-- news favorites
CREATE SEQUENCE IF NOT EXISTS news_favorites_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE news_favorites (
  table_pk BIGINT PRIMARY KEY,
  user_pk BIGINT NOT NULL,
  article_pk BIGINT NOT NULL,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_news_favorite_user_pk FOREIGN KEY (user_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_news_favorite_article_pk FOREIGN KEY (article_pk) REFERENCES news_articles(article_pk),
  CONSTRAINT uq_news_favorites UNIQUE (user_pk, article_pk)
);

COMMENT ON COLUMN news_favorites.user_pk IS 'users.user_pk';
COMMENT ON COLUMN news_favorites.article_pk IS 'news_articles.article_pk';

ALTER TABLE news_favorites ALTER COLUMN table_pk SET DEFAULT nextval('news_favorites_s');
ALTER SEQUENCE news_favorites_s OWNED BY news_favorites.table_pk;

