-- Converted from Oracle: 19_table_eshops.sql
-- Generated by tools/oracle2pg.py - review before running.

-- eshop cards
CREATE TABLE eshop_cards (
  card_pk BIGINT PRIMARY KEY,
  accum_card BIGINT NOT NULL UNIQUE,
  accum_level VARCHAR(64),
  wallet_card BIGINT,
  wallet_type VARCHAR(64),
  username VARCHAR(64),
  phone_number VARCHAR(64),
  eshop_pk BIGINT,
  eshop_id VARCHAR(64),
  wallet_balance NUMERIC(9,3),
  prize_balance NUMERIC(9,3),
  accum_value NUMERIC(9,3),
  commerce_value NUMERIC(9,3),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN eshop_cards.card_pk IS 'card pk';

-- eshop combine log
CREATE TABLE eshop_combine_log (
  id BIGINT PRIMARY KEY,
  org_user_pk BIGINT,
  org_userid VARCHAR(64),
  target_user_pk BIGINT NOT NULL,
  target_userid VARCHAR(64),
  combine_type SMALLINT DEFAULT 0,
  action_type SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN eshop_combine_log.org_user_pk IS 'orignal user pk';
COMMENT ON COLUMN eshop_combine_log.org_userid IS 'orignal user id';
COMMENT ON COLUMN eshop_combine_log.target_user_pk IS 'target user pk';
COMMENT ON COLUMN eshop_combine_log.target_userid IS 'target user id';
COMMENT ON COLUMN eshop_combine_log.combine_type IS '0: merge id, 1: merge card (mobile), 2: merge card (fixed)';
COMMENT ON COLUMN eshop_combine_log.action_type IS 'merge action by, 0: user, 1: manager';

-- eshop point stats
CREATE TABLE eshop_point_stats (
  accum_card BIGINT PRIMARY KEY,
  accum_level VARCHAR(64),
  wallet_card BIGINT,
  wallet_type VARCHAR(64),
  username VARCHAR(64),
  phone_number VARCHAR(64),
  eshop_pk BIGINT,
  eshop_id VARCHAR(64),
  wallet_balance NUMERIC(9,3),
  prize_balance NUMERIC(9,3),
  accum_value NUMERIC(9,3),
  commerce_value NUMERIC(9,3),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

