-- Converted from Oracle: 20_table_classify.sql
-- Generated by tools/oracle2pg.py - review before running.

-- user class phone
CREATE TABLE uclass_phone_values (
  user_pk BIGINT PRIMARY KEY,
  phone_9 SMALLINT DEFAULT 0,
  phone_7 SMALLINT DEFAULT 0,
  phone_5 SMALLINT DEFAULT 0,
  phone_3 SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN uclass_phone_values.user_pk IS 'users.user_pk';
COMMENT ON COLUMN uclass_phone_values.phone_9 IS '9-category phone register count';
COMMENT ON COLUMN uclass_phone_values.phone_7 IS '7-category phone register count';
COMMENT ON COLUMN uclass_phone_values.phone_5 IS '5-category phone register count';
COMMENT ON COLUMN uclass_phone_values.phone_3 IS '3-category phone register count';

-- user class eprod
CREATE TABLE uclass_eprod_values (
  user_id VARCHAR(50) PRIMARY KEY,
  tv_3 SMALLINT DEFAULT 0,
  tv_2 SMALLINT DEFAULT 0,
  tv_1 SMALLINT DEFAULT 0,
  stb SMALLINT DEFAULT 0,
  notecom SMALLINT DEFAULT 0,
  pc SMALLINT DEFAULT 0,
  camera SMALLINT DEFAULT 0,
  phone SMALLINT DEFAULT 0,
  other SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN uclass_eprod_values.user_id IS 'users.user_id';
COMMENT ON COLUMN uclass_eprod_values.tv_3 IS 'TV (75-100in, smart tv)';
COMMENT ON COLUMN uclass_eprod_values.tv_2 IS 'TV (50-65in)';
COMMENT ON COLUMN uclass_eprod_values.tv_1 IS 'TV (19-43in)';
COMMENT ON COLUMN uclass_eprod_values.stb IS 'STB';
COMMENT ON COLUMN uclass_eprod_values.notecom IS 'notecom (notecom, split, pad)';
COMMENT ON COLUMN uclass_eprod_values.pc IS 'PC (all-in-one, PC, mini-pc)';
COMMENT ON COLUMN uclass_eprod_values.camera IS 'CAMERA, RECORDER';
COMMENT ON COLUMN uclass_eprod_values.phone IS 'wireless line phone';
COMMENT ON COLUMN uclass_eprod_values.other IS 'other (projector, display, QR-scanner, ion-gen, etc)';
