-- Converted from Oracle: 21_crm.sql
-- Generated by tools/oracle2pg.py - review before running.

-- customer
CREATE SEQUENCE IF NOT EXISTS customers_s INCREMENT BY 10 MINVALUE 10000000 MAXVALUE 9223372036854775807 START WITH 10000000;

CREATE TABLE customers (
  ecid BIGINT PRIMARY KEY,
  user_name VARCHAR(50),
  gender CHAR(1) default 'M',
  birth_year VARCHAR(16),
  job VARCHAR(30),
  address VARCHAR(255),
  phone_number VARCHAR(64),
  source SMALLINT DEFAULT 0,
  status SMALLINT DEFAULT 1,
  pvendor_pk BIGINT UNIQUE,
  pvendor_id VARCHAR(50),
  target_id BIGINT,
  note VARCHAR(511),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_customer_gender CHECK (gender IN ('M', 'F'))
);

ALTER TABLE customers ALTER COLUMN ecid SET DEFAULT nextval('customers_s');
ALTER SEQUENCE customers_s OWNED BY customers.ecid;

-- CRM product categories
CREATE SEQUENCE IF NOT EXISTS crm_prod_categories_s INCREMENT BY 2 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_categories (
  category_pk BIGINT PRIMARY KEY,
  category_name VARCHAR(64),
  parent_pk BIGINT,
  position SMALLINT DEFAULT 0,
  is_leaf SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  template_xls VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE crm_prod_categories ALTER COLUMN category_pk SET DEFAULT nextval('crm_prod_categories_s');
ALTER SEQUENCE crm_prod_categories_s OWNED BY crm_prod_categories.category_pk;

-- crm products
CREATE SEQUENCE IF NOT EXISTS crm_products_s INCREMENT BY 2 MINVALUE 100 MAXVALUE 9223372036854775807 START WITH 100;

CREATE TABLE crm_products (
  product_pk BIGINT PRIMARY KEY,
  product_name VARCHAR(128),
  simple_name VARCHAR(64),
  category_pk BIGINT NOT NULL,
  root_pk BIGINT NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_prod_cat_pk FOREIGN KEY (category_pk) REFERENCES crm_prod_categories(category_pk),
  CONSTRAINT fk_crm_prod_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk)
);

ALTER TABLE crm_products ALTER COLUMN product_pk SET DEFAULT nextval('crm_products_s');
ALTER SEQUENCE crm_products_s OWNED BY crm_products.product_pk;

-- crm product spec keys
CREATE SEQUENCE IF NOT EXISTS crm_prod_spec_keys_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_spec_keys (
  spec_pk BIGINT PRIMARY KEY,
  spec_key VARCHAR(64) NOT NULL UNIQUE,
  spec_name VARCHAR(128),
  spec_type SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE crm_prod_spec_keys ALTER COLUMN spec_pk SET DEFAULT nextval('crm_prod_spec_keys_s');
ALTER SEQUENCE crm_prod_spec_keys_s OWNED BY crm_prod_spec_keys.spec_pk;

-- crm product spec values
CREATE SEQUENCE IF NOT EXISTS crm_prod_spec_values_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_spec_values (
  value_pk BIGINT PRIMARY KEY,
  root_pk BIGINT NOT NULL,
  spec_pk BIGINT NOT NULL,
  spec_value VARCHAR(255) NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_prod_val_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk),
  CONSTRAINT fk_crm_prod_val_spec_pk FOREIGN KEY (spec_pk) REFERENCES crm_prod_spec_keys(spec_pk)
);

ALTER TABLE crm_prod_spec_values ALTER COLUMN value_pk SET DEFAULT nextval('crm_prod_spec_values_s');
ALTER SEQUENCE crm_prod_spec_values_s OWNED BY crm_prod_spec_values.value_pk;

-- crm product spec orders
CREATE SEQUENCE IF NOT EXISTS crm_prod_spec_orders_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_spec_orders (
  table_pk BIGINT PRIMARY KEY,
  root_pk BIGINT NOT NULL,
  spec_pk BIGINT NOT NULL,
  position SMALLINT DEFAULT 0,
  is_required SMALLINT DEFAULT 0,
  spec_label VARCHAR(255),
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_spec_order_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk),
  CONSTRAINT fk_crm_spec_order_spec_pk FOREIGN KEY (spec_pk) REFERENCES crm_prod_spec_keys(spec_pk)
);

ALTER TABLE crm_prod_spec_orders ALTER COLUMN table_pk SET DEFAULT nextval('crm_prod_spec_orders_s');
ALTER SEQUENCE crm_prod_spec_orders_s OWNED BY crm_prod_spec_orders.table_pk;

-- crm product survey options
CREATE SEQUENCE IF NOT EXISTS crm_prod_survey_options_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_survey_options (
  option_pk BIGINT PRIMARY KEY,
  root_pk BIGINT NOT NULL,
  option_name VARCHAR(255) NOT NULL,
  position SMALLINT DEFAULT 0,
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_prd_svy_opt_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk)
);

ALTER TABLE crm_prod_survey_options ALTER COLUMN option_pk SET DEFAULT nextval('crm_prod_survey_options_s');
ALTER SEQUENCE crm_prod_survey_options_s OWNED BY crm_prod_survey_options.option_pk;

-- crm product survey responses
CREATE SEQUENCE IF NOT EXISTS crm_prod_survey_responses_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_prod_survey_responses (
  resp_pk BIGINT PRIMARY KEY,
  ecid BIGINT NOT NULL,
  serial_no VARCHAR(25),
  option_pk BIGINT NOT NULL,
  option_name VARCHAR(255),
  rating BIGINT DEFAULT 1,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_prd_svy_rsp_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_prd_svy_rsp_option FOREIGN KEY (option_pk) REFERENCES crm_prod_survey_options(option_pk)
);

ALTER TABLE crm_prod_survey_responses ALTER COLUMN resp_pk SET DEFAULT nextval('crm_prod_survey_responses_s');
ALTER SEQUENCE crm_prod_survey_responses_s OWNED BY crm_prod_survey_responses.resp_pk;

-- crm eprod sale
CREATE SEQUENCE IF NOT EXISTS crm_eprod_sales_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_eprod_sales (
  table_pk BIGINT PRIMARY KEY,
  ecid BIGINT NOT NULL,
  pvendor_pk BIGINT,
  pvendor_id VARCHAR(50),
  user_name VARCHAR(50),
  gender CHAR(1) default 'M',
  birth_year VARCHAR(16),
  job VARCHAR(12),
  address VARCHAR(255),
  phone_number VARCHAR(32),
  serial_no VARCHAR(25) NOT NULL UNIQUE,
  equip_no VARCHAR(25),
  root_pk BIGINT,
  category_name VARCHAR(64),
  product_pk BIGINT,
  product_name VARCHAR(128),
  simple_name VARCHAR(64),
  purchase_place VARCHAR(255),
  purchase_date VARCHAR(32),
  reg_date VARCHAR(32),
  serious_views VARCHAR(255),
  purchase_motives VARCHAR(255),
  old_prod_name VARCHAR(255),
  survey_up VARCHAR(511),
  survey_down VARCHAR(511),
  feedback_msg VARCHAR(1024),
  outlook VARCHAR(255),
  led_type VARCHAR(64),
  has_tv_mount VARCHAR(32),
  is_kara_user VARCHAR(32),
  use_bmedia VARCHAR(32),
  hour_usage VARCHAR(32),
  computer_usage VARCHAR(128),
  install_loc VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_eprod_sales_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eprod_sales_user_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_crm_eprod_sales_user_id FOREIGN KEY (pvendor_id) REFERENCES users(user_id),
  CONSTRAINT fk_crm_eprod_sales_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk),
  CONSTRAINT fk_crm_eprod_sales_prod_pk FOREIGN KEY (product_pk) REFERENCES crm_products(product_pk)
);

ALTER TABLE crm_eprod_sales ALTER COLUMN table_pk SET DEFAULT nextval('crm_eprod_sales_s');
ALTER SEQUENCE crm_eprod_sales_s OWNED BY crm_eprod_sales.table_pk;

-- crm eprod transfer log
CREATE SEQUENCE IF NOT EXISTS crm_eprod_trans_log_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_eprod_trans_log (
  log_pk BIGINT PRIMARY KEY,
  table_pk BIGINT,
  ecid BIGINT NOT NULL,
  pvendor_pk BIGINT,
  target_id BIGINT,
  target_pk BIGINT,
  user_name VARCHAR(50),
  gender CHAR(1) default 'M',
  birth_year VARCHAR(16),
  job VARCHAR(12),
  address VARCHAR(255),
  phone_number VARCHAR(32),
  serial_no VARCHAR(25) NOT NULL,
  equip_no VARCHAR(25),
  root_pk BIGINT,
  category_name VARCHAR(64),
  product_name VARCHAR(128),
  purchase_place VARCHAR(255),
  purchase_date VARCHAR(32),
  reg_date VARCHAR(32),
  serious_views VARCHAR(255),
  purchase_motives VARCHAR(255),
  old_prod_name VARCHAR(255),
  survey_up VARCHAR(511),
  survey_down VARCHAR(511),
  feedback_msg VARCHAR(1024),
  outlook VARCHAR(255),
  led_type VARCHAR(64),
  has_tv_mount VARCHAR(32),
  is_kara_user VARCHAR(32),
  use_bmedia VARCHAR(32),
  hour_usage VARCHAR(32),
  computer_usage VARCHAR(128),
  install_loc VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  transfered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_eprod_trans_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eprod_trans_prhn_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_crm_eprod_trans_target_id FOREIGN KEY (target_id) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eprod_trans_target_pk FOREIGN KEY (target_pk) REFERENCES users(user_pk)
);

ALTER TABLE crm_eprod_trans_log ALTER COLUMN log_pk SET DEFAULT nextval('crm_eprod_trans_log_s');
ALTER SEQUENCE crm_eprod_trans_log_s OWNED BY crm_eprod_trans_log.log_pk;

-- crm product spec value chosen
CREATE SEQUENCE IF NOT EXISTS crm_eprod_chosen_specs_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_eprod_chosen_specs (
  table_pk BIGINT PRIMARY KEY,
  ecid BIGINT NOT NULL,
  serial_no VARCHAR(25),
  product_pk BIGINT,
  value_pk BIGINT,
  spec_value VARCHAR(255),
  position SMALLINT DEFAULT 0,
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_eprod_chosen_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eprod_chosen_prod_pk FOREIGN KEY (product_pk) REFERENCES crm_products(product_pk),
  CONSTRAINT fk_crm_eprod_chosen_val_pk FOREIGN KEY (value_pk) REFERENCES crm_prod_spec_values(value_pk)
);

ALTER TABLE crm_eprod_chosen_specs ALTER COLUMN table_pk SET DEFAULT nextval('crm_eprod_chosen_specs_s');
ALTER SEQUENCE crm_eprod_chosen_specs_s OWNED BY crm_eprod_chosen_specs.table_pk;

-- crm eprod after service
CREATE SEQUENCE IF NOT EXISTS crm_eprod_as_s INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;

CREATE TABLE crm_eprod_as (
  table_pk BIGINT PRIMARY KEY,
  ecid BIGINT NOT NULL,
  pvendor_pk BIGINT,
  pvendor_id VARCHAR(50),
  user_name VARCHAR(50),
  gender CHAR(1) default 'M',
  birth_year VARCHAR(16),
  job VARCHAR(12),
  address VARCHAR(255),
  phone_number VARCHAR(32),
  serial_no VARCHAR(25) NOT NULL,
  root_pk BIGINT,
  category_name VARCHAR(64),
  product_pk BIGINT,
  product_name VARCHAR(128),
  simple_name VARCHAR(64),
  damages VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_eprod_as_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eprod_as_user_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_crm_eprod_as_user_id FOREIGN KEY (pvendor_id) REFERENCES users(user_id),
  CONSTRAINT fk_crm_eprod_as_root_pk FOREIGN KEY (root_pk) REFERENCES crm_prod_categories(category_pk),
  CONSTRAINT fk_crm_eprod_as_prod_pk FOREIGN KEY (product_pk) REFERENCES crm_products(product_pk)
);

ALTER TABLE crm_eprod_as ALTER COLUMN table_pk SET DEFAULT nextval('crm_eprod_as_s');
ALTER SEQUENCE crm_eprod_as_s OWNED BY crm_eprod_as.table_pk;

-- crm mars cards
CREATE TABLE crm_mars_cards (
  card_pk BIGINT PRIMARY KEY,
  ecid BIGINT,
  pvendor_pk BIGINT,
  pvendor_id VARCHAR(50),
  prhn_name VARCHAR(50),
  eshop_pk VARCHAR(64),
  eshop_id VARCHAR(50),
  accum_card VARCHAR(12) NOT NULL,
  wallet_card VARCHAR(12),
  card_name VARCHAR(50),
  phone_number VARCHAR(120),
  birthday VARCHAR(10),
  crm_level VARCHAR(50),
  vip_level1 VARCHAR(50),
  vip_level2 VARCHAR(50),
  vip_level3 VARCHAR(50),
  crm_class VARCHAR(50),
  max_cnt_product VARCHAR(255),
  all_months SMALLINT DEFAULT 0,
  buy_months SMALLINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_mars_card_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_mars_card_user_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_crm_mars_card_user_id FOREIGN KEY (pvendor_id) REFERENCES users(user_id)
);

-- crm eshop info
CREATE TABLE crm_eshop_info (
  eshop_pk VARCHAR(64) PRIMARY KEY,
  eshop_id VARCHAR(50),
  eshop_name VARCHAR(50),
  ecid BIGINT,
  pvendor_pk BIGINT,
  pvendor_id VARCHAR(50),
  prhn_name VARCHAR(50),
  phone_number VARCHAR(120),
  eshop_gender CHAR(1) default 'M',
  eshop_job VARCHAR(120),
  eshop_cid VARCHAR(12),
  crm_level SMALLINT,
  crm_grade SMALLINT,
  crm_level_desc VARCHAR(120),
  crm_grade_desc VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_crm_eshop_info_ecid FOREIGN KEY (ecid) REFERENCES customers(ecid),
  CONSTRAINT fk_crm_eshop_info_user_pk FOREIGN KEY (pvendor_pk) REFERENCES users(user_pk),
  CONSTRAINT fk_crm_eshop_info_user_id FOREIGN KEY (pvendor_id) REFERENCES users(user_id)
);
