-- Converted from Oracle: blog_tables.sql
-- Generated by tools/oracle2pg.py - review before running.



CREATE INDEX idx_blog_status ON blogs(status);
CREATE INDEX idx_blog_category ON blogs(category_id);
CREATE INDEX idx_blog_user ON blogs(user_pk);
CREATE INDEX idx_blog_content_text ON blogs(content) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX idx_blogs_search ON blogs(title, REGEXP_REPLACE(content, '<[^>]+>', ''));

CREATE TABLE blog_ratings (
  rating_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
  user_pk BIGINT NOT NULL,  -- User who gave the rating (references users table)
  blog_pk BIGINT NOT NULL,  -- Blog that was rated (references blogs table)
  rating_type BIGINT CHECK (rating_type IN (1, 2)) NOT NULL,  -- Rating type: 1 for thumb, 2 for star
  rating_value BIGINT CHECK (rating_value BETWEEN 1 AND 5) NOT NULL,  -- Rating value (1-3 for thumbs, 1-5 for stars)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Rating creation timestamp
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  -- Rating update timestamp
  UNIQUE (user_pk, blog_pk, rating_type),  -- A user can either thumb or rate a blog, but not both of the same type
  FOREIGN KEY (user_pk) REFERENCES users(user_pk),  -- Foreign key to users table
  FOREIGN KEY (blog_pk) REFERENCES blogs(blog_pk)  -- Foreign key to blogs table
);

CREATE TABLE blog_history (
  history_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing primary key
  blog_pk BIGINT NOT NULL,  -- Foreign key to the blog
  user_pk BIGINT NOT NULL,  -- User who performed the action
  action_type VARCHAR(255) NOT NULL,  -- The action performed ('update', 'delete', 'create')
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- When the action occurred
  FOREIGN KEY (blog_pk) REFERENCES blogs(blog_pk),  -- References the blog
  FOREIGN KEY (user_pk) REFERENCES users(user_pk)  -- References the user who performed the action
);

CREATE TABLE blog_followers (
  follow_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Primary key for the followers table
  follower_user_pk BIGINT NOT NULL,  -- The user who follows
  followed_user_pk BIGINT NOT NULL,  -- The user being followed
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp when the follow happened
  FOREIGN KEY (follower_user_pk) REFERENCES users(user_pk),  -- Foreign key to the user following
  FOREIGN KEY (followed_user_pk) REFERENCES users(user_pk),  -- Foreign key to the user being followed
  CONSTRAINT chk_self_follow CHECK (follower_user_pk != followed_user_pk),  -- Prevents a user from following themselves
  UNIQUE (follower_user_pk, followed_user_pk)  -- Ensures that a user can follow another only once
);

CREATE TABLE blog_favorites (
  favorite_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Primary key for the favorites table
  user_pk BIGINT NOT NULL,  -- The user marking or unmarking the blog as favorite
  blog_pk BIGINT NOT NULL,  -- The blog being marked/unmarked as favorite
  is_favorite SMALLINT DEFAULT 1,  -- 1: Marked as favorite, 0: Unmarked
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp when the blog was initially marked as favorite
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  -- Timestamp when the favorite status was last updated
  FOREIGN KEY (user_pk) REFERENCES users(user_pk),  -- Foreign key to the user
  FOREIGN KEY (blog_pk) REFERENCES blogs(blog_pk),  -- Foreign key to the blog
  UNIQUE (user_pk, blog_pk),  -- Ensures that a user can only have one entry per blog
  CONSTRAINT chk_is_favorite CHECK (is_favorite IN (0, 1))  -- Ensures the value of is_favorite is either 0 (unmarked) or 1 (marked)
);

CREATE TABLE blog_visits (
  visit_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Primary key for the visits table
  blog_pk BIGINT NOT NULL,  -- Blog being visited
  user_pk BIGINT,  -- The logged-in user (if available, NULL for non-logged-in users)
  ip_address VARCHAR(45),  -- IP address for non-logged-in users (IPv4 or IPv6)
  session_id VARCHAR(255),  -- Session identifier for non-logged-in users
  visited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- When the visit occurred
  FOREIGN KEY (blog_pk) REFERENCES blogs(blog_pk),  -- Foreign key to the blog
  FOREIGN KEY (user_pk) REFERENCES users(user_pk),  -- Foreign key to the user (can be NULL)
  CONSTRAINT unique_user_or_session_visit UNIQUE (blog_pk, user_pk, ip_address, session_id)  -- Ensures unique visits
);

CREATE TABLE blog_statistics (
  blog_pk BIGINT PRIMARY KEY,  -- Blog identifier
  visit_count BIGINT DEFAULT 0,  -- Total visit count (from blog_visits)
  rating_count BIGINT DEFAULT 0,  -- Total rating count (from blog_ratings)
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Last time statistics were updated
);

CREATE TABLE point_types (
  point_type BIGINT PRIMARY KEY,  -- The point type BIGINT
  description VARCHAR(255) NOT NULL,  -- A description for each point type (e.g., 'Thumb Up', 'Post Main Article')
  points BIGINT NOT NULL  -- The BIGINT of points associated with each action
);

INSERT INTO point_types (point_type, description, points) VALUES (1, 'Thumb Up', 1);
INSERT INTO point_types (point_type, description, points) VALUES (2, 'Post Main Article', 100);
INSERT INTO point_types (point_type, description, points) VALUES (3, 'Post Reply Article', 30);

CREATE TABLE activity_points (
  point_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incremented primary key
  user_pk BIGINT NOT NULL,  -- Foreign key to the user who received the points
  points BIGINT NOT NULL,  -- Points awarded for the action
  point_type BIGINT NOT NULL,  -- Type of point (represented as a BIGINT)
  reason VARCHAR(255) NOT NULL,  -- Description of the action (e.g., 'Thumb up', 'Post main article')
  related_pk BIGINT,  -- Foreign key to the relevant table (blog_ratings, blogs, etc.)
  action_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Timestamp for when the activity occurred
  FOREIGN KEY (user_pk) REFERENCES users(user_pk),  -- Foreign key to the users table
  FOREIGN KEY (point_type) REFERENCES point_types(point_type)  -- Foreign key to point_types
);

-- This trigger will update the visit_count in blog_statistics each time a user visits a blog.
-- [MANUAL] trigger moved to _MANUAL_REVIEW.sql

-- This trigger will update the rating_count in blog_statistics each time a user rates a blog.
-- [MANUAL] trigger moved to _MANUAL_REVIEW.sql

-- When inserting a record into the activity_points table, you can now automatically pull the points value from the point_types table.
-- Trigger for blog_ratings (Thumb Up/Down):
-- [MANUAL] trigger moved to _MANUAL_REVIEW.sql

-- Trigger for blogs (Post Main Article or Reply):
-- [MANUAL] trigger moved to _MANUAL_REVIEW.sql

CREATE INDEX idx_blog_status ON blogs(status);
CREATE INDEX idx_blog_category ON blogs(category_id);
CREATE INDEX idx_blog_user ON blogs(user_pk);
CREATE INDEX idx_blog_content_text ON blogs(content) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX idx_blogs_search ON blogs(title, REGEXP_REPLACE(content, '<[^>]+>', ''));

-- Index on category_id for filtering by category
CREATE INDEX idx_category_id ON blogs (category_id);

-- Index on user_pk for joining with users table
CREATE INDEX idx_user_pk ON blogs (user_pk);

-- Index on title for searching by title
CREATE INDEX idx_title ON blogs (title);

-- Index on blog_pk for pagination (ordering by primary key)
CREATE INDEX idx_blog_pk ON blogs (blog_pk);

-- Index on user_name for searching by user name in users table
CREATE INDEX idx_user_name ON users (user_name);

-- Create index on cleaned content
CREATE INDEX idx_blogs_cleaned_content ON blogs(cleaned_content);

-- Create a full-text index on the content column of the blogs table
CREATE INDEX idx_content_fulltext ON blogs (content) 
  INDEXTYPE IS CTXSYS.CONTEXT;

CREATE INDEX idx_blogs_search ON blogs(
  title, 
  REGEXP_REPLACE(content, '<[^>]+>', '') -- Cleaned content without HTML tags
);

